// 自動產生 —— 不要手改。來源：tools/generate_hints.js
//
// 第二層提示（「關鍵步驟」）的補充。只補作者沒寫的題。
//
// 每一條都是**這一題特有的、機器判定出來的事實**，不是罐頭句子：
// 「直接代入會得到 0/0」、「f(x)+f(π−x) 恆等於 2」、「比值判別的極限明顯小於 1」。
// 罐頭句子（「先求反導數再代入上下限」）對每一題都成立，也就是對每一題都沒用。
//
// 每一條都帶一個 claim，tools/validate_derived_hints.js 每次 CI 都會**重新算一次**。
// 題目改了、事實不成立了，會當場變紅 —— 這是自動產生內容唯一能被接受的形式。
//
// 畫面上會標明這些是機器推導的，不要讓它看起來像有人背書。
//
// 重新產生：node tools/generate_hints.js

(function () {
  "use strict";

  const DERIVED_HINTS = {
    "cx-der-005": { text: "最外層是商，用商法則 (u/v)' = (u'v − uv')/v²。也可以改寫成 u·v⁻¹ 用乘積律。", claim: {"k":"outer","v":"quotient"} },
    "cx-der-006": { text: "最外層是一個函數套著另一個函數，用鏈鎖律：先微外層、再乘內層的導數。", claim: {"k":"outer","v":"chain"} },
    "cx-exam-001": { text: "直接代入會得到 0/0，不能硬代 —— 要先化簡、有理化，或用 L'Hôpital 與泰勒展開。", claim: {"k":"limitForm","v":"0/0"} },
    "cx-exam-008": { text: "比值判別：|aₙ₊₁/aₙ| 在 n=20…120 之間一路落在 0.496 以下（最後約 0.495868），明顯小於 1 —— 收斂。", claim: {"k":"ratio","v":0.495868} },
    "cx-hi-001": { text: "區間是 [0,∞) 而被積函數是代數型（沒有指數在壓）—— 它收斂靠的是分母長得比分子快。這種積分用分部積分做不出來，要往 Beta/Gamma、留數或參數微分想。", claim: {"k":"algImproper","v":1} },
    "cx-hi-007": { text: "區間是 [0,∞) 而被積函數是代數型（沒有指數在壓）—— 它收斂靠的是分母長得比分子快。這種積分用分部積分做不出來，要往 Beta/Gamma、留數或參數微分想。", claim: {"k":"algImproper","v":1} },
    "cx-hm-002": { text: "把 x 換成 π/2−x 之後兩式相加：f(x)+f(π/2−x) 恆等於 1，所以 2I = 1×(區間長度)。", claim: {"k":"kings","v":1} },
    "cx-hs-003": { text: "比值判別：|aₙ₊₁/aₙ| 在 n=20…120 之間一路落在 0.0477 以下（最後約 0.00826503），明顯小於 1 —— 收斂。", claim: {"k":"ratio","v":0.00826503} },
    "cx-king-001": { text: "把 x 換成 π/2−x 之後兩式相加：f(x)+f(π/2−x) 恆等於 1，所以 2I = 1×(區間長度)。", claim: {"k":"kings","v":1} },
    "cx-lh-001": { text: "直接代入會得到 0/0，不能硬代 —— 要先化簡、有理化，或用 L'Hôpital 與泰勒展開。", claim: {"k":"limitForm","v":"0/0"} },
    "cx-lh-002": { text: "直接代入會得到 0/0，不能硬代 —— 要先化簡、有理化，或用 L'Hôpital 與泰勒展開。", claim: {"k":"limitForm","v":"0/0"} },
    "cx-lh-007": { text: "直接代入會得到 0/0，不能硬代 —— 要先化簡、有理化，或用 L'Hôpital 與泰勒展開。", claim: {"k":"limitForm","v":"0/0"} },
    "cx-lh-009": { text: "直接代入會得到 0/0，不能硬代 —— 要先化簡、有理化，或用 L'Hôpital 與泰勒展開。", claim: {"k":"limitForm","v":"0/0"} },
    "cx-lh-010": { text: "直接代入會得到 0/0，不能硬代 —— 要先化簡、有理化，或用 L'Hôpital 與泰勒展開。", claim: {"k":"limitForm","v":"0/0"} },
    "cx-lh-011": { text: "直接代入會得到 0/0，不能硬代 —— 要先化簡、有理化，或用 L'Hôpital 與泰勒展開。", claim: {"k":"limitForm","v":"0/0"} },
    "cx-lim-002": { text: "直接代入會得到 0/0，不能硬代 —— 要先化簡、有理化，或用 L'Hôpital 與泰勒展開。", claim: {"k":"limitForm","v":"0/0"} },
    "cx-lim-003": { text: "分子分母都不趨近 0 或 ∞，直接代入就是答案 —— 這題考的是「先確認不是不定型」。", claim: {"k":"limitForm","v":"direct"} },
    "cx-lim-004": { text: "直接代入會得到 0/0，不能硬代 —— 要先化簡、有理化，或用 L'Hôpital 與泰勒展開。", claim: {"k":"limitForm","v":"0/0"} },
    "cx-lim-005": { text: "直接代入會得到 0/0，不能硬代 —— 要先化簡、有理化，或用 L'Hôpital 與泰勒展開。", claim: {"k":"limitForm","v":"0/0"} },
    "cx-lim-009": { text: "直接代入會得到 0/0，不能硬代 —— 要先化簡、有理化，或用 L'Hôpital 與泰勒展開。", claim: {"k":"limitForm","v":"0/0"} },
    "cx-ser-003": { text: "比值判別：|aₙ₊₁/aₙ| 在 n=20…120 之間一路落在 0.667 以下（最後約 0.666667），明顯小於 1 —— 收斂。", claim: {"k":"ratio","v":0.666667} },
    "cx-ser-008": { text: "比值判別：|aₙ₊₁/aₙ| 在 n=20…120 之間一路落在 0.0476 以下（最後約 0.00826446），明顯小於 1 —— 收斂。", claim: {"k":"ratio","v":0.00826446} },
    "cx-smid-011": { text: "比值判別：|aₙ₊₁/aₙ| 在 n=20…80 之間一路落在 0.256 以下（最後約 0.251553），明顯小於 1 —— 收斂。", claim: {"k":"ratio","v":0.251553} },
    "dd-def-001": { text: "直接代入會得到 0/0，不能硬代 —— 要先化簡、有理化，或用 L'Hôpital 與泰勒展開。", claim: {"k":"limitForm","v":"0/0"} },
    "dd-def-003": { text: "直接代入會得到 0/0，不能硬代 —— 要先化簡、有理化，或用 L'Hôpital 與泰勒展開。", claim: {"k":"limitForm","v":"0/0"} },
    "dd-def-004": { text: "直接代入會得到 0/0，不能硬代 —— 要先化簡、有理化，或用 L'Hôpital 與泰勒展開。", claim: {"k":"limitForm","v":"0/0"} },
    "dd-def-005": { text: "直接代入會得到 0/0，不能硬代 —— 要先化簡、有理化，或用 L'Hôpital 與泰勒展開。", claim: {"k":"limitForm","v":"0/0"} },
    "dd-inv-003": { text: "最外層是加減，先逐項微分，不要急著套乘積或商法則。", claim: {"k":"outer","v":"sum"} },
    "dd-inv-004": { text: "最外層是一個函數套著另一個函數，用鏈鎖律：先微外層、再乘內層的導數。", claim: {"k":"outer","v":"chain"} },
    "dd-inv-005": { text: "最外層是一個函數套著另一個函數，用鏈鎖律：先微外層、再乘內層的導數。", claim: {"k":"outer","v":"chain"} },
    "dd-inv-006": { text: "最外層是一個函數套著另一個函數，用鏈鎖律：先微外層、再乘內層的導數。", claim: {"k":"outer","v":"chain"} },
    "dd-inv-007": { text: "最外層是一個函數套著另一個函數，用鏈鎖律：先微外層、再乘內層的導數。", claim: {"k":"outer","v":"chain"} },
    "dd-inv-008": { text: "最外層是商，用商法則 (u/v)' = (u'v − uv')/v²。也可以改寫成 u·v⁻¹ 用乘積律。", claim: {"k":"outer","v":"quotient"} },
    "dd-log-001": { text: "最外層是一個函數套著另一個函數，用鏈鎖律：先微外層、再乘內層的導數。", claim: {"k":"outer","v":"chain"} },
    "dd-log-002": { text: "最外層是一個函數套著另一個函數，用鏈鎖律：先微外層、再乘內層的導數。", claim: {"k":"outer","v":"chain"} },
    "dd-log-003": { text: "最外層是一個函數套著另一個函數，用鏈鎖律：先微外層、再乘內層的導數。", claim: {"k":"outer","v":"chain"} },
    "dd-log-004": { text: "最外層是一個函數套著另一個函數，用鏈鎖律：先微外層、再乘內層的導數。", claim: {"k":"outer","v":"chain"} },
    "dd-log-005": { text: "最外層是一個函數套著另一個函數，用鏈鎖律：先微外層、再乘內層的導數。", claim: {"k":"outer","v":"chain"} },
    "dd-log-006": { text: "最外層是一個函數套著另一個函數，用鏈鎖律：先微外層、再乘內層的導數。", claim: {"k":"outer","v":"chain"} },
    "dd-log-007": { text: "最外層是一個函數套著另一個函數，用鏈鎖律：先微外層、再乘內層的導數。", claim: {"k":"outer","v":"chain"} },
    "dd-log-008": { text: "最外層是商，用商法則 (u/v)' = (u'v − uv')/v²。也可以改寫成 u·v⁻¹ 用乘積律。", claim: {"k":"outer","v":"quotient"} },
    "dd-log-009": { text: "最外層是一個函數套著另一個函數，用鏈鎖律：先微外層、再乘內層的導數。", claim: {"k":"outer","v":"chain"} },
    "dd-log-010": { text: "最外層是一個函數套著另一個函數，用鏈鎖律：先微外層、再乘內層的導數。", claim: {"k":"outer","v":"chain"} },
    "dd-nest-001": { text: "最外層是一個函數套著另一個函數，用鏈鎖律：先微外層、再乘內層的導數。", claim: {"k":"outer","v":"chain"} },
    "dd-nest-002": { text: "最外層是一個函數套著另一個函數，用鏈鎖律：先微外層、再乘內層的導數。", claim: {"k":"outer","v":"chain"} },
    "dd-nest-003": { text: "最外層是一個函數套著另一個函數，用鏈鎖律：先微外層、再乘內層的導數。", claim: {"k":"outer","v":"chain"} },
    "dd-nest-006": { text: "最外層是一個函數套著另一個函數，用鏈鎖律：先微外層、再乘內層的導數。", claim: {"k":"outer","v":"chain"} },
    "dd-nest-008": { text: "最外層是一個函數套著另一個函數，用鏈鎖律：先微外層、再乘內層的導數。", claim: {"k":"outer","v":"chain"} },
    "der-001": { text: "最外層是加減，先逐項微分，不要急著套乘積或商法則。", claim: {"k":"outer","v":"sum"} },
    "der-002": { text: "最外層是加減，先逐項微分，不要急著套乘積或商法則。", claim: {"k":"outer","v":"sum"} },
    "der-003": { text: "最外層是兩個函數相乘，用乘積律 (uv)' = u'v + uv'。", claim: {"k":"outer","v":"product"} },
    "der-004": { text: "最外層是一個函數套著另一個函數，用鏈鎖律：先微外層、再乘內層的導數。", claim: {"k":"outer","v":"chain"} },
    "der-005": { text: "最外層是一個函數套著另一個函數，用鏈鎖律：先微外層、再乘內層的導數。", claim: {"k":"outer","v":"chain"} },
    "der-006": { text: "最外層是兩個函數相乘，用乘積律 (uv)' = u'v + uv'。", claim: {"k":"outer","v":"product"} },
    "der-007": { text: "最外層是一個函數套著另一個函數，用鏈鎖律：先微外層、再乘內層的導數。", claim: {"k":"outer","v":"chain"} },
    "der-008": { text: "最外層是商，用商法則 (u/v)' = (u'v − uv')/v²。也可以改寫成 u·v⁻¹ 用乘積律。", claim: {"k":"outer","v":"quotient"} },
    "der-009": { text: "最外層是一個函數套著另一個函數，用鏈鎖律：先微外層、再乘內層的導數。", claim: {"k":"outer","v":"chain"} },
    "der-010": { text: "最外層是兩個函數相乘，用乘積律 (uv)' = u'v + uv'。", claim: {"k":"outer","v":"product"} },
    "der-011": { text: "最外層是一個函數套著另一個函數，用鏈鎖律：先微外層、再乘內層的導數。", claim: {"k":"outer","v":"chain"} },
    "der-012": { text: "最外層是商，用商法則 (u/v)' = (u'v − uv')/v²。也可以改寫成 u·v⁻¹ 用乘積律。", claim: {"k":"outer","v":"quotient"} },
    "der-013": { text: "最外層是一個函數套著另一個函數，用鏈鎖律：先微外層、再乘內層的導數。", claim: {"k":"outer","v":"chain"} },
    "der-014": { text: "最外層是一個函數套著另一個函數，用鏈鎖律：先微外層、再乘內層的導數。", claim: {"k":"outer","v":"chain"} },
    "der-015": { text: "最外層是一個函數套著另一個函數，用鏈鎖律：先微外層、再乘內層的導數。", claim: {"k":"outer","v":"chain"} },
    "der-016": { text: "最外層是商，用商法則 (u/v)' = (u'v − uv')/v²。也可以改寫成 u·v⁻¹ 用乘積律。", claim: {"k":"outer","v":"quotient"} },
    "der-017": { text: "最外層是兩個函數相乘，用乘積律 (uv)' = u'v + uv'。", claim: {"k":"outer","v":"product"} },
    "der-018": { text: "最外層是一個函數套著另一個函數，用鏈鎖律：先微外層、再乘內層的導數。", claim: {"k":"outer","v":"chain"} },
    "der-019": { text: "最外層是一個函數套著另一個函數，用鏈鎖律：先微外層、再乘內層的導數。", claim: {"k":"outer","v":"chain"} },
    "der-020": { text: "最外層是一個函數套著另一個函數，用鏈鎖律：先微外層、再乘內層的導數。", claim: {"k":"outer","v":"chain"} },
    "hd-010": { text: "最外層是一個函數套著另一個函數，用鏈鎖律：先微外層、再乘內層的導數。", claim: {"k":"outer","v":"chain"} },
    "hd-011": { text: "最外層是一個函數套著另一個函數，用鏈鎖律：先微外層、再乘內層的導數。", claim: {"k":"outer","v":"chain"} },
    "int-012": { text: "把 x 換成 π/2−x 之後兩式相加：f(x)+f(π/2−x) 恆等於 1，所以 2I = 1×(區間長度)。", claim: {"k":"kings","v":1} },
    "lim-001": { text: "直接代入會得到 0/0，不能硬代 —— 要先化簡、有理化，或用 L'Hôpital 與泰勒展開。", claim: {"k":"limitForm","v":"0/0"} },
    "lim-002": { text: "直接代入會得到 0/0，不能硬代 —— 要先化簡、有理化，或用 L'Hôpital 與泰勒展開。", claim: {"k":"limitForm","v":"0/0"} },
    "lim-003": { text: "直接代入會得到 0/0，不能硬代 —— 要先化簡、有理化，或用 L'Hôpital 與泰勒展開。", claim: {"k":"limitForm","v":"0/0"} },
    "lim-004": { text: "直接代入會得到 ∞/∞，分子分母同除以最高次項，或用 L'Hôpital。", claim: {"k":"limitForm","v":"inf/inf"} },
    "lim-005": { text: "直接代入會得到 0/0，不能硬代 —— 要先化簡、有理化，或用 L'Hôpital 與泰勒展開。", claim: {"k":"limitForm","v":"0/0"} },
    "lim-006": { text: "直接代入會得到 0/0，不能硬代 —— 要先化簡、有理化，或用 L'Hôpital 與泰勒展開。", claim: {"k":"limitForm","v":"0/0"} },
    "lim-007": { text: "直接代入會得到 0/0，不能硬代 —— 要先化簡、有理化，或用 L'Hôpital 與泰勒展開。", claim: {"k":"limitForm","v":"0/0"} },
    "lim-009": { text: "直接代入會得到 0/0，不能硬代 —— 要先化簡、有理化，或用 L'Hôpital 與泰勒展開。", claim: {"k":"limitForm","v":"0/0"} },
    "lim-010": { text: "直接代入會得到 0/0，不能硬代 —— 要先化簡、有理化，或用 L'Hôpital 與泰勒展開。", claim: {"k":"limitForm","v":"0/0"} },
    "lim-012": { text: "直接代入會得到 0/0，不能硬代 —— 要先化簡、有理化，或用 L'Hôpital 與泰勒展開。", claim: {"k":"limitForm","v":"0/0"} },
    "lim-013": { text: "直接代入會得到 0/0，不能硬代 —— 要先化簡、有理化，或用 L'Hôpital 與泰勒展開。", claim: {"k":"limitForm","v":"0/0"} },
    "lim-014": { text: "直接代入會得到 0/0，不能硬代 —— 要先化簡、有理化，或用 L'Hôpital 與泰勒展開。", claim: {"k":"limitForm","v":"0/0"} },
    "lim-015": { text: "直接代入會得到 0/0，不能硬代 —— 要先化簡、有理化，或用 L'Hôpital 與泰勒展開。", claim: {"k":"limitForm","v":"0/0"} },
    "lim-017": { text: "直接代入會得到 0/0，不能硬代 —— 要先化簡、有理化，或用 L'Hôpital 與泰勒展開。", claim: {"k":"limitForm","v":"0/0"} },
    "lim-018": { text: "直接代入會得到 0/0，不能硬代 —— 要先化簡、有理化，或用 L'Hôpital 與泰勒展開。", claim: {"k":"limitForm","v":"0/0"} },
    "lim-019": { text: "直接代入會得到 0/0，不能硬代 —— 要先化簡、有理化，或用 L'Hôpital 與泰勒展開。", claim: {"k":"limitForm","v":"0/0"} },
    "lim-020": { text: "直接代入會得到 0/0，不能硬代 —— 要先化簡、有理化，或用 L'Hôpital 與泰勒展開。", claim: {"k":"limitForm","v":"0/0"} },
    "mob-conv-006": { text: "比值判別：|aₙ₊₁/aₙ| 在 n=20…120 之間一路落在 0.0952 以下（最後約 0.0165289），明顯小於 1 —— 收斂。", claim: {"k":"ratio","v":0.0165289} },
    "mob-limtrap-003": { text: "直接代入會得到 0/0，不能硬代 —— 要先化簡、有理化，或用 L'Hôpital 與泰勒展開。", claim: {"k":"limitForm","v":"0/0"} },
    "mob-limtrap-004": { text: "直接代入會得到 0/0，不能硬代 —— 要先化簡、有理化，或用 L'Hôpital 與泰勒展開。", claim: {"k":"limitForm","v":"0/0"} },
    "mob-limtrap-005": { text: "直接代入會得到 0/0，不能硬代 —— 要先化簡、有理化，或用 L'Hôpital 與泰勒展開。", claim: {"k":"limitForm","v":"0/0"} },
    "mob-limtrap-006": { text: "直接代入會得到 0/0，不能硬代 —— 要先化簡、有理化，或用 L'Hôpital 與泰勒展開。", claim: {"k":"limitForm","v":"0/0"} },
    "mob-tech-002": { text: "直接代入會得到 0/0，不能硬代 —— 要先化簡、有理化，或用 L'Hôpital 與泰勒展開。", claim: {"k":"limitForm","v":"0/0"} },
    "mob-tech-007": { text: "比值判別：|aₙ₊₁/aₙ| 在 n=20…120 之間一路在 7 以上（最後約 40.3333），明顯大於 1 —— 發散。", claim: {"k":"ratio","v":40.3333} },
    "mob-tech-008": { text: "比值判別：|aₙ₊₁/aₙ| 在 n=20…120 之間一路落在 0.5 以下（最後約 0.499996），明顯小於 1 —— 收斂。", claim: {"k":"ratio","v":0.499996} },
    "mob-trap-001": { text: "最外層是一個函數套著另一個函數，用鏈鎖律：先微外層、再乘內層的導數。", claim: {"k":"outer","v":"chain"} },
    "mob-trap-007": { text: "最外層是一個函數套著另一個函數，用鏈鎖律：先微外層、再乘內層的導數。", claim: {"k":"outer","v":"chain"} },
    "mob-wallis-005": { text: "把 x 換成 π/2−x 之後兩式相加：f(x)+f(π/2−x) 恆等於 1，所以 2I = 1×(區間長度)。", claim: {"k":"kings","v":1} },
    "putnam-005": { text: "把 x 換成 π/2−x 之後兩式相加：f(x)+f(π/2−x) 恆等於 1，所以 2I = 1×(區間長度)。", claim: {"k":"kings","v":1} },
    "putnam-009": { text: "區間是 [0,∞) 而被積函數是代數型（沒有指數在壓）—— 它收斂靠的是分母長得比分子快。這種積分用分部積分做不出來，要往 Beta/Gamma、留數或參數微分想。", claim: {"k":"algImproper","v":1} },
    "putnam-012": { text: "區間是 [0,∞) 而被積函數是代數型（沒有指數在壓）—— 它收斂靠的是分母長得比分子快。這種積分用分部積分做不出來，要往 Beta/Gamma、留數或參數微分想。", claim: {"k":"algImproper","v":1} },
    "rel-adv-002": { text: "直接代入會得到 0/0，不能硬代 —— 要先化簡、有理化，或用 L'Hôpital 與泰勒展開。", claim: {"k":"limitForm","v":"0/0"} },
    "rel-adv-015": { text: "比值判別：|aₙ₊₁/aₙ| 在 n=20…120 之間一路落在 0.333 以下（最後約 0.333332），明顯小於 1 —— 收斂。", claim: {"k":"ratio","v":0.333332} },
    "rel-basic-001": { text: "直接代入會得到 0/0，不能硬代 —— 要先化簡、有理化，或用 L'Hôpital 與泰勒展開。", claim: {"k":"limitForm","v":"0/0"} },
    "rel-basic-003": { text: "直接代入會得到 0/0，不能硬代 —— 要先化簡、有理化，或用 L'Hôpital 與泰勒展開。", claim: {"k":"limitForm","v":"0/0"} },
    "rel-basic-004": { text: "直接代入會得到 0/0，不能硬代 —— 要先化簡、有理化，或用 L'Hôpital 與泰勒展開。", claim: {"k":"limitForm","v":"0/0"} },
    "rel-basic-005": { text: "直接代入會得到 0/0，不能硬代 —— 要先化簡、有理化，或用 L'Hôpital 與泰勒展開。", claim: {"k":"limitForm","v":"0/0"} },
    "rel-basic-018": { text: "把 x 換成 2−x 之後兩式相加：f(x)+f(2−x) 恆等於 6，所以 2I = 6×(區間長度)。", claim: {"k":"kings","v":6} },
    "rel-basic-019": { text: "比值判別：|aₙ₊₁/aₙ| 在 n=20…120 之間一路落在 0.5 以下（最後約 0.5），明顯小於 1 —— 收斂。", claim: {"k":"ratio","v":0.5} },
    "rel-basic-024": { text: "比值判別：|aₙ₊₁/aₙ| 在 n=20…120 之間一路落在 0.333 以下（最後約 0.333333），明顯小於 1 —— 收斂。", claim: {"k":"ratio","v":0.333333} },
    "rel-boss-001": { text: "區間是 [0,∞) 而被積函數是代數型（沒有指數在壓）—— 它收斂靠的是分母長得比分子快。這種積分用分部積分做不出來，要往 Beta/Gamma、留數或參數微分想。", claim: {"k":"algImproper","v":1} },
    "rel-boss-003": { text: "區間是 [0,∞) 而被積函數是代數型（沒有指數在壓）—— 它收斂靠的是分母長得比分子快。這種積分用分部積分做不出來，要往 Beta/Gamma、留數或參數微分想。", claim: {"k":"algImproper","v":1} },
    "rel-hard-int-009": { text: "區間是 [0,∞) 而被積函數是代數型（沒有指數在壓）—— 它收斂靠的是分母長得比分子快。這種積分用分部積分做不出來，要往 Beta/Gamma、留數或參數微分想。", claim: {"k":"algImproper","v":1} },
    "rel-hard-int-011": { text: "區間是 [0,∞) 而被積函數是代數型（沒有指數在壓）—— 它收斂靠的是分母長得比分子快。這種積分用分部積分做不出來，要往 Beta/Gamma、留數或參數微分想。", claim: {"k":"algImproper","v":1} },
    "rel-hard-int-012": { text: "區間是 [0,∞) 而被積函數是代數型（沒有指數在壓）—— 它收斂靠的是分母長得比分子快。這種積分用分部積分做不出來，要往 Beta/Gamma、留數或參數微分想。", claim: {"k":"algImproper","v":1} },
    "rel-hard-int-018": { text: "區間是 [0,∞) 而被積函數是代數型（沒有指數在壓）—— 它收斂靠的是分母長得比分子快。這種積分用分部積分做不出來，要往 Beta/Gamma、留數或參數微分想。", claim: {"k":"algImproper","v":1} },
    "rel-hard-lim-001": { text: "直接代入會得到 0/0，不能硬代 —— 要先化簡、有理化，或用 L'Hôpital 與泰勒展開。", claim: {"k":"limitForm","v":"0/0"} },
    "rel-hard-lim-002": { text: "直接代入會得到 0/0，不能硬代 —— 要先化簡、有理化，或用 L'Hôpital 與泰勒展開。", claim: {"k":"limitForm","v":"0/0"} },
    "rel-hard-lim-003": { text: "直接代入會得到 0/0，不能硬代 —— 要先化簡、有理化，或用 L'Hôpital 與泰勒展開。", claim: {"k":"limitForm","v":"0/0"} },
    "rel-hard-lim-004": { text: "直接代入會得到 0/0，不能硬代 —— 要先化簡、有理化，或用 L'Hôpital 與泰勒展開。", claim: {"k":"limitForm","v":"0/0"} },
    "rel-hard-lim-009": { text: "直接代入會得到 0/0，不能硬代 —— 要先化簡、有理化，或用 L'Hôpital 與泰勒展開。", claim: {"k":"limitForm","v":"0/0"} },
    "rel-hard-ser-010": { text: "比值判別：|aₙ₊₁/aₙ| 在 n=20…120 之間一路在 2.65 以上（最後約 2.70704），明顯大於 1 —— 發散。", claim: {"k":"ratio","v":2.70704} },
    "ser-003": { text: "比值判別：|aₙ₊₁/aₙ| 在 n=20…120 之間一路落在 0.333 以下（最後約 0.333333），明顯小於 1 —— 收斂。", claim: {"k":"ratio","v":0.333333} },
    "ser-006": { text: "比值判別：|aₙ₊₁/aₙ| 在 n=20…120 之間一路落在 0.377 以下（最後約 0.369407），明顯小於 1 —— 收斂。", claim: {"k":"ratio","v":0.369407} },
    "ser-007": { text: "比值判別：|aₙ₊₁/aₙ| 在 n=20…120 之間一路落在 0.143 以下（最後約 0.0247934），明顯小於 1 —— 收斂。", claim: {"k":"ratio","v":0.0247934} },
    "ser-011": { text: "比值判別：|aₙ₊₁/aₙ| 在 n=20…120 之間一路落在 0.667 以下（最後約 0.666667），明顯小於 1 —— 收斂。", claim: {"k":"ratio","v":0.666667} },
    "ser-014": { text: "比值判別：|aₙ₊₁/aₙ| 在 n=20…120 之間一路落在 0.525 以下（最後約 0.504167），明顯小於 1 —— 收斂。", claim: {"k":"ratio","v":0.504167} },
    "ser-015": { text: "比值判別：|aₙ₊₁/aₙ| 在 n=20…120 之間一路落在 0.551 以下（最後約 0.508368），明顯小於 1 —— 收斂。", claim: {"k":"ratio","v":0.508368} },
    "ser-016": { text: "比值判別：|aₙ₊₁/aₙ| 在 n=20…80 之間一路落在 0.256 以下（最後約 0.251553），明顯小於 1 —— 收斂。", claim: {"k":"ratio","v":0.251553} },
    "td-der-001": { text: "最外層是一個函數套著另一個函數，用鏈鎖律：先微外層、再乘內層的導數。", claim: {"k":"outer","v":"chain"} },
    "td-der-002": { text: "最外層是兩個函數相乘，用乘積律 (uv)' = u'v + uv'。", claim: {"k":"outer","v":"product"} },
    "td-der-003": { text: "最外層是兩個函數相乘，用乘積律 (uv)' = u'v + uv'。", claim: {"k":"outer","v":"product"} },
    "td-der-004": { text: "最外層是一個函數套著另一個函數，用鏈鎖律：先微外層、再乘內層的導數。", claim: {"k":"outer","v":"chain"} },
    "td-int-001": { text: "區間是 [0,∞) 而被積函數是代數型（沒有指數在壓）—— 它收斂靠的是分母長得比分子快。這種積分用分部積分做不出來，要往 Beta/Gamma、留數或參數微分想。", claim: {"k":"algImproper","v":1} },
    "td-int-004": { text: "區間是 [0,∞) 而被積函數是代數型（沒有指數在壓）—— 它收斂靠的是分母長得比分子快。這種積分用分部積分做不出來，要往 Beta/Gamma、留數或參數微分想。", claim: {"k":"algImproper","v":1} },
    "td-lim-004": { text: "直接代入會得到 0/0，不能硬代 —— 要先化簡、有理化，或用 L'Hôpital 與泰勒展開。", claim: {"k":"limitForm","v":"0/0"} },
    "tmpl-der-simple-power-001": { text: "最外層是兩個函數相乘，用乘積律 (uv)' = u'v + uv'。", claim: {"k":"outer","v":"product"} },
    "tmpl-der-simple-power-002": { text: "最外層是兩個函數相乘，用乘積律 (uv)' = u'v + uv'。", claim: {"k":"outer","v":"product"} },
    "tmpl-der-simple-power-003": { text: "最外層是兩個函數相乘，用乘積律 (uv)' = u'v + uv'。", claim: {"k":"outer","v":"product"} },
    "tmpl-der-simple-power-004": { text: "最外層是兩個函數相乘，用乘積律 (uv)' = u'v + uv'。", claim: {"k":"outer","v":"product"} },
    "tmpl-der-simple-power-005": { text: "最外層是兩個函數相乘，用乘積律 (uv)' = u'v + uv'。", claim: {"k":"outer","v":"product"} },
    "tmpl-der-simple-power-006": { text: "最外層是兩個函數相乘，用乘積律 (uv)' = u'v + uv'。", claim: {"k":"outer","v":"product"} },
    "world-001": { text: "直接代入會得到 0/0，不能硬代 —— 要先化簡、有理化，或用 L'Hôpital 與泰勒展開。", claim: {"k":"limitForm","v":"0/0"} },
    "world-002": { text: "直接代入會得到 0/0，不能硬代 —— 要先化簡、有理化，或用 L'Hôpital 與泰勒展開。", claim: {"k":"limitForm","v":"0/0"} },
    "world-004": { text: "最外層是一個函數套著另一個函數，用鏈鎖律：先微外層、再乘內層的導數。", claim: {"k":"outer","v":"chain"} },
    "world-007": { text: "直接代入會得到 0/0，不能硬代 —— 要先化簡、有理化，或用 L'Hôpital 與泰勒展開。", claim: {"k":"limitForm","v":"0/0"} },
    "world-008": { text: "直接代入會得到 0/0，不能硬代 —— 要先化簡、有理化，或用 L'Hôpital 與泰勒展開。", claim: {"k":"limitForm","v":"0/0"} },
    "world-009": { text: "比值判別：|aₙ₊₁/aₙ| 在 n=20…120 之間一路落在 0.331 以下（最後約 0.330579），明顯小於 1 —— 收斂。", claim: {"k":"ratio","v":0.330579} },
    "world-014": { text: "把 x 換成 0.78539816−x 之後兩式相加：f(x)+f(0.78539816−x) 恆等於 0.69314718，所以 2I = 0.69314718×(區間長度)。", claim: {"k":"kings","v":0.6931471806} },
    "world-016": { text: "區間是 [0,∞) 而被積函數是代數型（沒有指數在壓）—— 它收斂靠的是分母長得比分子快。這種積分用分部積分做不出來，要往 Beta/Gamma、留數或參數微分想。", claim: {"k":"algImproper","v":1} },
    "world-017": { text: "區間是 [0,∞) 而被積函數是代數型（沒有指數在壓）—— 它收斂靠的是分母長得比分子快。這種積分用分部積分做不出來，要往 Beta/Gamma、留數或參數微分想。", claim: {"k":"algImproper","v":1} },
    "world-020": { text: "比值判別：|aₙ₊₁/aₙ| 在 n=20…120 之間一路落在 0.0525 以下（最後約 0.00840278），明顯小於 1 —— 收斂。", claim: {"k":"ratio","v":0.00840278} },
    "world-021": { text: "比值判別：|aₙ₊₁/aₙ| 在 n=20…120 之間一路落在 0.0551 以下（最後約 0.0084728），明顯小於 1 —— 收斂。", claim: {"k":"ratio","v":0.0084728} },
    "world-026": { text: "直接代入會得到 0/0，不能硬代 —— 要先化簡、有理化，或用 L'Hôpital 與泰勒展開。", claim: {"k":"limitForm","v":"0/0"} },
    "world-029": { text: "區間是 [0,∞) 而被積函數是代數型（沒有指數在壓）—— 它收斂靠的是分母長得比分子快。這種積分用分部積分做不出來，要往 Beta/Gamma、留數或參數微分想。", claim: {"k":"algImproper","v":1} },
    "world-031": { text: "區間是 [0,∞) 而被積函數是代數型（沒有指數在壓）—— 它收斂靠的是分母長得比分子快。這種積分用分部積分做不出來，要往 Beta/Gamma、留數或參數微分想。", claim: {"k":"algImproper","v":1} },
    "world-033": { text: "區間是 [0,∞) 而被積函數是代數型（沒有指數在壓）—— 它收斂靠的是分母長得比分子快。這種積分用分部積分做不出來，要往 Beta/Gamma、留數或參數微分想。", claim: {"k":"algImproper","v":1} },
    "world-038": { text: "區間是 [0,∞) 而被積函數是代數型（沒有指數在壓）—— 它收斂靠的是分母長得比分子快。這種積分用分部積分做不出來，要往 Beta/Gamma、留數或參數微分想。", claim: {"k":"algImproper","v":1} },
    "world-039": { text: "比值判別：|aₙ₊₁/aₙ| 在 n=20…120 之間一路落在 0.247 以下（最後約 0.246905），明顯小於 1 —— 收斂。", claim: {"k":"ratio","v":0.246905} },
    "world-040": { text: "直接代入會得到 0/0，不能硬代 —— 要先化簡、有理化，或用 L'Hôpital 與泰勒展開。", claim: {"k":"limitForm","v":"0/0"} },
    "world-043": { text: "區間是 [0,∞) 而被積函數是代數型（沒有指數在壓）—— 它收斂靠的是分母長得比分子快。這種積分用分部積分做不出來，要往 Beta/Gamma、留數或參數微分想。", claim: {"k":"algImproper","v":1} },
    "world-045": { text: "區間是 [0,∞) 而被積函數是代數型（沒有指數在壓）—— 它收斂靠的是分母長得比分子快。這種積分用分部積分做不出來，要往 Beta/Gamma、留數或參數微分想。", claim: {"k":"algImproper","v":1} },
    "world-047": { text: "區間是 [0,∞) 而被積函數是代數型（沒有指數在壓）—— 它收斂靠的是分母長得比分子快。這種積分用分部積分做不出來，要往 Beta/Gamma、留數或參數微分想。", claim: {"k":"algImproper","v":1} },
    "world-057": { text: "區間是 [0,∞) 而被積函數是代數型（沒有指數在壓）—— 它收斂靠的是分母長得比分子快。這種積分用分部積分做不出來，要往 Beta/Gamma、留數或參數微分想。", claim: {"k":"algImproper","v":1} },
    "world-063": { text: "區間是 [0,∞) 而被積函數是代數型（沒有指數在壓）—— 它收斂靠的是分母長得比分子快。這種積分用分部積分做不出來，要往 Beta/Gamma、留數或參數微分想。", claim: {"k":"algImproper","v":1} },
    "world-069": { text: "區間是 [0,∞) 而被積函數是代數型（沒有指數在壓）—— 它收斂靠的是分母長得比分子快。這種積分用分部積分做不出來，要往 Beta/Gamma、留數或參數微分想。", claim: {"k":"algImproper","v":1} },
    "world-076": { text: "區間是 [0,∞) 而被積函數是代數型（沒有指數在壓）—— 它收斂靠的是分母長得比分子快。這種積分用分部積分做不出來，要往 Beta/Gamma、留數或參數微分想。", claim: {"k":"algImproper","v":1} },
    "world-078": { text: "比值判別：|aₙ₊₁/aₙ| 在 n=20…120 之間一路落在 0.492 以下（最後約 0.49177），明顯小於 1 —— 收斂。", claim: {"k":"ratio","v":0.49177} },
    "world-080": { text: "區間是 [0,∞) 而被積函數是代數型（沒有指數在壓）—— 它收斂靠的是分母長得比分子快。這種積分用分部積分做不出來，要往 Beta/Gamma、留數或參數微分想。", claim: {"k":"algImproper","v":1} },
    "world-081": { text: "區間是 [0,∞) 而被積函數是代數型（沒有指數在壓）—— 它收斂靠的是分母長得比分子快。這種積分用分部積分做不出來，要往 Beta/Gamma、留數或參數微分想。", claim: {"k":"algImproper","v":1} },
    "world-083": { text: "區間是 [0,∞) 而被積函數是代數型（沒有指數在壓）—— 它收斂靠的是分母長得比分子快。這種積分用分部積分做不出來，要往 Beta/Gamma、留數或參數微分想。", claim: {"k":"algImproper","v":1} },
    "world-088": { text: "區間是 [0,∞) 而被積函數是代數型（沒有指數在壓）—— 它收斂靠的是分母長得比分子快。這種積分用分部積分做不出來，要往 Beta/Gamma、留數或參數微分想。", claim: {"k":"algImproper","v":1} },
    "world-089": { text: "區間是 [0,∞) 而被積函數是代數型（沒有指數在壓）—— 它收斂靠的是分母長得比分子快。這種積分用分部積分做不出來，要往 Beta/Gamma、留數或參數微分想。", claim: {"k":"algImproper","v":1} },
    "world-094": { text: "區間是 [0,∞) 而被積函數是代數型（沒有指數在壓）—— 它收斂靠的是分母長得比分子快。這種積分用分部積分做不出來，要往 Beta/Gamma、留數或參數微分想。", claim: {"k":"algImproper","v":1} },
    "world-096": { text: "這是 1^∞ 型。取對數變成 0·∞，再整理成分式。", claim: {"k":"limitForm","v":"1^inf"} },
    "world-098": { text: "區間是 [0,∞) 而被積函數是代數型（沒有指數在壓）—— 它收斂靠的是分母長得比分子快。這種積分用分部積分做不出來，要往 Beta/Gamma、留數或參數微分想。", claim: {"k":"algImproper","v":1} },
    "world-099": { text: "直接代入會得到 0/0，不能硬代 —— 要先化簡、有理化，或用 L'Hôpital 與泰勒展開。", claim: {"k":"limitForm","v":"0/0"} }
  };

  const API = {
    version: 1,
    table: DERIVED_HINTS,
    textFor: (id) => (DERIVED_HINTS[id] ? DERIVED_HINTS[id].text : ""),
    has: (id) => Boolean(DERIVED_HINTS[id])
  };

  if (typeof module !== "undefined" && module.exports) module.exports = DERIVED_HINTS;
  if (typeof window !== "undefined") {
    window.BUZZ_DERIVED_HINTS = DERIVED_HINTS;
    window.BuzzDerivedHints = API;
  }
})();
