// 自動產生 —— 不要手改。來源：tools/backfill_skill_tags.js
//
// 早期題目（problems.js 與幾個高速反射包）沒有技巧 tag，只有校準層加的
// rank-N。這張表補上它們的 skill 對應，讓能力模型不會漏掉 17% 的題庫。
//
// 為什麼不寫進 problem.tags：tags 會餵給題包抽題、主線關卡與既有 8 軸雷達，
// 動它等於改變抽題結果。這張表只有 skill graph 讀。
//
// 重新產生：node tools/backfill_skill_tags.js

(function () {
  "use strict";

  const SKILL_TAGS = {
    "burst-boss2-anti-001": ["integral.ibp.cyclic", "integral.ibp"],
    "burst-boss2-anti-002": ["integral.ibp.cyclic", "integral.ibp"],
    "burst-boss2-anti-003": ["integral.ibp.cyclic", "integral.ibp"],
    "burst-boss2-anti-004": ["integral.ibp.cyclic", "integral.ibp"],
    "burst-boss2-anti-005": ["integral.ibp.cyclic", "integral.ibp"],
    "burst-boss2-anti-006": ["integral.usub"],
    "burst-boss2-der-001": ["diff.higher.extreme", "series.taylor.coeff"],
    "burst-boss2-der-002": ["diff.higher.extreme", "series.taylor.coeff"],
    "burst-boss2-der-003": ["diff.higher.extreme", "series.taylor.coeff"],
    "burst-boss2-der-004": ["diff.higher.extreme", "series.taylor.coeff"],
    "burst-boss2-der-005": ["diff.higher.extreme", "series.taylor.coeff"],
    "burst-boss2-der-006": ["diff.higher.extreme", "series.taylor.coeff"],
    "burst-boss2-der-007": ["diff.higher.extreme", "series.taylor.coeff"],
    "burst-boss2-der-008": ["diff.higher.extreme", "series.taylor.coeff"],
    "burst-boss2-int-001": ["integral.improper"],
    "burst-boss2-int-002": ["integral.improper"],
    "burst-boss2-int-003": ["integral.improper"],
    "burst-boss2-int-004": ["integral.improper"],
    "burst-boss2-int-005": ["integral.dirichlet", "integral.improper"],
    "burst-boss2-int-006": ["integral.dirichlet", "integral.improper"],
    "burst-boss2-int-007": ["integral.dirichlet", "integral.improper"],
    "burst-boss2-int-008": ["integral.log", "series.euler"],
    "burst-boss2-int-009": ["integral.log", "series.euler"],
    "burst-boss2-int-010": ["integral.log", "series.euler"],
    "burst-boss2-int-011": ["integral.log", "series.euler"],
    "burst-boss2-int-012": ["integral.wallis", "integral.trig"],
    "burst-boss2-int-013": ["integral.ibp"],
    "burst-boss2-int-014": ["integral.basic"],
    "burst-boss2-lim-001": ["limit.exponential", "limit.taylor"],
    "burst-boss2-lim-002": ["limit.taylor"],
    "burst-boss2-lim-003": ["limit.taylor"],
    "burst-boss2-lim-004": ["limit.taylor"],
    "burst-boss2-lim-005": ["limit.taylor", "integral.ftc"],
    "burst-boss2-lim-006": ["limit.taylor", "integral.ftc"],
    "burst-boss2-lim-007": ["limit.riemann", "limit.asymptotic"],
    "burst-boss2-lim-008": ["limit.riemann", "limit.asymptotic"],
    "burst-boss2-lim-009": ["limit.riemann", "limit.asymptotic"],
    "burst-boss2-lim-010": ["limit.direct"],
    "burst-boss2-param-001": ["integral.parameter", "integral.improper"],
    "burst-boss2-param-002": ["integral.parameter", "integral.improper"],
    "burst-boss2-param-003": ["integral.parameter", "integral.improper"],
    "burst-boss2-param-004": ["integral.parameter", "integral.improper"],
    "burst-boss2-param-005": ["integral.parameter", "integral.improper"],
    "burst-boss2-param-006": ["integral.parameter", "integral.improper"],
    "burst-boss2-ser-001": ["series.euler", "series.geometric"],
    "burst-boss2-ser-002": ["series.euler", "series.geometric"],
    "burst-boss2-ser-003": ["series.alternating"],
    "burst-boss2-ser-004": ["series.alternating"],
    "burst-boss2-ser-005": ["series.sum", "series.generating"],
    "burst-boss2-ser-006": ["series.sum", "series.generating"],
    "burst-boss2-ser-007": ["series.euler", "series.generating"],
    "burst-boss2-ser-008": ["series.euler", "series.generating"],
    "burst-boss3-anti-001": ["integral.ibp.cyclic", "integral.ibp"],
    "burst-boss3-anti-002": ["integral.ibp.cyclic", "integral.ibp"],
    "burst-boss3-anti-003": ["integral.ibp.cyclic", "integral.ibp"],
    "burst-boss3-anti-004": ["integral.ibp.cyclic", "integral.ibp"],
    "burst-boss3-anti-005": ["integral.ibp.cyclic", "integral.ibp"],
    "burst-boss3-anti-006": ["integral.usub"],
    "burst-boss3-der-001": ["diff.higher.extreme", "series.taylor.coeff"],
    "burst-boss3-der-002": ["diff.higher.extreme", "series.taylor.coeff"],
    "burst-boss3-der-003": ["diff.higher.extreme", "series.taylor.coeff"],
    "burst-boss3-der-004": ["diff.higher.extreme", "series.taylor.coeff"],
    "burst-boss3-der-005": ["diff.higher.extreme", "series.taylor.coeff"],
    "burst-boss3-der-006": ["diff.higher.extreme", "series.taylor.coeff"],
    "burst-boss3-der-007": ["diff.higher.extreme", "series.taylor.coeff"],
    "burst-boss3-der-008": ["diff.higher.extreme", "series.taylor.coeff"],
    "burst-boss3-int-001": ["integral.double"],
    "burst-boss3-int-002": ["integral.double"],
    "burst-boss3-int-003": ["integral.basic"],
    "burst-boss3-int-004": ["integral.basic"],
    "burst-boss3-int-005": ["integral.ibp"],
    "burst-boss3-int-006": ["integral.ibp.cyclic", "integral.ibp"],
    "burst-boss3-int-007": ["integral.ibp.cyclic", "integral.ibp"],
    "burst-boss3-int-008": ["integral.dirichlet", "integral.improper"],
    "burst-boss3-int-009": ["integral.dirichlet", "integral.improper"],
    "burst-boss3-int-010": ["integral.dirichlet", "integral.improper"],
    "burst-boss3-int-011": ["integral.dirichlet", "integral.improper"],
    "burst-boss3-int-012": ["integral.special", "integral.improper"],
    "burst-boss3-int-013": ["integral.special", "integral.improper"],
    "burst-boss3-lim-001": ["limit.asymptotic"],
    "burst-boss3-lim-002": ["limit.asymptotic"],
    "burst-boss3-lim-003": ["limit.direct"],
    "burst-boss3-lim-004": ["limit.riemann", "limit.asymptotic"],
    "burst-boss3-lim-005": ["limit.riemann", "limit.asymptotic"],
    "burst-boss3-lim-006": ["limit.riemann", "limit.asymptotic"],
    "burst-boss3-lim-007": ["limit.taylor", "integral.ftc"],
    "burst-boss3-lim-008": ["limit.taylor", "integral.ftc"],
    "burst-boss3-lim-009": ["limit.taylor"],
    "burst-boss3-lim-010": ["limit.taylor"],
    "burst-boss3-lim-011": ["limit.taylor"],
    "burst-boss3-lim-012": ["limit.exponential", "limit.taylor"],
    "burst-boss3-param-001": ["integral.parameter", "integral.improper"],
    "burst-boss3-param-002": ["integral.parameter", "integral.improper"],
    "burst-boss3-param-003": ["integral.parameter", "integral.improper"],
    "burst-boss3-param-004": ["integral.parameter", "integral.improper"],
    "burst-boss3-param-005": ["integral.parameter", "integral.improper"],
    "burst-boss3-param-006": ["integral.parameter", "integral.improper"],
    "burst-boss3-ser-001": ["series.sum", "series.generating"],
    "burst-boss3-ser-002": ["series.sum", "series.generating"],
    "burst-boss3-ser-003": ["series.sum", "series.generating"],
    "burst-boss3-ser-004": ["series.sum", "series.generating"],
    "burst-boss3-ser-005": ["series.euler", "series.generating"],
    "burst-boss3-ser-006": ["series.taylor.coeff"],
    "burst-boss3-ser-007": ["series.taylor.coeff"],
    "burst-boss3-ser-008": ["series.taylor.coeff"],
    "cx-der-002": ["diff.basic"],
    "cx-der-006": ["diff.basic"],
    "cx-exam-004": ["diff.log"],
    "cx-exam-005": ["integral.basic"],
    "cx-int-001": ["integral.basic"],
    "cx-int-003": ["integral.basic"],
    "cx-int-004": ["integral.trigsub"],
    "cx-int-006": ["integral.basic"],
    "dd-inv-005": ["diff.basic"],
    "dd-inv-007": ["diff.basic"],
    "depth-int-011": ["integral.partialfrac"],
    "depth-int-015": ["integral.partialfrac"],
    "der-001": ["diff.basic"],
    "der-002": ["diff.basic"],
    "der-003": ["diff.basic"],
    "der-004": ["diff.basic"],
    "der-005": ["diff.chain"],
    "der-006": ["diff.basic"],
    "der-007": ["diff.inverse"],
    "der-008": ["diff.basic"],
    "der-009": ["diff.log"],
    "der-010": ["diff.chain"],
    "der-011": ["diff.chain"],
    "der-012": ["diff.basic"],
    "der-013": ["diff.log"],
    "der-014": ["diff.inverse"],
    "der-015": ["diff.chain"],
    "der-016": ["diff.basic"],
    "der-017": ["diff.chain"],
    "der-018": ["diff.chain"],
    "der-019": ["diff.chain"],
    "der-020": ["diff.inverse"],
    "exam-der-006": ["diff.chain"],
    "exam-der-018": ["diff.chain"],
    "exam-int-002": ["integral.usub"],
    "exam-int-014": ["integral.partialfrac"],
    "exam-int-030": ["integral.basic"],
    "exam-lim-008": ["limit.direct"],
    "fd-der-008": ["diff.basic"],
    "hc-rad-002": ["integral.trigsub"],
    "hc-rad-006": ["integral.trigsub"],
    "int-001": ["integral.basic"],
    "int-002": ["integral.basic"],
    "int-003": ["integral.basic"],
    "int-004": ["integral.basic"],
    "int-005": ["integral.usub"],
    "int-006": ["integral.usub"],
    "int-007": ["integral.usub"],
    "int-008": ["integral.basic"],
    "int-009": ["integral.ibp"],
    "int-010": ["integral.wallis", "integral.trig"],
    "int-011": ["integral.trigsub"],
    "int-012": ["integral.wallis", "integral.trig"],
    "int-013": ["integral.ibp"],
    "int-014": ["integral.partialfrac"],
    "int-015": ["integral.ibp"],
    "int-016": ["integral.ibp"],
    "int-017": ["integral.ibp"],
    "int-018": ["integral.usub"],
    "int-019": ["integral.basic"],
    "int-020": ["integral.usub"],
    "int-039": ["integral.trigsub"],
    "lim-001": ["limit.trig"],
    "lim-002": ["limit.trig"],
    "lim-003": ["limit.direct"],
    "lim-004": ["limit.direct"],
    "lim-005": ["limit.exponential"],
    "lim-006": ["limit.exponential"],
    "lim-007": ["limit.trig"],
    "lim-008": ["limit.rationalize"],
    "lim-009": ["limit.taylor"],
    "lim-010": ["limit.exponential"],
    "lim-011": ["limit.exponential"],
    "lim-012": ["limit.taylor"],
    "lim-013": ["limit.taylor"],
    "lim-014": ["limit.exponential"],
    "lim-015": ["limit.trig"],
    "lim-016": ["limit.rationalize"],
    "lim-017": ["limit.taylor"],
    "lim-018": ["limit.taylor"],
    "lim-019": ["limit.exponential", "limit.taylor"],
    "lim-020": ["limit.taylor"],
    "mob-tech-001": ["limit.rationalize"],
    "mob-tech-002": ["limit.exponential"],
    "mob-tech-003": ["integral.usub"],
    "mob-tech-004": ["integral.ibp"],
    "mob-tech-005": ["integral.partialfrac"],
    "mob-tech-006": ["integral.trigsub"],
    "mob-tech-007": ["series.ratio"],
    "mob-tech-008": ["series.compare"],
    "mob-tech-009": ["mvcalc.partial"],
    "mob-tech-010": ["integral.kings"],
    "mob-tech-011": ["integral.frullani", "integral.improper"],
    "mob-tech-012": ["mvcalc.lagrange"],
    "mob-tech-013": ["integral.basic"],
    "mob-tech-014": ["mvcalc.nabla"],
    "mob-tech-015": ["integral.beta"],
    "mob-tech-016": ["integral.gamma"],
    "mob-tech-017": ["integral.wallis", "integral.trig"],
    "mob-tech-018": ["adv.bessel"],
    "mob-tech-019": ["series.power.radius"],
    "mob-tech-020": ["diff.log"],
    "mob-trap-001": ["diff.basic"],
    "mob-trap-002": ["integral.basic"],
    "mob-trap-003": ["integral.trigsub"],
    "mob-trap-004": ["series.alternating"],
    "mob-trap-005": ["series.power.radius"],
    "mob-trap-006": ["integral.improper"],
    "mob-trap-007": ["mvcalc.partial"],
    "mob-trap-008": ["integral.double"],
    "mob-trap-009": ["limit.direct"],
    "mob-trap-010": ["integral.basic"],
    "mob-trap-011": ["mvcalc.nabla"],
    "mob-trap-012": ["integral.beta"],
    "putnam-002": ["series.telescoping"],
    "putnam-004": ["integral.kings"],
    "putnam-009": ["integral.partialfrac"],
    "rel-basic-007": ["diff.basic"],
    "rel-basic-008": ["diff.basic"],
    "rel-basic-010": ["diff.basic"],
    "rel-basic-011": ["diff.basic"],
    "ser-001": ["series.euler", "series.geometric"],
    "ser-002": ["series.geometric"],
    "ser-003": ["series.geometric"],
    "ser-004": ["series.alternating"],
    "ser-005": ["series.compare"],
    "ser-006": ["series.ratio"],
    "ser-007": ["series.ratio"],
    "ser-008": ["series.power.radius"],
    "ser-009": ["series.power.radius"],
    "ser-010": ["series.alternating"],
    "ser-011": ["series.compare"],
    "ser-012": ["series.telescoping"],
    "ser-013": ["series.alternating"],
    "ser-014": ["series.sum", "series.generating"],
    "ser-015": ["series.sum", "series.generating"],
    "ser-016": ["series.ratio"],
    "ser-017": ["series.power.radius"],
    "ser-018": ["series.alternating"],
    "ser-019": ["series.telescoping"],
    "ser-020": ["series.compare"],
    "td-der-001": ["diff.higher"],
    "td-der-002": ["diff.basic"],
    "td-der-003": ["diff.chain"],
    "td-der-004": ["diff.chain"],
    "td-int-001": ["integral.dirichlet", "integral.improper"],
    "td-int-002": ["integral.basic"],
    "td-int-003": ["integral.frullani", "integral.improper"],
    "td-int-004": ["integral.dirichlet", "integral.improper"],
    "td-int-005": ["integral.basic"],
    "td-int-006": ["integral.special", "integral.improper"],
    "td-lim-001": ["limit.exponential", "limit.riemann"],
    "td-lim-002": ["limit.exponential", "limit.riemann"],
    "td-lim-004": ["limit.taylor"],
    "td-ser-001": ["series.taylor.coeff"],
    "td-ser-002": ["series.taylor.coeff"],
    "td-ser-003": ["series.euler"],
    "tmpl-int-exp-def-001": ["integral.basic"],
    "tmpl-int-exp-def-002": ["integral.basic"],
    "tmpl-int-exp-def-003": ["integral.basic"],
    "tmpl-int-exp-def-004": ["integral.basic"],
    "tmpl-int-exp-def-005": ["integral.basic"],
    "tmpl-int-sin-def-001": ["integral.basic"],
    "tmpl-int-sin-def-002": ["integral.basic"],
    "tmpl-int-sin-def-003": ["integral.basic"],
    "tmpl-int-sin-def-004": ["integral.basic"],
    "uni-int-013": ["integral.usub"],
    "uni-int-020": ["integral.partialfrac"]
  };

  if (typeof module !== "undefined" && module.exports) module.exports = SKILL_TAGS;
  if (typeof window !== "undefined") window.BUZZ_SKILL_TAGS = SKILL_TAGS;
})();
