// 技巧 / 出處 tag 的顯示名。
//
// 從 app.js 搬出來的側表（2026-09-13）：tag key 是抽題與既有資料的鍵，不能動；
// 畫面上要講人話 —— 初學者看到「Basic Derivative」不會知道那是「基本微分」。
// 沒列在這裡的 tag 由 app.js 的 tagLabel() 退回 Title Case。
// app.js 用 feature-detect 接（window.BuzzTagLabels），檔案缺席時退回空表。

(function () {
  "use strict";

  const TAG_LABELS = {
    // 出處型 tag 的顯示名：tag key 保留（抽題與既有資料靠它），
    // 但畫面上一律講 Buzz 自己的難度語言，不掛學校名。
    "todai-burst": "高速反射",
    "world-universities": "國際難題",
    damo: "長題挑戰",
    putnam: "競賽經典",
    competition: "競賽難題",
    "true-boss": "終極挑戰",
    "multi-ibp": "multi-IBP",
    "trig-power": "Trig power",
    "recurrence-formula": "Recurrence",
    // 技巧型 tag 的中文名：這些會出現在回饋卡的「該用什麼技巧」與題庫標籤上，
    // 初學者看到 Basic Derivative 不會知道那是「基本微分」。
    "log": "對數",
    "trig": "三角",
    "exponential": "指數",
    "definite-integral": "定積分",
    "inverse-trig": "反三角",
    "radical": "根式",
    "special-functions": "特殊函數",
    "higher-derivative": "高階導數",
    "hardcore": "硬題",
    "basic-integral": "基本積分",
    "ivp": "初值問題",
    "ode": "微分方程",
    "curve-sketching": "曲線描繪",
    "long-form": "長題",
    "geometric-series": "等比級數",
    "first-derivative": "一階導數",
    "rational": "有理式",
    "log-differentiation": "對數微分",
    "quotient-rule": "商法則",
    "power-rule": "冪法則",
    "standard-limit": "標準極限",
    "parameter-integral": "含參積分",
    "u-sub": "換元",
    "separable": "分離變數",
    "product-rule": "乘法規則",
    "hyperbolic": "雙曲函數",
    "area": "面積",
    "residue": "留數",
    "second-order": "二階",
    "sum-series": "級數求和",
    "trig-integral": "三角積分",
    "second-derivative": "二階導數",
    "critical-points": "臨界點",
    "alternating": "交錯級數",
    "exponential-limit": "指數極限",
    "applications": "應用",
    "polar-coordinates": "極座標",
    "polynomial": "多項式",
    "asymptotics": "漸近",
    "rational-limit": "有理式極限",
    "rational-function": "有理函數",
    "parametric-differentiation": "參數微分",
    "factoring": "因式分解",
    "domain": "定義域",
    "extrema": "極值",
    "one-sided": "單邊極限",
    "linear-first-order": "一階線性",
    "taylor-limit": "Taylor 求極限",
    "symmetry": "對稱",
    "basic-derivative": "基本微分",
    "direct-substitution": "直接代入",
    "even-function": "偶函數",
    "oscillation": "震盪",
    "dne": "極限不存在",
    "linearization": "線性近似",
    "estimate": "估計",
    "integrating-factor": "積分因子",
    "inverse-function": "反函數",
    "log-integral": "對數積分",
    "monotonicity": "單調性",
    "floor": "高斯函數",
    "rational-integral": "有理式積分",
    "exponential-growth": "指數成長",
    "log-limit": "對數極限",
    "derivative-zero": "導數為零",
    "partial-fractions": "部分分式",
    "fundamental-theorem": "微積分基本定理",
    "derivative-definition": "導數定義",
    "series-test": "級數判別",
    "series-expansion": "級數展開",
    "differentiability": "可微性",
    "partial-derivative": "偏導數",
    "quadratic": "二次式",
    "volume": "體積",
    "harmonic": "調和級數",
    "nth-root": "n 次根",
    "super-high-derivative": "High derivative",
    "special-function": "Special function",
    "series-integral": "Series integral",
    "beginner-friendly": "新手友善",
    "boss-rank": "Boss",
    "boss-plus": "Boss+",
    custom: "自訂",
    "hard-limit": "硬極限",
    "asymptotic-expansion": "漸近展開",
    "generating-function": "生成函數",
    "harmonic-number": "調和數",
    "laplace-transform": "Laplace",
    "exam-style": "大考題感",
    "exam-depth": "大考深水",
    "depth-r5": "R5 深水",
    "depth-r6": "R6 深水",
    "transfer-exam": "轉學考",
    "proficiency-exam": "免修考",
    "technique-recognition": "技巧辨識",
    "technique-sprint": "速判",
    "trap-drill": "陷阱",
    "limit-trap": "極限陷阱",
    taylor: "Taylor",
    coefficient: "係數",
    rationalize: "有理化",
    "trig-limit": "三角極限",
    "chain-rule": "鏈鎖律",
    substitution: "U-sub",
    "integration-by-parts": "IBP",
    ibp: "IBP",
    "trig-substitution": "三角代換",
    "partial-fraction": "Partial Fraction",
    "ode-style": "ODE 型",
    "kings-property": "King's",
    frullani: "Frullani",
    "improper-integral": "廣義積分",
    "double-integral": "二重積分",
    "triple-integral": "三重積分",
    "change-of-variables": "變數變換",
    multivariable: "多變數",
    hessian: "Hessian",
    wronskian: "Wronskian",
    jacobian: "Jacobian",
    "jacobian-chain": "Jacobian 鏈鎖",
    "lagrange-multiplier": "LM",
    nabla: "Nabla",
    "vector-calculus": "向量分析",
    "total-differential": "全微分",
    "total-differential-min": "全微分最小",
    complex: "複變",
    "ode-intro": "ODE 入門",
    "power-series": "冪級數",
    radius: "收斂半徑",
    "ratio-test": "Ratio",
    "root-test": "Root",
    "integral-test": "Integral Test",
    "p-series": "p-series",
    "alternating-series": "交錯級數",
    comparison: "比較判別",
    "limit-comparison": "極限比較",
    "endpoint-analysis": "端點分析",
    "convergence-test": "審斂",
    "beta-function": "Beta",
    "gamma-function": "Gamma",
    wallis: "Wallis",
    bessel: "Bessel",
    parametric: "參數式",
    "polar-curve": "極座標",
    "related-rates": "相關變率",
    "tangent-normal": "切線法線",
    "linear-approximation": "線性近似",
    "newton-method": "Newton",
    curvature: "曲率",
    "nested-taylor": "巢狀 Taylor",
    "composite-taylor": "複合 Taylor",
    "asymptotic-balance": "漸近配平",
    "power-exponential": "變冪函數",
    "moving-limits": "變動上下限",
    laplacian: "Laplacian",
    region: "積分區域",
    "special-sum": "特殊級數",
    "line-integral": "線積分",
    "green-theorem": "Green 定理",
    "stokes-theorem": "Stokes 定理",
    "divergence-theorem": "散度定理",
    "surface-integral": "面積分",
    flux: "通量",
    "conservative-field": "保守場",
    "vector-identity": "向量恆等式",
    "directional-derivative": "方向導數",
    lhopital: "L'Hôpital",
    mvt: "均值定理",
    rolle: "Rolle",
    continuity: "連續性",
    ivt: "IVT 勘根",
    concavity: "凹凸性",
    inflection: "反曲點",
    asymptote: "漸近線",
    "implicit-differentiation": "隱微分",
    optimization: "最佳化",
    "arc-length": "弧長",
    "solid-of-revolution": "旋轉體",
    "surface-area": "曲面面積",
    "average-value": "平均值",
    "riemann-sum": "Riemann 和",
    ftc: "FTC",
    sequence: "數列",
    recursive: "遞迴數列",
    squeeze: "夾擠",
    telescoping: "望遠鏡和",
    "story-problem": "情境題",
    kinematics: "運動學",
    "work-integral": "功",
    "newton-cooling": "冷卻定律",
    "half-life": "半衰期",
    mixing: "混合問題",
    marginal: "邊際分析",
    centroid: "形心",
    "graph-reading": "讀圖",
    power: "功率"
  };

  if (typeof module !== "undefined" && module.exports) module.exports = TAG_LABELS;
  if (typeof window !== "undefined") window.BuzzTagLabels = TAG_LABELS;
})();
