// 技巧 / 出處 tag 的顯示名。
//
// 從 app.js 搬出來的側表（2026-09-13）：tag key 是抽題與既有資料的鍵，不能動；
// 畫面上要講人話 —— 初學者看到「Basic Derivative」不會知道那是「基本微分」。
// 沒列在這裡的 tag 由 app.js 的 tagLabel() 退回 Title Case。
// app.js 用 feature-detect 接（window.BuzzTagLabels），檔案缺席時退回空表。

(function () {
  "use strict";
  // 語言層：t() 由 src/kernel/i18n.js 掛在 globalThis；node 的驗證器直接 require 這一支時沒有它，
  // 就原樣印出（佔位符照填），所以每個模組都能單獨載入。
  const t = typeof globalThis.t === "function" ? globalThis.t : (text, vars) => (vars ? String(text).replace(/\{(\w+)(?:\|[^}]*)?\}/g, (m, k) => (k in vars ? String(vars[k]) : m)) : text);

  const TAG_LABELS = {
    // 出處型 tag 的顯示名：tag key 保留（抽題與既有資料靠它），
    // 但畫面上一律講 Buzz 自己的難度語言，不掛學校名。
    burst: t("高速反射"),
    "world-universities": t("國際難題"),
    longform: t("長題挑戰"),
    putnam: t("競賽經典"),
    competition: t("競賽難題"),
    "true-boss": t("終極挑戰"),
    "multi-ibp": "multi-IBP",
    "trig-power": "Trig power",
    "recurrence-formula": "Recurrence",
    // 技巧型 tag 的中文名：這些會出現在回饋卡的「該用什麼技巧」與題庫標籤上，
    // 初學者看到 Basic Derivative 不會知道那是「基本微分」。
    "log": t("對數"),
    "trig": t("三角"),
    "exponential": t("指數"),
    "definite-integral": t("定積分"),
    "inverse-trig": t("反三角"),
    "radical": t("根式"),
    "special-functions": t("特殊函數"),
    "higher-derivative": t("高階導數"),
    "hardcore": t("硬題"),
    "basic-integral": t("基本積分"),
    "ivp": t("初值問題"),
    "ode": t("微分方程"),
    "curve-sketching": t("曲線描繪"),
    "long-form": t("長題"),
    "geometric-series": t("等比級數"),
    "first-derivative": t("一階導數"),
    "rational": t("有理式"),
    "log-differentiation": t("對數微分"),
    "quotient-rule": t("商法則"),
    "power-rule": t("冪法則"),
    "standard-limit": t("標準極限"),
    "parameter-integral": t("含參積分"),
    "u-sub": t("換元"),
    "separable": t("分離變數"),
    "product-rule": t("乘法規則"),
    "hyperbolic": t("雙曲函數"),
    "area": t("面積"),
    "residue": t("留數"),
    "second-order": t("二階"),
    "sum-series": t("級數求和"),
    "trig-integral": t("三角積分"),
    "second-derivative": t("二階導數"),
    "critical-points": t("臨界點"),
    "alternating": t("交錯級數"),
    "exponential-limit": t("指數極限"),
    "applications": t("應用"),
    "polar-coordinates": t("極座標"),
    "polynomial": t("多項式"),
    "asymptotics": t("漸近"),
    "rational-limit": t("有理式極限"),
    "rational-function": t("有理函數"),
    "parametric-differentiation": t("參數微分"),
    "factoring": t("因式分解"),
    "domain": t("定義域"),
    "extrema": t("極值"),
    "one-sided": t("單邊極限"),
    "linear-first-order": t("一階線性"),
    "taylor-limit": t("Taylor 求極限"),
    "symmetry": t("對稱"),
    "basic-derivative": t("基本微分"),
    "direct-substitution": t("直接代入"),
    "even-function": t("偶函數"),
    "oscillation": t("震盪"),
    "dne": t("極限不存在"),
    "linearization": t("線性近似"),
    "estimate": t("估計"),
    "integrating-factor": t("積分因子"),
    "inverse-function": t("反函數"),
    "log-integral": t("對數積分"),
    "monotonicity": t("單調性"),
    "floor": t("高斯函數"),
    "rational-integral": t("有理式積分"),
    "exponential-growth": t("指數成長"),
    "log-limit": t("對數極限"),
    "derivative-zero": t("導數為零"),
    "partial-fractions": t("部分分式"),
    "fundamental-theorem": t("微積分基本定理"),
    "derivative-definition": t("導數定義"),
    "series-test": t("級數判別"),
    "series-expansion": t("級數展開"),
    "differentiability": t("可微性"),
    "partial-derivative": t("偏導數"),
    "quadratic": t("二次式"),
    "volume": t("體積"),
    "harmonic": t("調和級數"),
    "nth-root": t("n 次根"),
    "super-high-derivative": "High derivative",
    "special-function": "Special function",
    "series-integral": "Series integral",
    "beginner-friendly": t("新手友善"),
    "boss-rank": "Boss",
    "boss-plus": "Boss+",
    custom: t("自訂"),
    "hard-limit": t("硬極限"),
    "asymptotic-expansion": t("漸近展開"),
    "generating-function": t("生成函數"),
    "harmonic-number": t("調和數"),
    "laplace-transform": "Laplace",
    "exam-style": t("大考題感"),
    "exam-depth": t("大考深水"),
    "depth-r5": t("R5 深水"),
    "depth-r6": t("R6 深水"),
    "transfer-exam": t("轉學考"),
    "proficiency-exam": t("免修考"),
    "technique-recognition": t("技巧辨識"),
    "technique-sprint": t("速判"),
    "trap-drill": t("陷阱"),
    "limit-trap": t("極限陷阱"),
    taylor: "Taylor",
    coefficient: t("係數"),
    rationalize: t("有理化"),
    "trig-limit": t("三角極限"),
    "chain-rule": t("鏈鎖律"),
    substitution: "U-sub",
    "integration-by-parts": "IBP",
    ibp: "IBP",
    "trig-substitution": t("三角代換"),
    "partial-fraction": "Partial Fraction",
    "ode-style": t("ODE 型"),
    "kings-property": "King's",
    frullani: "Frullani",
    "improper-integral": t("廣義積分"),
    "double-integral": t("二重積分"),
    "triple-integral": t("三重積分"),
    "change-of-variables": t("變數變換"),
    multivariable: t("多變數"),
    hessian: "Hessian",
    wronskian: "Wronskian",
    jacobian: "Jacobian",
    "jacobian-chain": t("Jacobian 鏈鎖"),
    "lagrange-multiplier": "LM",
    nabla: "Nabla",
    "vector-calculus": t("向量分析"),
    "total-differential": t("全微分"),
    "total-differential-min": t("全微分最小"),
    complex: t("複變"),
    "ode-intro": t("ODE 入門"),
    "power-series": t("冪級數"),
    radius: t("收斂半徑"),
    "ratio-test": "Ratio",
    "root-test": "Root",
    "integral-test": "Integral Test",
    "p-series": "p-series",
    "alternating-series": t("交錯級數"),
    comparison: t("比較判別"),
    "limit-comparison": t("極限比較"),
    "endpoint-analysis": t("端點分析"),
    "convergence-test": t("審斂"),
    "beta-function": "Beta",
    "gamma-function": "Gamma",
    wallis: "Wallis",
    bessel: "Bessel",
    parametric: t("參數式"),
    "polar-curve": t("極座標"),
    "related-rates": t("相關變率"),
    "tangent-normal": t("切線法線"),
    "linear-approximation": t("線性近似"),
    "newton-method": "Newton",
    curvature: t("曲率"),
    "nested-taylor": t("巢狀 Taylor"),
    "composite-taylor": t("複合 Taylor"),
    "asymptotic-balance": t("漸近配平"),
    "power-exponential": t("變冪函數"),
    "moving-limits": t("變動上下限"),
    laplacian: "Laplacian",
    region: t("積分區域"),
    "special-sum": t("特殊級數"),
    "line-integral": t("線積分"),
    "green-theorem": t("Green 定理"),
    "stokes-theorem": t("Stokes 定理"),
    "divergence-theorem": t("散度定理"),
    "surface-integral": t("面積分"),
    flux: t("通量"),
    "conservative-field": t("保守場"),
    "vector-identity": t("向量恆等式"),
    "directional-derivative": t("方向導數"),
    lhopital: "L'Hôpital",
    mvt: t("均值定理"),
    rolle: "Rolle",
    continuity: t("連續性"),
    ivt: t("IVT 勘根"),
    concavity: t("凹凸性"),
    inflection: t("反曲點"),
    asymptote: t("漸近線"),
    "implicit-differentiation": t("隱微分"),
    optimization: t("最佳化"),
    "arc-length": t("弧長"),
    "solid-of-revolution": t("旋轉體"),
    "surface-area": t("曲面面積"),
    "average-value": t("平均值"),
    "riemann-sum": t("Riemann 和"),
    // 分析學入門包（2026-09）
    "analysis": t("分析學"),
    "supremum": t("上確界"),
    "infimum": t("下確界"),
    "limsup": t("上下極限"),
    "epsilon-delta": t("ε-δ 定義"),
    "uniform-continuity": t("一致連續"),
    "uniform-convergence": t("一致收斂"),
    "lipschitz": t("Lipschitz 條件"),
    "darboux": t("達布上下和"),
    "cauchy-sequence": t("Cauchy 數列"),
    "rearrangement": t("級數重排"),
    ftc: "FTC",
    sequence: t("數列"),
    recursive: t("遞迴數列"),
    squeeze: t("夾擠"),
    telescoping: t("望遠鏡和"),
    "story-problem": t("情境題"),
    kinematics: t("運動學"),
    "work-integral": t("功"),
    "newton-cooling": t("冷卻定律"),
    "half-life": t("半衰期"),
    mixing: t("混合問題"),
    marginal: t("邊際分析"),
    centroid: t("形心"),
    "graph-reading": t("讀圖"),
    power: t("功率")
  };

  if (typeof module !== "undefined" && module.exports) module.exports = TAG_LABELS;
  if (typeof window !== "undefined") window.BuzzTagLabels = TAG_LABELS;
})();
