(function () {
  "use strict";

  const gapProblems = [
    {
      id: "gap-int-pf-001",
      topic: "integrals",
      difficulty: 3,
      source: "Buzz gap pack",
      prompt: "\\int \\frac{1}{x^2-1}\\,dx",
      answerKind: "antiderivative",
      answer: "(log(x-1)-log(x+1))/2",
      timeLimit: 85,
      tabLimit: 1,
      tags: ["partial-fraction", "rational-integral"],
      hints: ["Factor x^2-1.", "Write 1/((x-1)(x+1)) as A/(x-1)+B/(x+1).", "Integrate logarithms."],
      solution: "Partial fractions give 1/(x^2-1)=1/2/(x-1)-1/2/(x+1)."
    },
    {
      id: "gap-int-pf-002",
      topic: "integrals",
      difficulty: 2,
      source: "Buzz gap pack",
      prompt: "\\int \\frac{x+1}{x^2+x}\\,dx",
      answerKind: "antiderivative",
      answer: "log(x)",
      timeLimit: 60,
      tabLimit: 1,
      tags: ["partial-fraction", "rational-integral", "cancellation"],
      hints: ["Factor the denominator.", "x^2+x=x(x+1).", "Cancel x+1."],
      solution: "The integrand reduces to 1/x, so the answer is log x."
    },
    {
      id: "gap-int-pf-003",
      topic: "integrals",
      difficulty: 3,
      source: "Buzz gap pack",
      prompt: "\\int \\frac{1}{x(x+2)}\\,dx",
      answerKind: "antiderivative",
      answer: "(log(x)-log(x+2))/2",
      timeLimit: 75,
      tabLimit: 1,
      tags: ["partial-fraction", "rational-integral"],
      hints: ["Use A/x+B/(x+2).", "A=1/2 and B=-1/2.", "Integrate each term."],
      solution: "1/(x(x+2))=(1/2)/x-(1/2)/(x+2)."
    },
    {
      id: "gap-int-pf-004",
      topic: "integrals",
      difficulty: 3,
      source: "Buzz gap pack",
      prompt: "\\int \\frac{2x+3}{x^2+3x+2}\\,dx",
      answerKind: "antiderivative",
      answer: "log(x+1)+log(x+2)",
      timeLimit: 75,
      tabLimit: 1,
      tags: ["partial-fraction", "rational-integral", "log"],
      hints: ["Factor x^2+3x+2.", "Notice the numerator is the derivative of the denominator.", "A single log appears."],
      solution: "The denominator derivative is 2x+3, so the integral is log(x^2+3x+2)."
    },
    {
      id: "gap-int-pf-005",
      topic: "integrals",
      difficulty: 3,
      source: "Buzz gap pack",
      prompt: "\\int \\frac{1}{(x+1)^2}\\,dx",
      answerKind: "antiderivative",
      answer: "-1/(x+1)",
      timeLimit: 55,
      tabLimit: 1,
      tags: ["partial-fraction", "repeated-factor"],
      hints: ["Rewrite as (x+1)^{-2}.", "Use the power rule.", "Do not write a logarithm for a repeated square factor."],
      solution: "The antiderivative of (x+1)^{-2} is -(x+1)^{-1}."
    },
    {
      id: "gap-int-pf-006",
      topic: "integrals",
      difficulty: 4,
      source: "Buzz gap pack",
      prompt: "\\int \\frac{3x+5}{x^2+x-2}\\,dx",
      answerKind: "antiderivative",
      answer: "8*log(x-1)/3+log(x+2)/3",
      timeLimit: 95,
      tabLimit: 1,
      tags: ["partial-fraction", "rational-integral"],
      hints: ["Factor x^2+x-2=(x-1)(x+2).", "Use A/(x-1)+B/(x+2).", "Solve A+B=3 and 2A-B=5."],
      solution: "A=8/3 and B=1/3, so integrate the two simple fractions."
    },
    {
      id: "gap-int-pf-007",
      topic: "integrals",
      difficulty: 4,
      source: "Buzz gap pack",
      prompt: "\\int \\frac{x+4}{x^2+5x+6}\\,dx",
      answerKind: "antiderivative",
      answer: "2*log(x+2)-log(x+3)",
      timeLimit: 90,
      tabLimit: 1,
      tags: ["partial-fraction", "rational-integral"],
      hints: ["Factor the denominator as (x+2)(x+3).", "Use A/(x+2)+B/(x+3).", "Solve A+B=1 and 3A+2B=4."],
      solution: "A=2 and B=-1, giving 2log(x+2)-log(x+3)."
    },
    {
      id: "gap-der-param-001",
      topic: "derivatives",
      difficulty: 2,
      source: "Buzz gap pack",
      prompt: "x=t^2,\\ y=t^3.\\ \\frac{dy}{dx}=?",
      answerKind: "expression",
      answer: "3*t/2",
      variable: "t",
      timeLimit: 65,
      tabLimit: 1,
      tags: ["parametric", "parametric-differentiation"],
      hints: ["dy/dx=(dy/dt)/(dx/dt).", "dy/dt=3t^2.", "dx/dt=2t."],
      solution: "dy/dx=3t^2/(2t)=3t/2."
    },
    {
      id: "gap-der-param-002",
      topic: "derivatives",
      difficulty: 3,
      source: "Buzz gap pack",
      prompt: "x=\\cos t,\\ y=\\sin t.\\ \\frac{dy}{dx}=?",
      answerKind: "expression",
      answer: "-cos(t)/sin(t)",
      variable: "t",
      timeLimit: 70,
      tabLimit: 1,
      tags: ["parametric", "parametric-differentiation", "trig"],
      hints: ["dy/dt=cos t.", "dx/dt=-sin t.", "Divide dy/dt by dx/dt."],
      solution: "dy/dx=cos t/(-sin t)=-cot t."
    },
    {
      id: "gap-der-param-003",
      topic: "derivatives",
      difficulty: 2,
      source: "Buzz gap pack",
      prompt: "x=t,\\ y=t^2.\\ \\frac{d^2y}{dx^2}=?",
      answerKind: "numeric",
      answer: "2",
      timeLimit: 60,
      tabLimit: 1,
      tags: ["parametric", "second-derivative"],
      hints: ["Since x=t, dy/dx=dy/dt.", "dy/dx=2t.", "Differentiate again with respect to x=t."],
      solution: "dy/dx=2t and d/dx=d/dt, so d^2y/dx^2=2."
    },
    {
      id: "gap-der-param-004",
      topic: "derivatives",
      difficulty: 2,
      source: "Buzz gap pack",
      prompt: "x=t^2+1,\\ y=t^3.\\ \\left.\\frac{dy}{dx}\\right|_{t=2}",
      answerKind: "numeric",
      answer: "3",
      timeLimit: 65,
      tabLimit: 1,
      tags: ["parametric", "parametric-differentiation"],
      hints: ["dy/dx=(3t^2)/(2t).", "Simplify to 3t/2.", "Evaluate at t=2."],
      solution: "dy/dx=3t/2, so at t=2 the slope is 3."
    },
    {
      id: "gap-der-polar-001",
      topic: "derivatives",
      difficulty: 4,
      source: "Buzz gap pack",
      prompt: "r=1+\\cos\\theta.\\ \\left.\\frac{dy}{dx}\\right|_{\\theta=\\pi/2}",
      answerKind: "numeric",
      answer: "1",
      timeLimit: 95,
      tabLimit: 1,
      tags: ["polar-curve", "parametric", "slope"],
      hints: ["Use x=r cos theta and y=r sin theta.", "dy/dx=(r' sin theta+r cos theta)/(r' cos theta-r sin theta).", "At pi/2, r=1 and r'=-1."],
      solution: "The numerator and denominator are both -1, so the slope is 1."
    },
    {
      id: "gap-int-polar-001",
      topic: "integrals",
      difficulty: 2,
      source: "Buzz gap pack",
      prompt: "\\text{Area enclosed by }r=2\\text{ from }0\\le\\theta\\le\\pi/2",
      answerKind: "numeric",
      answer: "pi",
      timeLimit: 60,
      tabLimit: 1,
      tags: ["polar-curve", "polar-area"],
      hints: ["Polar area is (1/2)int r^2 dtheta.", "Here r^2=4.", "The angle length is pi/2."],
      solution: "Area=(1/2)*4*(pi/2)=pi."
    },
    {
      id: "gap-int-polar-002",
      topic: "integrals",
      difficulty: 3,
      source: "Buzz gap pack",
      prompt: "\\text{Area enclosed by }r=\\sin\\theta\\text{ for }0\\le\\theta\\le\\pi",
      answerKind: "numeric",
      answer: "pi/4",
      timeLimit: 80,
      tabLimit: 1,
      tags: ["polar-curve", "polar-area", "trig"],
      hints: ["Use (1/2)int_0^pi sin^2 theta dtheta.", "int_0^pi sin^2 theta dtheta=pi/2.", "Multiply by 1/2."],
      solution: "The polar area is (1/2)(pi/2)=pi/4."
    },
    {
      id: "gap-der-param-005",
      topic: "derivatives",
      difficulty: 2,
      source: "Buzz gap pack",
      prompt: "x=3t,\\ y=4t.\\ \\text{Speed }\\sqrt{(dx/dt)^2+(dy/dt)^2}",
      answerKind: "numeric",
      answer: "5",
      timeLimit: 55,
      tabLimit: 1,
      tags: ["parametric", "speed"],
      hints: ["dx/dt=3.", "dy/dt=4.", "Use the 3-4-5 triangle."],
      solution: "The speed is sqrt(3^2+4^2)=5."
    },
    {
      id: "gap-der-app-001",
      topic: "derivatives",
      difficulty: 3,
      source: "Buzz gap pack",
      prompt: "\\text{A sphere has }r=3,\\ dr/dt=2.\\ \\frac{dV}{dt}=?",
      answerKind: "numeric",
      answer: "72*pi",
      timeLimit: 80,
      tabLimit: 1,
      tags: ["related-rates", "volume"],
      hints: ["V=(4/3)pi r^3.", "dV/dt=4pi r^2 dr/dt.", "Substitute r=3 and dr/dt=2."],
      solution: "dV/dt=4pi(9)(2)=72pi."
    },
    {
      id: "gap-der-app-002",
      topic: "derivatives",
      difficulty: 2,
      source: "Buzz gap pack",
      prompt: "\\text{A circle has }r=5,\\ dr/dt=0.2.\\ \\frac{dA}{dt}=?",
      answerKind: "numeric",
      answer: "2*pi",
      timeLimit: 70,
      tabLimit: 1,
      tags: ["related-rates", "area"],
      hints: ["A=pi r^2.", "dA/dt=2pi r dr/dt.", "Substitute r=5."],
      solution: "dA/dt=2pi(5)(0.2)=2pi."
    },
    {
      id: "gap-der-app-003",
      topic: "derivatives",
      difficulty: 3,
      source: "Buzz gap pack",
      prompt: "\\text{Ladder length }10,\\ x=6,\\ dx/dt=2.\\ dy/dt=?",
      answerKind: "numeric",
      answer: "-3/2",
      timeLimit: 85,
      tabLimit: 1,
      tags: ["related-rates", "implicit-differentiation"],
      hints: ["x^2+y^2=100.", "At x=6, y=8.", "2x dx/dt+2y dy/dt=0."],
      solution: "dy/dt=-(x/y)dx/dt=-(6/8)*2=-3/2."
    },
    {
      id: "gap-der-app-004",
      topic: "derivatives",
      difficulty: 2,
      source: "Buzz gap pack",
      prompt: "\\text{Normal slope to }y=x^2\\text{ at }x=2",
      answerKind: "numeric",
      answer: "-1/4",
      timeLimit: 60,
      tabLimit: 1,
      tags: ["tangent-normal", "derivative"],
      hints: ["The tangent slope is y'=2x.", "At x=2, tangent slope is 4.", "Normal slope is the negative reciprocal."],
      solution: "The normal slope is -1/4."
    },
    {
      id: "gap-der-app-005",
      topic: "derivatives",
      difficulty: 2,
      source: "Buzz gap pack",
      prompt: "\\text{Linear approximation of }\\sqrt{4.04}",
      answerKind: "numeric",
      answer: "2.01",
      timeLimit: 65,
      tabLimit: 1,
      tags: ["linear-approximation", "application"],
      hints: ["Use f(x)=sqrt x near x=4.", "f'(4)=1/4.", "dx=0.04."],
      solution: "sqrt(4.04)≈2+(1/4)(0.04)=2.01."
    },
    {
      id: "gap-der-app-006",
      topic: "derivatives",
      difficulty: 2,
      source: "Buzz gap pack",
      prompt: "\\text{One Newton step for }f(x)=x^2-2\\text{ from }x_0=1",
      answerKind: "numeric",
      answer: "3/2",
      timeLimit: 70,
      tabLimit: 1,
      tags: ["newton-method", "application"],
      hints: ["Newton: x1=x0-f(x0)/f'(x0).", "f(1)=-1.", "f'(1)=2."],
      solution: "x1=1-(-1)/2=3/2."
    },
    {
      id: "gap-der-app-007",
      topic: "derivatives",
      difficulty: 3,
      source: "Buzz gap pack",
      prompt: "\\text{Curvature of }y=x^2\\text{ at }x=0",
      answerKind: "numeric",
      answer: "2",
      timeLimit: 80,
      tabLimit: 1,
      tags: ["curvature", "application"],
      hints: ["Curvature is |y''|/(1+(y')^2)^{3/2}.", "y'=2x and y''=2.", "At x=0, the denominator is 1."],
      solution: "The curvature is 2."
    },
    {
      id: "gap-int-triple-001",
      topic: "integrals",
      difficulty: 2,
      source: "Buzz gap pack",
      prompt: "\\int_0^1\\int_0^1\\int_0^1 xyz\\,dz\\,dy\\,dx",
      answerKind: "numeric",
      answer: "1/8",
      timeLimit: 75,
      tabLimit: 1,
      tags: ["triple-integral", "iterated-integral"],
      hints: ["The variables separate.", "Each of int_0^1 x dx, int_0^1 y dy, int_0^1 z dz equals 1/2.", "Multiply them."],
      solution: "The value is (1/2)^3=1/8."
    },
    {
      id: "gap-int-triple-002",
      topic: "integrals",
      difficulty: 2,
      source: "Buzz gap pack",
      prompt: "\\int_0^1\\int_0^1\\int_0^1 (x+y+z)\\,dz\\,dy\\,dx",
      answerKind: "numeric",
      answer: "3/2",
      timeLimit: 75,
      tabLimit: 1,
      tags: ["triple-integral", "iterated-integral"],
      hints: ["Use symmetry.", "The average of x, y, and z on the unit cube is 1/2 each.", "Add three copies."],
      solution: "Each coordinate contributes 1/2, so the total is 3/2."
    },
    {
      id: "gap-int-triple-003",
      topic: "integrals",
      difficulty: 3,
      source: "Buzz gap pack",
      prompt: "\\iiint_{x+y+z\\le 1,\\ x,y,z\\ge0}1\\,dV",
      answerKind: "numeric",
      answer: "1/6",
      timeLimit: 80,
      tabLimit: 1,
      tags: ["triple-integral", "volume", "simplex"],
      hints: ["This is a tetrahedron.", "Intercepts are all 1.", "Volume is 1/6."],
      solution: "The standard simplex in R^3 has volume 1/6."
    },
    {
      id: "gap-int-triple-004",
      topic: "integrals",
      difficulty: 3,
      source: "Buzz gap pack",
      prompt: "\\int_0^1\\int_0^x\\int_0^y 1\\,dz\\,dy\\,dx",
      answerKind: "numeric",
      answer: "1/6",
      timeLimit: 80,
      tabLimit: 1,
      tags: ["triple-integral", "iterated-integral"],
      hints: ["The z-integral gives y.", "Then integrate y from 0 to x.", "Finally integrate x^2/2 from 0 to 1."],
      solution: "The integral becomes int_0^1 x^2/2 dx=1/6."
    },
    {
      id: "gap-int-triple-005",
      topic: "integrals",
      difficulty: 3,
      source: "Buzz gap pack",
      prompt: "\\text{Volume of the cylinder }x^2+y^2\\le4,\\ 0\\le z\\le3",
      answerKind: "numeric",
      answer: "12*pi",
      timeLimit: 70,
      tabLimit: 1,
      tags: ["triple-integral", "cylindrical-coordinates", "volume"],
      hints: ["Radius is 2.", "Base area is 4pi.", "Height is 3."],
      solution: "The volume is pi(2^2)(3)=12pi."
    },
    {
      id: "gap-int-triple-006",
      topic: "integrals",
      difficulty: 3,
      source: "Buzz gap pack",
      prompt: "\\text{Volume of the ball }x^2+y^2+z^2\\le4",
      answerKind: "numeric",
      answer: "32*pi/3",
      timeLimit: 70,
      tabLimit: 1,
      tags: ["triple-integral", "spherical-coordinates", "volume"],
      hints: ["The radius is 2.", "Use 4pi r^3/3.", "Substitute r=2."],
      solution: "The volume is (4/3)pi(2^3)=32pi/3."
    },
    {
      id: "gap-int-cov-001",
      topic: "integrals",
      difficulty: 3,
      source: "Buzz gap pack",
      prompt: "u=x+y,\\ v=x-y.\\ \\left|\\frac{\\partial(x,y)}{\\partial(u,v)}\\right|=?",
      answerKind: "numeric",
      answer: "1/2",
      timeLimit: 75,
      tabLimit: 1,
      tags: ["change-of-variables", "jacobian"],
      hints: ["Solve x=(u+v)/2 and y=(u-v)/2.", "Build the 2 by 2 Jacobian.", "Its determinant has absolute value 1/2."],
      solution: "The inverse Jacobian determinant is -1/2, so the absolute value is 1/2."
    },
    {
      id: "gap-int-cov-002",
      topic: "integrals",
      difficulty: 3,
      source: "Buzz gap pack",
      prompt: "\\text{Area of }0\\le x+y\\le1,\\ 0\\le x-y\\le2",
      answerKind: "numeric",
      answer: "1",
      timeLimit: 80,
      tabLimit: 1,
      tags: ["change-of-variables", "jacobian", "area"],
      hints: ["Use u=x+y and v=x-y.", "The uv-rectangle has area 2.", "Multiply by |J|=1/2."],
      solution: "The area is 2*(1/2)=1."
    },
    {
      id: "gap-der-ode-001",
      topic: "derivatives",
      difficulty: 2,
      source: "Buzz gap pack",
      prompt: "y'+y=0,\\ y(0)=2.\\ y=?",
      answerKind: "expression",
      answer: "2*exp(-x)",
      variable: "x",
      timeLimit: 75,
      tabLimit: 1,
      tags: ["ode-intro", "separable", "first-order"],
      hints: ["The equation is y'=-y.", "Solutions are Ce^{-x}.", "Use y(0)=2."],
      solution: "y=Ce^{-x}; the initial condition gives C=2."
    },
    {
      id: "gap-der-ode-002",
      topic: "derivatives",
      difficulty: 2,
      source: "Buzz gap pack",
      prompt: "y'=2y,\\ y(0)=3.\\ y=?",
      answerKind: "expression",
      answer: "3*exp(2*x)",
      variable: "x",
      timeLimit: 70,
      tabLimit: 1,
      tags: ["ode-intro", "separable", "exponential-growth"],
      hints: ["Solutions are Ce^{2x}.", "Use y(0)=3.", "This is exponential growth."],
      solution: "The solution is y=3e^{2x}."
    },
    {
      id: "gap-der-ode-003",
      topic: "derivatives",
      difficulty: 3,
      source: "Buzz gap pack",
      prompt: "y'+y=e^x,\\ y(0)=0.\\ y=?",
      answerKind: "expression",
      answer: "(exp(x)-exp(-x))/2",
      variable: "x",
      timeLimit: 95,
      tabLimit: 1,
      tags: ["ode-intro", "integrating-factor", "first-order"],
      hints: ["Use integrating factor e^x.", "(e^x y)'=e^{2x}.", "Use the initial condition."],
      solution: "e^x y=(e^{2x}-1)/2, so y=(e^x-e^{-x})/2."
    },
    {
      id: "gap-der-ode-004",
      topic: "derivatives",
      difficulty: 3,
      source: "Buzz gap pack",
      prompt: "y''+y=0,\\ y(0)=0,\\ y'(0)=1.\\ y=?",
      answerKind: "expression",
      answer: "sin(x)",
      variable: "x",
      timeLimit: 90,
      tabLimit: 1,
      tags: ["ode-intro", "second-order", "trig"],
      hints: ["General solution is A cos x+B sin x.", "y(0)=0 gives A=0.", "y'(0)=1 gives B=1."],
      solution: "The solution is y=sin x."
    },
    {
      id: "gap-der-ode-005",
      topic: "derivatives",
      difficulty: 4,
      source: "Buzz gap pack",
      prompt: "y'=y(1-y),\\ y(0)=1/2.\\ y=?",
      answerKind: "expression",
      answer: "1/(1+exp(-x))",
      variable: "x",
      timeLimit: 105,
      tabLimit: 1,
      tags: ["ode-intro", "logistic", "separable"],
      hints: ["The logistic solution is 1/(1+Ce^{-x}).", "Use y(0)=1/2.", "This gives C=1."],
      solution: "With C=1, the solution is y=1/(1+e^{-x})."
    },
    {
      id: "gap-ser-root-001",
      topic: "series",
      difficulty: 3,
      source: "Buzz gap pack",
      prompt: "\\text{Radius of convergence of }\\sum_{n=1}^{\\infty}\\frac{3^n}{n^2}x^n",
      answerKind: "numeric",
      answer: "1/3",
      timeLimit: 75,
      tabLimit: 1,
      tags: ["root-test", "power-series", "radius"],
      hints: ["Use the root test.", "The nth root behaves like 3|x|.", "Require 3|x|<1."],
      solution: "The radius is 1/3."
    },
    {
      id: "gap-ser-root-002",
      topic: "series",
      difficulty: 3,
      source: "Buzz gap pack",
      prompt: "\\text{Radius of convergence of }\\sum_{n=1}^{\\infty}\\left(\\frac{n}{n+1}\\right)^n x^n",
      answerKind: "numeric",
      answer: "1",
      timeLimit: 85,
      tabLimit: 1,
      tags: ["root-test", "power-series", "radius"],
      hints: ["Use the root test.", "The nth root is (n/(n+1))|x|.", "The factor tends to 1."],
      solution: "The root test gives |x|<1, so R=1."
    },
    {
      id: "gap-ser-lc-001",
      topic: "series",
      difficulty: 3,
      source: "Buzz gap pack",
      prompt: "\\sum_{n=1}^{\\infty}\\frac{3n^2+1}{n^3+2}\\ \\text{ converges or diverges?}",
      answerKind: "text",
      answers: ["divergent", "diverges", "發散"],
      canonical: "divergent",
      timeLimit: 75,
      tabLimit: 1,
      tags: ["limit-comparison", "harmonic"],
      hints: ["Compare with 1/n.", "The term behaves like 3/n.", "The harmonic series diverges."],
      solution: "Limit comparison with 1/n gives a nonzero constant, so the series diverges."
    },
    {
      id: "gap-ser-lc-002",
      topic: "series",
      difficulty: 3,
      source: "Buzz gap pack",
      prompt: "\\sum_{n=1}^{\\infty}\\frac{n+1}{n^3+1}\\ \\text{ converges or diverges?}",
      answerKind: "text",
      answers: ["convergent", "converges", "收斂"],
      canonical: "convergent",
      timeLimit: 75,
      tabLimit: 1,
      tags: ["limit-comparison", "p-series"],
      hints: ["Compare with 1/n^2.", "The term behaves like n/n^3.", "p=2 converges."],
      solution: "Limit comparison with 1/n^2 shows convergence."
    },
    {
      id: "gap-ser-cond-001",
      topic: "series",
      difficulty: 3,
      source: "Buzz gap pack",
      prompt: "\\sum_{n=1}^{\\infty}\\frac{(-1)^n}{n}\\ \\text{ absolute, conditional, or divergent?}",
      answerKind: "text",
      answers: ["conditional", "conditionally convergent", "conditional convergence", "條件收斂"],
      canonical: "conditional",
      timeLimit: 75,
      tabLimit: 1,
      tags: ["alternating-series", "absolute-conditional"],
      hints: ["The alternating harmonic series converges.", "The absolute series is harmonic.", "So convergence is conditional."],
      solution: "It converges by the alternating test but not absolutely."
    },
    {
      id: "gap-ser-end-001",
      topic: "series",
      difficulty: 4,
      source: "Buzz gap pack",
      prompt: "\\sum_{n=1}^{\\infty}\\frac{x^n}{n}\\text{ at }x=-1\\text{ is absolute, conditional, or divergent?}",
      answerKind: "text",
      answers: ["conditional", "conditionally convergent", "conditional convergence", "條件收斂"],
      canonical: "conditional",
      timeLimit: 85,
      tabLimit: 1,
      tags: ["endpoint-analysis", "power-series", "alternating-series"],
      hints: ["At x=-1, the series becomes sum (-1)^n/n.", "It converges by alternating test.", "The absolute series diverges."],
      solution: "The endpoint x=-1 is conditionally convergent."
    },
    {
      id: "gap-ser-end-002",
      topic: "series",
      difficulty: 4,
      source: "Buzz gap pack",
      prompt: "\\sum_{n=1}^{\\infty}\\frac{x^n}{n}\\text{ at }x=1\\text{ converges or diverges?}",
      answerKind: "text",
      answers: ["divergent", "diverges", "發散"],
      canonical: "divergent",
      timeLimit: 80,
      tabLimit: 1,
      tags: ["endpoint-analysis", "power-series", "harmonic"],
      hints: ["At x=1, the series is harmonic.", "sum 1/n diverges.", "Endpoint behavior must be checked separately."],
      solution: "At x=1, the series is the divergent harmonic series."
    },
    {
      id: "gap-ser-taylor-001",
      topic: "series",
      difficulty: 3,
      source: "Buzz gap pack",
      prompt: "\\text{Coefficient of }x^5\\text{ in the Maclaurin series for }\\sin x",
      answerKind: "numeric",
      answer: "1/120",
      timeLimit: 70,
      tabLimit: 1,
      tags: ["taylor", "coefficient", "full-expansion"],
      hints: ["sin x=x-x^3/3!+x^5/5!-...", "The x^5 term is positive.", "5!=120."],
      solution: "The coefficient is 1/5!=1/120."
    },
    {
      id: "gap-ser-taylor-002",
      topic: "series",
      difficulty: 3,
      source: "Buzz gap pack",
      prompt: "\\text{Degree 4 Maclaurin polynomial for }\\cos x",
      answerKind: "expression",
      answer: "1-x^2/2+x^4/24",
      variable: "x",
      timeLimit: 80,
      tabLimit: 1,
      tags: ["taylor", "full-expansion"],
      hints: ["cos x=1-x^2/2!+x^4/4!-...", "Keep terms through x^4.", "4!=24."],
      solution: "The polynomial is 1-x^2/2+x^4/24."
    },
    {
      id: "gap-tech-001",
      topic: "limits",
      difficulty: 1,
      source: "Buzz technique recognition",
      prompt: "\\text{Technique for }\\lim_{x\\to\\infty}\\left(\\sqrt{x^2+3x}-x\\right)",
      answerKind: "text",
      answers: ["rationalize", "rationalization", "conjugate", "有理化"],
      canonical: "rationalize",
      timeLimit: 45,
      tabLimit: 1,
      tags: ["technique-recognition", "rationalize"],
      hints: ["There is a radical difference.", "Multiply by the conjugate.", "This is the rationalization trigger."],
      solution: "The right reflex is to rationalize with the conjugate."
    },
    {
      id: "gap-tech-002",
      topic: "limits",
      difficulty: 1,
      source: "Buzz technique recognition",
      prompt: "\\text{Technique for }\\lim_{x\\to0}\\frac{e^{2x}-1-2x}{x^2}",
      answerKind: "text",
      answers: ["taylor", "series", "expansion", "泰勒"],
      canonical: "taylor",
      timeLimit: 45,
      tabLimit: 1,
      tags: ["technique-recognition", "taylor"],
      hints: ["The numerator cancels low-order terms.", "Expand e^{2x}.", "This is a Taylor trigger."],
      solution: "Use Taylor expansion of e^{2x} around 0."
    },
    {
      id: "gap-tech-003",
      topic: "integrals",
      difficulty: 1,
      source: "Buzz technique recognition",
      prompt: "\\text{Technique for }\\int x e^{x^2}\\,dx",
      answerKind: "text",
      answers: ["substitution", "u-sub", "u substitution", "換元"],
      canonical: "substitution",
      timeLimit: 45,
      tabLimit: 1,
      tags: ["technique-recognition", "substitution", "u-sub"],
      hints: ["A function and its derivative appear together.", "Let u=x^2.", "This is u-substitution."],
      solution: "Use u=x^2."
    },
    {
      id: "gap-tech-004",
      topic: "integrals",
      difficulty: 1,
      source: "Buzz technique recognition",
      prompt: "\\text{Technique for }\\int x\\log x\\,dx",
      answerKind: "text",
      answers: ["integration by parts", "ibp", "分部積分"],
      canonical: "integration by parts",
      timeLimit: 45,
      tabLimit: 1,
      tags: ["technique-recognition", "integration-by-parts", "ibp"],
      hints: ["A polynomial times log appears.", "One factor differentiates simpler.", "Use integration by parts."],
      solution: "Use integration by parts with u=log x."
    },
    {
      id: "gap-tech-005",
      topic: "series",
      difficulty: 1,
      source: "Buzz technique recognition",
      prompt: "\\text{Technique for }\\sum \\left(\\frac{n}{n+1}\\right)^n x^n",
      answerKind: "text",
      answers: ["root test", "root-test", "根值判別"],
      canonical: "root test",
      timeLimit: 45,
      tabLimit: 1,
      tags: ["technique-recognition", "root-test"],
      hints: ["There is an n-th power.", "Take the nth root.", "This is a root-test trigger."],
      solution: "Use the root test."
    },
    {
      id: "gap-tech-006",
      topic: "integrals",
      difficulty: 1,
      source: "Buzz technique recognition",
      prompt: "\\text{Technique for }\\int \\frac{1}{x^2-1}\\,dx",
      answerKind: "text",
      answers: ["partial fraction", "partial fractions", "partial-fraction", "部分分式"],
      canonical: "partial fraction",
      timeLimit: 45,
      tabLimit: 1,
      tags: ["technique-recognition", "partial-fraction"],
      hints: ["The denominator factors.", "The numerator is not a derivative trigger.", "Split into simple rational terms."],
      solution: "Use partial fractions after factoring x^2-1."
    },
    {
      id: "gap-tech-007",
      topic: "derivatives",
      difficulty: 1,
      source: "Buzz technique recognition",
      prompt: "x=t^2,\\ y=t^3.\\ \\text{Which differentiation technique?}",
      answerKind: "text",
      answers: ["parametric", "parametric differentiation", "參數微分"],
      canonical: "parametric differentiation",
      timeLimit: 45,
      tabLimit: 1,
      tags: ["technique-recognition", "parametric"],
      hints: ["x and y are both functions of t.", "Compute dy/dt and dx/dt.", "Then divide."],
      solution: "Use parametric differentiation."
    },
    {
      id: "gap-tech-008",
      topic: "limits",
      difficulty: 2,
      source: "Buzz technique recognition",
      prompt: "\\text{Technique for }\\lim_{(x,y)\\to(0,0)}\\frac{x^2y}{x^4+y^2}",
      answerKind: "text",
      answers: ["path test", "path", "路徑測試"],
      canonical: "path test",
      timeLimit: 55,
      tabLimit: 1,
      tags: ["technique-recognition", "multivariable-limit", "path-test"],
      hints: ["Try y=mx^2.", "Different paths may give different values.", "This is a path-test trigger."],
      solution: "Use a path test such as y=mx^2."
    }
  ];

  window.BUZZ_PROBLEMS = (window.BUZZ_PROBLEMS || []).concat(gapProblems);
})();
