(function () {
  "use strict";

  const extraProblems = [
    {
      id: "lim-031",
      topic: "limits",
      difficulty: 3,
      source: "Buzz original",
      prompt: "\\lim_{(x,y)\\to(0,0)}\\frac{x^2y^2}{x^2+y^2}",
      answerKind: "numeric",
      answer: "0",
      timeLimit: 70,
      tabLimit: 1,
      tags: ["multivariable", "squeeze"],
      hints: ["Use polar size r^2=x^2+y^2.", "The numerator has order 4 and denominator order 2.", "The whole expression is bounded by a constant times r^2."],
      solution: "With x=r cos t, y=r sin t, the expression is r^2 cos^2 t sin^2 t, so the limit is 0."
    },
    {
      id: "lim-032",
      topic: "limits",
      difficulty: 3,
      source: "Buzz original",
      prompt: "\\lim_{(x,y)\\to(0,0)}\\frac{x^2-y^2}{x^2+y^2}",
      answerKind: "numeric",
      answer: "dne",
      timeLimit: 70,
      tabLimit: 1,
      tags: ["multivariable", "path-test", "dne"],
      hints: ["Test y=0 and x=0.", "The two paths give different values.", "Different path values mean DNE."],
      solution: "Along y=0 the value is 1; along x=0 the value is -1. The limit does not exist."
    },
    {
      id: "lim-033",
      topic: "limits",
      difficulty: 2,
      source: "Buzz original",
      prompt: "\\lim_{(x,y)\\to(0,0)}\\frac{e^{x+y}-1}{x+y}",
      answerKind: "numeric",
      answer: "1",
      timeLimit: 60,
      tabLimit: 1,
      tags: ["multivariable", "standard-limit", "exponential"],
      hints: ["Let u=x+y.", "Then u tends to 0.", "Use (e^u-1)/u -> 1."],
      solution: "Set u=x+y. The expression becomes (e^u-1)/u, so the limit is 1."
    },
    {
      id: "lim-034",
      topic: "limits",
      difficulty: 3,
      source: "Buzz original",
      prompt: "\\lim_{(x,y)\\to(0,0)}\\frac{x^3}{x^2+y^2}",
      answerKind: "numeric",
      answer: "0",
      timeLimit: 70,
      tabLimit: 1,
      tags: ["multivariable", "squeeze"],
      hints: ["Use |x| <= sqrt(x^2+y^2).", "Then |x^3|/(x^2+y^2) <= r.", "r tends to 0."],
      solution: "Let r=sqrt(x^2+y^2). Since |x|<=r, the absolute value is <= r^3/r^2=r, hence the limit is 0."
    },
    {
      id: "lim-035",
      topic: "limits",
      difficulty: 2,
      source: "Buzz original",
      prompt: "\\lim_{x\\to0}\\frac{\\sin(5x)}{\\sin(2x)}",
      answerKind: "numeric",
      answer: "5/2",
      timeLimit: 50,
      tabLimit: 1,
      tags: ["standard-limit", "trig-limit"],
      hints: ["Use sin(kx) ~ kx.", "The ratio becomes 5x/2x.", "Cancel x."],
      solution: "As x->0, sin(5x)~5x and sin(2x)~2x, so the limit is 5/2."
    },
    {
      id: "lim-036",
      topic: "limits",
      difficulty: 3,
      source: "Buzz original",
      prompt: "\\lim_{x\\to0}\\frac{\\log(1+x+x^2)-x}{x^2}",
      answerKind: "numeric",
      answer: "1/2",
      timeLimit: 70,
      tabLimit: 1,
      tags: ["taylor", "log"],
      hints: ["Let u=x+x^2.", "log(1+u)=u-u^2/2+O(u^3).", "Keep terms through x^2."],
      solution: "log(1+x+x^2)=x+x^2-(x^2/2)+O(x^3)=x+x^2/2+O(x^3). The limit is 1/2."
    },
    {
      id: "lim-037",
      topic: "limits",
      difficulty: 2,
      source: "Buzz original",
      prompt: "\\lim_{x\\to0}\\frac{\\sqrt{1+4x}-1}{x}",
      answerKind: "numeric",
      answer: "2",
      timeLimit: 50,
      tabLimit: 1,
      tags: ["rationalize"],
      hints: ["Rationalize the numerator.", "The numerator becomes 4x.", "Then let x go to 0."],
      solution: "After rationalizing, the expression is 4/(sqrt(1+4x)+1), whose limit is 2."
    },
    {
      id: "lim-038",
      topic: "limits",
      difficulty: 3,
      source: "Buzz original",
      prompt: "\\lim_{x\\to0}\\frac{\\sin x-x\\cos x}{x^3}",
      answerKind: "numeric",
      answer: "1/3",
      timeLimit: 70,
      tabLimit: 1,
      tags: ["taylor", "trig-limit"],
      hints: ["Expand sin x and x cos x.", "sin x=x-x^3/6+...", "x cos x=x-x^3/2+..."],
      solution: "sin x-x cos x=(x-x^3/6)-(x-x^3/2)+O(x^5)=x^3/3+O(x^5)."
    },
    {
      id: "lim-039",
      topic: "limits",
      difficulty: 3,
      source: "Buzz original",
      prompt: "\\lim_{(x,y)\\to(0,0)}\\frac{x^2y}{x^4+y^2}",
      answerKind: "numeric",
      answer: "dne",
      timeLimit: 80,
      tabLimit: 1,
      tags: ["multivariable", "path-test", "dne"],
      hints: ["Try y=kx^2.", "The expression becomes k/(1+k^2).", "Different k gives different limits."],
      solution: "Along y=kx^2 the expression is k/(1+k^2). Since this depends on k, the limit does not exist."
    },
    {
      id: "lim-040",
      topic: "limits",
      difficulty: 2,
      source: "Buzz original",
      prompt: "\\lim_{x\\to\\infty}x\\log\\left(1+\\frac{2}{x}\\right)",
      answerKind: "numeric",
      answer: "2",
      timeLimit: 55,
      tabLimit: 1,
      tags: ["standard-limit", "log", "infinity"],
      hints: ["Let u=2/x.", "Use log(1+u)~u.", "Then x*(2/x) remains."],
      solution: "Since log(1+2/x)~2/x, the limit is 2."
    },
    {
      id: "der-031",
      topic: "derivatives",
      difficulty: 3,
      source: "Buzz original",
      prompt: "\\frac{\\partial}{\\partial x}\\left(e^{x^2+y^2}\\right)",
      answerKind: "expression",
      answer: "2*x*exp(x^2+y^2)",
      variables: ["x", "y"],
      timeLimit: 65,
      tabLimit: 1,
      tags: ["multivariable", "partial-derivative", "chain-rule"],
      hints: ["Use chain rule.", "The inside x^2+y^2 has x-derivative 2x.", "Keep y constant."],
      solution: "The derivative is e^{x^2+y^2} times 2x."
    },
    {
      id: "der-032",
      topic: "derivatives",
      difficulty: 3,
      source: "Buzz original",
      prompt: "\\frac{\\partial}{\\partial y}\\arctan\\left(\\frac{y}{x}\\right)",
      answerKind: "expression",
      answer: "x/(x^2+y^2)",
      variables: ["x", "y"],
      timeLimit: 75,
      tabLimit: 1,
      tags: ["multivariable", "partial-derivative", "inverse-trig"],
      hints: ["Let u=y/x.", "d arctan u = u'/(1+u^2).", "For y derivative, u'=1/x."],
      solution: "(1/x)/(1+y^2/x^2)=x/(x^2+y^2)."
    },
    {
      id: "der-033",
      topic: "derivatives",
      difficulty: 3,
      source: "Buzz original",
      prompt: "\\frac{\\partial^2}{\\partial x^2}\\left(x^2y+\\sin x\\right)",
      answerKind: "expression",
      answer: "2*y-sin(x)",
      variables: ["x", "y"],
      timeLimit: 65,
      tabLimit: 1,
      tags: ["multivariable", "second-derivative"],
      hints: ["Differentiate twice with respect to x.", "First derivative is 2xy+cos x.", "Differentiate again."],
      solution: "f_x=2xy+cos x, so f_xx=2y-sin x."
    },
    {
      id: "der-034",
      topic: "derivatives",
      difficulty: 3,
      source: "Buzz original",
      prompt: "\\text{Jacobian determinant of }u=x+y,\\ v=xy",
      answerKind: "expression",
      answer: "x-y",
      variables: ["x", "y"],
      timeLimit: 75,
      tabLimit: 1,
      tags: ["multivariable", "jacobian"],
      hints: ["Build the 2 by 2 derivative matrix.", "Rows are (u_x,u_y) and (v_x,v_y).", "Take determinant."],
      solution: "The Jacobian matrix is [[1,1],[y,x]], so det = x-y."
    },
    {
      id: "der-035",
      topic: "derivatives",
      difficulty: 3,
      source: "Buzz original",
      prompt: "\\text{If }z=x^2y,\\ x=t^2,\\ y=e^t,\\text{ find }dz/dt",
      answerKind: "expression",
      answer: "exp(t)*(4*t^3+t^4)",
      variables: ["t"],
      timeLimit: 80,
      tabLimit: 1,
      tags: ["multivariable", "chain-rule"],
      hints: ["Substitute first or use multivariable chain rule.", "z=t^4 e^t.", "Differentiate product."],
      solution: "After substitution z=t^4e^t, so dz/dt=e^t(4t^3+t^4)."
    },
    {
      id: "der-036",
      topic: "derivatives",
      difficulty: 3,
      source: "Buzz original",
      prompt: "\\text{Laplacian of }f=x^2+y^2",
      answerKind: "numeric",
      answer: "4",
      timeLimit: 55,
      tabLimit: 1,
      tags: ["multivariable", "second-derivative", "laplacian"],
      hints: ["Laplacian is f_xx+f_yy.", "f_xx=2.", "f_yy=2."],
      solution: "The Laplacian is 2+2=4."
    },
    {
      id: "der-037",
      topic: "derivatives",
      difficulty: 4,
      source: "Buzz original",
      prompt: "\\text{Hessian determinant of }f=x^3+y^3-3xy\\text{ at }(1,1)",
      answerKind: "numeric",
      answer: "27",
      timeLimit: 90,
      tabLimit: 1,
      tags: ["multivariable", "hessian", "second-derivative"],
      hints: ["Compute f_xx, f_yy, and f_xy.", "At (1,1), f_xx=6 and f_yy=6.", "f_xy=-3."],
      solution: "The Hessian is [[6,-3],[-3,6]], whose determinant is 36-9=27."
    },
    {
      id: "der-038",
      topic: "derivatives",
      difficulty: 2,
      source: "Buzz original",
      prompt: "\\frac{d}{dx}\\left(\\frac{x^2+1}{x-1}\\right)",
      answerKind: "expression",
      answer: "(x^2-2*x-1)/(x-1)^2",
      timeLimit: 65,
      tabLimit: 1,
      tags: ["quotient-rule"],
      hints: ["Use quotient rule.", "Numerator derivative is 2x.", "Simplify the numerator."],
      solution: "Derivative is [2x(x-1)-(x^2+1)]/(x-1)^2=(x^2-2x-1)/(x-1)^2."
    },
    {
      id: "der-039",
      topic: "derivatives",
      difficulty: 2,
      source: "Buzz original",
      prompt: "\\frac{d}{dx}\\left(\\sin^2x\\right)",
      answerKind: "expression",
      answer: "2*sin(x)*cos(x)",
      timeLimit: 45,
      tabLimit: 1,
      tags: ["chain-rule", "trig"],
      hints: ["Treat it as (sin x)^2.", "Outer derivative gives 2 sin x.", "Inner derivative gives cos x."],
      solution: "By chain rule, the derivative is 2sin(x)cos(x)."
    },
    {
      id: "der-040",
      topic: "derivatives",
      difficulty: 3,
      source: "Buzz original",
      prompt: "\\frac{d}{dx}\\left(x^{\\log x}\\right)",
      answerKind: "expression",
      answer: "2*x^log(x)*log(x)/x",
      timeLimit: 80,
      tabLimit: 1,
      tags: ["logarithmic-differentiation"],
      hints: ["Rewrite x^{log x}=exp((log x)^2).", "Differentiate the exponent.", "d(log x)^2 = 2log(x)/x."],
      solution: "x^{log x}=exp((log x)^2), so the derivative is x^{log x}*2log(x)/x."
    },
    {
      id: "int-031",
      topic: "integrals",
      difficulty: 3,
      source: "Buzz original",
      prompt: "\\int_0^1\\int_y^1 x^2\\,dx\\,dy",
      answerKind: "numeric",
      answer: "1/4",
      timeLimit: 70,
      tabLimit: 1,
      tags: ["multivariable", "double-integral", "change-order"],
      hints: ["Region: 0<=y<=x<=1.", "You may swap order.", "Integral becomes int_0^1 int_0^x x^2 dy dx."],
      solution: "Swap order: integral is int_0^1 x^2*x dx = int_0^1 x^3 dx = 1/4."
    },
    {
      id: "int-032",
      topic: "integrals",
      difficulty: 3,
      source: "Buzz original",
      prompt: "\\iint_{1\\le x^2+y^2\\le4}1\\,dA",
      answerKind: "numeric",
      answer: "3*pi",
      timeLimit: 60,
      tabLimit: 1,
      tags: ["multivariable", "polar-coordinates", "area"],
      hints: ["This is an annulus.", "Outer radius is 2 and inner radius is 1.", "Area is pi(R^2-r^2)."],
      solution: "Area = pi(4-1)=3pi."
    },
    {
      id: "int-033",
      topic: "integrals",
      difficulty: 3,
      source: "Buzz original",
      prompt: "\\iint_{x^2+y^2\\le4}x^2\\,dA",
      answerKind: "numeric",
      answer: "4*pi",
      timeLimit: 85,
      tabLimit: 1,
      tags: ["multivariable", "polar-coordinates", "symmetry"],
      hints: ["By symmetry, integral of x^2 equals integral of y^2.", "So it is half of integral of r^2.", "Use polar coordinates on radius 2."],
      solution: "Integral of r^2 over disk radius 2 is int_0^{2pi}int_0^2 r^3 dr dtheta=8pi. Half is 4pi."
    },
    {
      id: "int-034",
      topic: "integrals",
      difficulty: 3,
      source: "Buzz original",
      prompt: "\\int_0^1\\int_0^{\\sqrt{1-x^2}}1\\,dy\\,dx",
      answerKind: "numeric",
      answer: "pi/4",
      timeLimit: 60,
      tabLimit: 1,
      tags: ["multivariable", "area"],
      hints: ["The region is a quarter unit disk.", "Area of unit disk is pi.", "Quarter area is pi/4."],
      solution: "The region is x>=0,y>=0,x^2+y^2<=1, so the area is pi/4."
    },
    {
      id: "int-035",
      topic: "integrals",
      difficulty: 3,
      source: "Buzz original",
      prompt: "\\int_0^{2\\pi}\\int_0^1 r^2\\cdot r\\,dr\\,d\\theta",
      answerKind: "numeric",
      answer: "pi/2",
      timeLimit: 60,
      tabLimit: 1,
      tags: ["multivariable", "polar-coordinates", "double-integral"],
      hints: ["Integrate r^3 in r.", "Then multiply by 2pi.", "int_0^1 r^3 dr=1/4."],
      solution: "The integral is 2pi*(1/4)=pi/2."
    },
    {
      id: "int-036",
      topic: "integrals",
      difficulty: 3,
      source: "Buzz original",
      prompt: "\\int_0^1\\int_0^{1-y}x\\,dx\\,dy",
      answerKind: "numeric",
      answer: "1/6",
      timeLimit: 65,
      tabLimit: 1,
      tags: ["multivariable", "double-integral", "triangle"],
      hints: ["First integrate x.", "Inner integral gives (1-y)^2/2.", "Then integrate from 0 to 1."],
      solution: "Integral is (1/2)int_0^1(1-y)^2dy=1/6."
    },
    {
      id: "int-037",
      topic: "integrals",
      difficulty: 3,
      source: "Buzz original",
      prompt: "\\int x e^{x^2}\\,dx",
      answerKind: "antiderivative",
      answer: "exp(x^2)/2",
      timeLimit: 50,
      tabLimit: 1,
      tags: ["substitution"],
      hints: ["Let u=x^2.", "du=2x dx.", "A factor 1/2 remains."],
      solution: "With u=x^2, the antiderivative is e^{x^2}/2."
    },
    {
      id: "int-038",
      topic: "integrals",
      difficulty: 3,
      source: "Buzz original",
      prompt: "\\int x\\cos x\\,dx",
      answerKind: "antiderivative",
      answer: "x*sin(x)+cos(x)",
      timeLimit: 65,
      tabLimit: 1,
      tags: ["integration-by-parts"],
      hints: ["Use integration by parts.", "Take u=x and dv=cos x dx.", "v=sin x."],
      solution: "Integration by parts gives x sin x - int sin x dx = x sin x + cos x."
    },
    {
      id: "int-039",
      topic: "integrals",
      difficulty: 3,
      source: "Buzz original",
      prompt: "\\int_0^1\\frac{1}{1+x^2}\\,dx",
      answerKind: "numeric",
      answer: "pi/4",
      timeLimit: 50,
      tabLimit: 1,
      tags: ["inverse-trig", "definite-integral"],
      hints: ["Antiderivative is atan x.", "Evaluate from 0 to 1.", "atan(1)=pi/4."],
      solution: "The integral is atan(1)-atan(0)=pi/4."
    },
    {
      id: "int-040",
      topic: "integrals",
      difficulty: 4,
      source: "Buzz original",
      prompt: "\\int_0^\\infty xe^{-x}\\,dx",
      answerKind: "numeric",
      answer: "1",
      timeLimit: 70,
      tabLimit: 1,
      tags: ["improper-integral", "gamma"],
      hints: ["This is Gamma(2).", "Gamma(n+1)=n!.", "Gamma(2)=1."],
      solution: "The integral equals Gamma(2)=1!=1."
    },
    {
      id: "ser-031",
      topic: "series",
      difficulty: 3,
      source: "Buzz original",
      prompt: "\\sum_{n=1}^{\\infty}\\frac{1}{\\sqrt n}",
      answerKind: "text",
      answers: ["diverges", "divergent", "發散"],
      canonical: "發散",
      timeLimit: 45,
      tabLimit: 1,
      tags: ["p-series"],
      hints: ["This is a p-series.", "p=1/2.", "p<=1 diverges."],
      solution: "Since p=1/2<=1, the p-series diverges."
    },
    {
      id: "ser-032",
      topic: "series",
      difficulty: 3,
      source: "Buzz original",
      prompt: "\\sum_{n=1}^{\\infty}\\left(\\frac{n}{n+1}\\right)^n",
      answerKind: "text",
      answers: ["diverges", "divergent", "發散"],
      canonical: "發散",
      timeLimit: 65,
      tabLimit: 1,
      tags: ["term-test"],
      hints: ["Check the nth term limit.", "(n/(n+1))^n tends to e^{-1}.", "Terms do not go to 0."],
      solution: "The terms tend to e^{-1}, not 0, so the series diverges."
    },
    {
      id: "ser-033",
      topic: "series",
      difficulty: 3,
      source: "Buzz original",
      prompt: "\\sum_{n=1}^{\\infty}\\frac{(-1)^n}{\\sqrt n}",
      answerKind: "text",
      answers: ["conditionally converges", "conditional", "條件收斂"],
      canonical: "條件收斂",
      timeLimit: 65,
      tabLimit: 1,
      tags: ["alternating-series", "conditional-convergence"],
      hints: ["Alternating series test applies.", "1/sqrt(n) decreases to 0.", "Absolute series is a p-series with p=1/2."],
      solution: "The alternating series converges, but the absolute series diverges, so it is conditionally convergent."
    },
    {
      id: "ser-034",
      topic: "series",
      difficulty: 3,
      source: "Buzz original",
      prompt: "\\text{Radius of convergence of }\\sum_{n=1}^{\\infty}n!x^n",
      answerKind: "numeric",
      answer: "0",
      timeLimit: 60,
      tabLimit: 1,
      tags: ["power-series", "radius", "ratio-test"],
      hints: ["Use ratio test.", "a_{n+1}/a_n=(n+1)|x|.", "For any nonzero x this grows without bound."],
      solution: "Only x=0 converges, so the radius is 0."
    },
    {
      id: "ser-035",
      topic: "series",
      difficulty: 3,
      source: "Buzz original",
      prompt: "\\text{Radius of convergence of }\\sum_{n=1}^{\\infty}\\frac{x^n}{n!}",
      answerKind: "text",
      answers: ["infinite", "infinity", "無窮大"],
      canonical: "Infinity",
      timeLimit: 60,
      tabLimit: 1,
      tags: ["power-series", "radius", "ratio-test"],
      hints: ["Use ratio test.", "Ratio is |x|/(n+1).", "This tends to 0 for every x."],
      solution: "The series converges for all x, so the radius is Infinity."
    },
    {
      id: "ser-036",
      topic: "series",
      difficulty: 3,
      source: "Buzz original",
      prompt: "\\sum_{n=1}^{\\infty}\\frac{2^n}{3^n+n}",
      answerKind: "text",
      answers: ["converges", "convergent", "收斂"],
      canonical: "收斂",
      timeLimit: 70,
      tabLimit: 1,
      tags: ["comparison", "geometric-series"],
      hints: ["Compare with (2/3)^n.", "Denominator is bigger than 3^n.", "So the term is less than (2/3)^n."],
      solution: "0 <= 2^n/(3^n+n) <= (2/3)^n, so the series converges by comparison."
    },
    {
      id: "ser-037",
      topic: "series",
      difficulty: 3,
      source: "Buzz original",
      prompt: "\\sum_{n=2}^{\\infty}\\frac{1}{n(\\log n)^2}",
      answerKind: "text",
      answers: ["converges", "convergent", "收斂"],
      canonical: "收斂",
      timeLimit: 70,
      tabLimit: 1,
      tags: ["integral-test", "log"],
      hints: ["Use integral test.", "Integral of 1/(x(log x)^p) converges when p>1.", "Here p=2."],
      solution: "The integral test shows convergence because p=2>1."
    },
    {
      id: "ser-038",
      topic: "series",
      difficulty: 2,
      source: "Buzz original",
      prompt: "\\text{Coefficient of }x^3\\text{ in }\\log(1+x)",
      answerKind: "numeric",
      answer: "1/3",
      timeLimit: 50,
      tabLimit: 1,
      tags: ["taylor", "coefficient"],
      hints: ["log(1+x)=x-x^2/2+x^3/3-...", "Read the x^3 coefficient.", "The sign is positive."],
      solution: "The coefficient of x^3 in log(1+x) is 1/3."
    },
    {
      id: "ser-039",
      topic: "series",
      difficulty: 3,
      source: "Buzz original",
      prompt: "\\text{Radius of convergence of }\\sum_{n=1}^{\\infty}\\frac{(2x)^n}{n}",
      answerKind: "numeric",
      answer: "1/2",
      timeLimit: 55,
      tabLimit: 1,
      tags: ["power-series", "radius"],
      hints: ["This behaves like sum (2x)^n/n.", "Need |2x|<1.", "Solve for |x|."],
      solution: "The radius condition is |2x|<1, so R=1/2."
    },
    {
      id: "ser-040",
      topic: "series",
      difficulty: 3,
      source: "Buzz original",
      prompt: "\\sum_{n=1}^{\\infty}\\frac{n^2}{2^n}",
      answerKind: "numeric",
      answer: "6",
      timeLimit: 60,
      tabLimit: 1,
      tags: ["power-series", "geometric-derivative"],
      hints: ["Use sum n^2 r^n.", "Formula is r(1+r)/(1-r)^3.", "Take r=1/2."],
      solution: "For r=1/2, r(1+r)/(1-r)^3=(1/2)(3/2)/(1/2)^3=6."
    }
  ];

  window.BUZZ_PROBLEMS = (window.BUZZ_PROBLEMS || []).concat(extraProblems);
})();
