window.BUZZ_PROBLEMS = [
  {
    id: "lim-001",
    topic: "limits",
    difficulty: 1,
    prompt: "\\lim_{x \\to 0}\\frac{\\sin x}{x}",
    answerKind: "numeric",
    answer: "1",
    timeLimit: 25,
    tabLimit: 2,
    solution: "標準極限：sin x 和 x 在 0 附近同階，所以答案是 1。"
  },
  {
    id: "lim-002",
    topic: "limits",
    difficulty: 1,
    prompt: "\\lim_{x \\to 0}\\frac{1-\\cos x}{x^2}",
    answerKind: "numeric",
    answer: "1/2",
    timeLimit: 30,
    tabLimit: 2,
    solution: "用 1-cos x 約等於 x^2/2。"
  },
  {
    id: "lim-003",
    topic: "limits",
    difficulty: 1,
    prompt: "\\lim_{x \\to 2}\\frac{x^2-4}{x-2}",
    answerKind: "numeric",
    answer: "4",
    timeLimit: 25,
    tabLimit: 2,
    solution: "因式分解為 (x-2)(x+2)，約掉後代入 x=2。"
  },
  {
    id: "lim-004",
    topic: "limits",
    difficulty: 1,
    prompt: "\\lim_{x \\to \\infty}\\frac{3x^2-x+7}{2x^2+5}",
    answerKind: "numeric",
    answer: "3/2",
    timeLimit: 30,
    tabLimit: 2,
    solution: "最高次項係數比是 3/2。"
  },
  {
    id: "lim-005",
    topic: "limits",
    difficulty: 2,
    prompt: "\\lim_{x \\to 0}\\frac{e^x-1}{x}",
    answerKind: "numeric",
    answer: "1",
    timeLimit: 30,
    tabLimit: 2,
    solution: "e^x 在 0 的線性項是 x。"
  },
  {
    id: "lim-006",
    topic: "limits",
    difficulty: 2,
    prompt: "\\lim_{x \\to 0}\\frac{\\ln(1+3x)}{x}",
    answerKind: "numeric",
    answer: "3",
    timeLimit: 35,
    tabLimit: 2,
    solution: "ln(1+u) 約等於 u，令 u=3x。"
  },
  {
    id: "lim-007",
    topic: "limits",
    difficulty: 2,
    prompt: "\\lim_{x \\to 0}\\frac{\\tan(4x)}{\\sin(2x)}",
    answerKind: "numeric",
    answer: "2",
    timeLimit: 35,
    tabLimit: 2,
    solution: "tan(4x) 約等於 4x，sin(2x) 約等於 2x。"
  },
  {
    id: "lim-008",
    topic: "limits",
    difficulty: 2,
    prompt: "\\lim_{x \\to \\infty}x\\left(\\sqrt{x^2+1}-x\\right)",
    answerKind: "numeric",
    answer: "1/2",
    timeLimit: 45,
    tabLimit: 2,
    solution: "有理化後是 x/(sqrt(x^2+1)+x)，趨近 1/2。"
  },
  {
    id: "lim-009",
    topic: "limits",
    difficulty: 3,
    prompt: "\\lim_{x \\to 0}\\frac{\\sin x-x}{x^3}",
    answerKind: "numeric",
    answer: "-1/6",
    timeLimit: 45,
    tabLimit: 1,
    solution: "sin x = x - x^3/6 + ...。"
  },
  {
    id: "lim-010",
    topic: "limits",
    difficulty: 3,
    prompt: "\\lim_{x \\to 0}\\frac{e^{2x}-1-2x}{x^2}",
    answerKind: "numeric",
    answer: "2",
    timeLimit: 50,
    tabLimit: 1,
    solution: "e^{2x}=1+2x+2x^2+...。"
  },
  {
    id: "lim-011",
    topic: "limits",
    difficulty: 3,
    prompt: "\\lim_{x \\to 0^+}x\\ln x",
    answerKind: "numeric",
    answer: "0",
    timeLimit: 45,
    tabLimit: 1,
    solution: "令 x=1/t，變成 -(ln t)/t，趨近 0。"
  },
  {
    id: "lim-012",
    topic: "limits",
    difficulty: 4,
    prompt: "\\lim_{x \\to 0}\\frac{\\ln(1+x)-x+\\frac{x^2}{2}}{x^3}",
    answerKind: "numeric",
    answer: "1/3",
    timeLimit: 65,
    tabLimit: 1,
    solution: "ln(1+x)=x-x^2/2+x^3/3-...。"
  },
  {
    id: "der-001",
    topic: "derivatives",
    difficulty: 1,
    prompt: "\\frac{d}{dx}\\left(x^5-3x^2+7\\right)",
    answerKind: "expression",
    answer: "5*x^4-6*x",
    variable: "x",
    timeLimit: 30,
    tabLimit: 2,
    solution: "逐項微分。"
  },
  {
    id: "der-002",
    topic: "derivatives",
    difficulty: 1,
    prompt: "\\frac{d}{dx}\\left(\\sin x+\\cos x\\right)",
    answerKind: "expression",
    answer: "cos(x)-sin(x)",
    variable: "x",
    timeLimit: 30,
    tabLimit: 2,
    solution: "sin 的導數是 cos，cos 的導數是 -sin。"
  },
  {
    id: "der-003",
    topic: "derivatives",
    difficulty: 1,
    prompt: "\\frac{d}{dx}\\left(e^x\\ln x\\right)",
    answerKind: "expression",
    answer: "exp(x)*log(x)+exp(x)/x",
    variable: "x",
    timeLimit: 40,
    tabLimit: 2,
    solution: "乘法法則。"
  },
  {
    id: "der-004",
    topic: "derivatives",
    difficulty: 1,
    prompt: "\\frac{d}{dx}\\left(\\sqrt{x}\\right)",
    answerKind: "expression",
    answer: "1/(2*sqrt(x))",
    variable: "x",
    timeLimit: 30,
    tabLimit: 2,
    solution: "sqrt(x)=x^{1/2}。"
  },
  {
    id: "der-005",
    topic: "derivatives",
    difficulty: 2,
    prompt: "\\frac{d}{dx}\\left(\\ln(1+x^2)\\right)",
    answerKind: "expression",
    answer: "2*x/(1+x^2)",
    variable: "x",
    timeLimit: 40,
    tabLimit: 2,
    solution: "鏈鎖律：u=1+x^2。"
  },
  {
    id: "der-006",
    topic: "derivatives",
    difficulty: 2,
    prompt: "\\frac{d}{dx}\\left(x^2\\sin x\\right)",
    answerKind: "expression",
    answer: "2*x*sin(x)+x^2*cos(x)",
    variable: "x",
    timeLimit: 45,
    tabLimit: 2,
    solution: "乘法法則。"
  },
  {
    id: "der-007",
    topic: "derivatives",
    difficulty: 2,
    prompt: "\\frac{d}{dx}\\left(\\arctan x\\right)",
    answerKind: "expression",
    answer: "1/(1+x^2)",
    variable: "x",
    timeLimit: 35,
    tabLimit: 2,
    solution: "反三角函數基本導數。"
  },
  {
    id: "der-008",
    topic: "derivatives",
    difficulty: 2,
    prompt: "\\frac{d}{dx}\\left(\\frac{x}{x+1}\\right)",
    answerKind: "expression",
    answer: "1/(x+1)^2",
    variable: "x",
    timeLimit: 45,
    tabLimit: 2,
    solution: "商法則或改寫成 1-1/(x+1)。"
  },
  {
    id: "der-009",
    topic: "derivatives",
    difficulty: 3,
    prompt: "\\frac{d}{dx}\\left(x^x\\right)",
    answerKind: "expression",
    answer: "x^x*(log(x)+1)",
    variable: "x",
    timeLimit: 55,
    tabLimit: 1,
    solution: "對數微分：x^x=e^{x ln x}。"
  },
  {
    id: "der-010",
    topic: "derivatives",
    difficulty: 3,
    prompt: "\\frac{d}{dx}\\left(\\sin(x^2)e^{-x}\\right)",
    answerKind: "expression",
    answer: "exp(-x)*(2*x*cos(x^2)-sin(x^2))",
    variable: "x",
    timeLimit: 60,
    tabLimit: 1,
    solution: "乘法法則加鏈鎖律。"
  },
  {
    id: "der-011",
    topic: "derivatives",
    difficulty: 3,
    prompt: "\\frac{d}{dx}\\left(\\ln(\\sin x)\\right)",
    answerKind: "expression",
    answer: "cos(x)/sin(x)",
    variable: "x",
    timeLimit: 45,
    tabLimit: 1,
    solution: "鏈鎖律，答案也可寫成 cot x。"
  },
  {
    id: "der-012",
    topic: "derivatives",
    difficulty: 4,
    prompt: "\\frac{d}{dx}\\left(\\frac{\\ln x}{x^2+1}\\right)",
    answerKind: "expression",
    answer: "((x^2+1)/x-2*x*log(x))/(x^2+1)^2",
    variable: "x",
    timeLimit: 70,
    tabLimit: 1,
    solution: "商法則。"
  },
  {
    id: "int-001",
    topic: "integrals",
    difficulty: 1,
    prompt: "\\int 6x^2\\,dx",
    answerKind: "antiderivative",
    answer: "2*x^3",
    variable: "x",
    timeLimit: 30,
    tabLimit: 2,
    solution: "次方積分公式。常數 C 可省略。"
  },
  {
    id: "int-002",
    topic: "integrals",
    difficulty: 1,
    prompt: "\\int \\cos x\\,dx",
    answerKind: "antiderivative",
    answer: "sin(x)",
    variable: "x",
    timeLimit: 25,
    tabLimit: 2,
    solution: "sin x 的導數是 cos x。"
  },
  {
    id: "int-003",
    topic: "integrals",
    difficulty: 1,
    prompt: "\\int \\frac{1}{x}\\,dx",
    answerKind: "antiderivative",
    answer: "log(abs(x))",
    variable: "x",
    timeLimit: 30,
    tabLimit: 2,
    solution: "基本積分為 ln|x|。"
  },
  {
    id: "int-004",
    topic: "integrals",
    difficulty: 1,
    prompt: "\\int e^{3x}\\,dx",
    answerKind: "antiderivative",
    answer: "exp(3*x)/3",
    variable: "x",
    timeLimit: 35,
    tabLimit: 2,
    solution: "鏈鎖律反向使用。"
  },
  {
    id: "int-005",
    topic: "integrals",
    difficulty: 2,
    prompt: "\\int x e^{x^2}\\,dx",
    answerKind: "antiderivative",
    answer: "exp(x^2)/2",
    variable: "x",
    timeLimit: 45,
    tabLimit: 2,
    solution: "令 u=x^2，du=2x dx。"
  },
  {
    id: "int-006",
    topic: "integrals",
    difficulty: 2,
    prompt: "\\int \\frac{2x}{1+x^2}\\,dx",
    answerKind: "antiderivative",
    answer: "log(1+x^2)",
    variable: "x",
    timeLimit: 40,
    tabLimit: 2,
    solution: "分子是分母導數。"
  },
  {
    id: "int-007",
    topic: "integrals",
    difficulty: 2,
    prompt: "\\int x\\cos(x^2)\\,dx",
    answerKind: "antiderivative",
    answer: "sin(x^2)/2",
    variable: "x",
    timeLimit: 45,
    tabLimit: 2,
    solution: "令 u=x^2。"
  },
  {
    id: "int-008",
    topic: "integrals",
    difficulty: 2,
    prompt: "\\int_0^1 3x^2\\,dx",
    answerKind: "numeric",
    answer: "1",
    timeLimit: 35,
    tabLimit: 2,
    solution: "原函數 x^3，代入 0 到 1。"
  },
  {
    id: "int-009",
    topic: "integrals",
    difficulty: 3,
    prompt: "\\int x\\ln x\\,dx",
    answerKind: "antiderivative",
    answer: "x^2*log(x)/2-x^2/4",
    variable: "x",
    timeLimit: 65,
    tabLimit: 1,
    solution: "分部積分，u=ln x，dv=x dx。"
  },
  {
    id: "int-010",
    topic: "integrals",
    difficulty: 3,
    prompt: "\\int \\sin^3 x\\,dx",
    answerKind: "antiderivative",
    answer: "-cos(x)+cos(x)^3/3",
    variable: "x",
    timeLimit: 70,
    tabLimit: 1,
    solution: "sin^3 x = sin x(1-cos^2 x)，令 u=cos x。"
  },
  {
    id: "int-011",
    topic: "integrals",
    difficulty: 3,
    prompt: "\\int \\frac{1}{x^2+4}\\,dx",
    answerKind: "antiderivative",
    answer: "atan(x/2)/2",
    variable: "x",
    timeLimit: 60,
    tabLimit: 1,
    solution: "套 arctan 形式。"
  },
  {
    id: "int-012",
    topic: "integrals",
    difficulty: 4,
    prompt: "\\int_0^{\\pi/2}\\sin^2 x\\,dx",
    answerKind: "numeric",
    answer: "pi/4",
    timeLimit: 70,
    tabLimit: 1,
    solution: "用 sin^2 x=(1-cos 2x)/2。"
  },
  {
    id: "ser-001",
    topic: "series",
    difficulty: 1,
    prompt: "\\sum_{n=1}^{\\infty}\\frac{1}{n^2}",
    answerKind: "text",
    answers: ["converges", "convergent", "收斂"],
    canonical: "收斂",
    timeLimit: 25,
    tabLimit: 2,
    solution: "p-series，p=2>1，所以收斂。"
  },
  {
    id: "ser-002",
    topic: "series",
    difficulty: 1,
    prompt: "\\sum_{n=1}^{\\infty}\\frac{1}{n}",
    answerKind: "text",
    answers: ["diverges", "divergent", "發散"],
    canonical: "發散",
    timeLimit: 25,
    tabLimit: 2,
    solution: "調和級數發散。"
  },
  {
    id: "ser-003",
    topic: "series",
    difficulty: 1,
    prompt: "\\sum_{n=0}^{\\infty}\\left(\\frac{1}{3}\\right)^n",
    answerKind: "numeric",
    answer: "3/2",
    timeLimit: 35,
    tabLimit: 2,
    solution: "等比級數，和為 1/(1-1/3)=3/2。"
  },
  {
    id: "ser-004",
    topic: "series",
    difficulty: 1,
    prompt: "\\sum_{n=1}^{\\infty}\\frac{(-1)^{n+1}}{n}",
    answerKind: "text",
    answers: ["conditionally converges", "conditional", "條件收斂"],
    canonical: "條件收斂",
    timeLimit: 35,
    tabLimit: 2,
    solution: "交錯調和級數條件收斂。"
  },
  {
    id: "ser-005",
    topic: "series",
    difficulty: 2,
    prompt: "\\sum_{n=1}^{\\infty}\\frac{n}{n^2+1}",
    answerKind: "text",
    answers: ["diverges", "divergent", "發散"],
    canonical: "發散",
    timeLimit: 45,
    tabLimit: 2,
    solution: "項行為像 1/n，和調和級數比較會發散。"
  },
  {
    id: "ser-006",
    topic: "series",
    difficulty: 2,
    prompt: "\\sum_{n=1}^{\\infty}\\frac{n!}{n^n}",
    answerKind: "text",
    answers: ["converges", "convergent", "收斂"],
    canonical: "收斂",
    timeLimit: 50,
    tabLimit: 2,
    solution: "比值測試極限趨近 e^{-1}<1。"
  },
  {
    id: "ser-007",
    topic: "series",
    difficulty: 2,
    prompt: "\\sum_{n=1}^{\\infty}\\frac{3^n}{n!}",
    answerKind: "numeric",
    answer: "exp(3)-1",
    timeLimit: 55,
    tabLimit: 2,
    solution: "e^3 的展開式少了 n=0 項。"
  },
  {
    id: "ser-008",
    topic: "series",
    difficulty: 2,
    prompt: "\\text{Radius of convergence of }\\sum_{n=0}^{\\infty}n!x^n",
    answerKind: "numeric",
    answer: "0",
    timeLimit: 45,
    tabLimit: 2,
    solution: "n! 成長太快，半徑為 0。"
  },
  {
    id: "ser-009",
    topic: "series",
    difficulty: 3,
    prompt: "\\text{Radius of convergence of }\\sum_{n=1}^{\\infty}\\frac{x^n}{n}",
    answerKind: "numeric",
    answer: "1",
    timeLimit: 45,
    tabLimit: 1,
    solution: "與 -ln(1-x) 的冪級數相同，半徑 1。"
  },
  {
    id: "ser-010",
    topic: "series",
    difficulty: 3,
    prompt: "\\sum_{n=1}^{\\infty}\\frac{(-1)^n}{\\sqrt n}",
    answerKind: "text",
    answers: ["conditionally converges", "conditional", "條件收斂"],
    canonical: "條件收斂",
    timeLimit: 45,
    tabLimit: 1,
    solution: "交錯級數收斂，但絕對值級數 p=1/2 發散。"
  },
  {
    id: "ser-011",
    topic: "series",
    difficulty: 3,
    prompt: "\\sum_{n=1}^{\\infty}\\frac{2^n+n}{3^n}",
    answerKind: "numeric",
    answer: "9/4",
    timeLimit: 70,
    tabLimit: 1,
    solution: "拆成 sum (2/3)^n 加 sum n(1/3)^n，分別是 2 和 3/4。"
  },
  {
    id: "ser-012",
    topic: "series",
    difficulty: 4,
    prompt: "\\sum_{n=1}^{\\infty}\\frac{1}{n(n+1)}",
    answerKind: "numeric",
    answer: "1",
    timeLimit: 60,
    tabLimit: 1,
    solution: "裂項：1/(n(n+1))=1/n-1/(n+1)。"
  },
  {
    id: "lim-013",
    topic: "limits",
    difficulty: 4,
    prompt: "\\lim_{x \\to 0}\\frac{\\tan x-\\sin x}{x^3}",
    answerKind: "numeric",
    answer: "1/2",
    timeLimit: 75,
    tabLimit: 1,
    solution: "tan x = x+x^3/3+...，sin x = x-x^3/6+...。"
  },
  {
    id: "lim-014",
    topic: "limits",
    difficulty: 4,
    prompt: "\\lim_{x \\to 0}\\frac{\\ln(1+x)-\\sin x}{x^2}",
    answerKind: "numeric",
    answer: "-1/2",
    timeLimit: 75,
    tabLimit: 1,
    solution: "二階項來自 ln(1+x) 的 -x^2/2。"
  },
  {
    id: "lim-015",
    topic: "limits",
    difficulty: 4,
    prompt: "\\lim_{x \\to 0}\\frac{\\sec x-1}{x^2}",
    answerKind: "numeric",
    answer: "1/2",
    timeLimit: 70,
    tabLimit: 1,
    solution: "sec x = 1+x^2/2+...。"
  },
  {
    id: "lim-016",
    topic: "limits",
    difficulty: 4,
    prompt: "\\lim_{x \\to \\infty}x\\left(\\sqrt{x^2+x}-x-\\frac12\\right)",
    answerKind: "numeric",
    answer: "-1/8",
    timeLimit: 90,
    tabLimit: 1,
    solution: "展開 sqrt(1+1/x)，下一項是 -1/(8x^2)。"
  },
  {
    id: "lim-017",
    topic: "limits",
    difficulty: 4,
    prompt: "\\lim_{x \\to 0}\\frac{e^x-e^{-x}-2x}{x^3}",
    answerKind: "numeric",
    answer: "1/3",
    timeLimit: 75,
    tabLimit: 1,
    solution: "e^x-e^{-x}=2x+x^3/3+...。"
  },
  {
    id: "lim-018",
    topic: "limits",
    difficulty: 4,
    prompt: "\\lim_{x \\to 0}\\frac{\\sin x-x\\cos x}{x^3}",
    answerKind: "numeric",
    answer: "1/3",
    timeLimit: 70,
    tabLimit: 1,
    solution: "sin x 與 x cos x 的三階項相減。"
  },
  {
    id: "lim-019",
    topic: "limits",
    difficulty: 4,
    prompt: "\\lim_{x \\to 0}\\frac{(1+x)^{1/x}-e}{x}",
    answerKind: "numeric",
    answer: "-e/2",
    timeLimit: 95,
    tabLimit: 1,
    solution: "(1+x)^{1/x}=e(1-x/2+...)。"
  },
  {
    id: "lim-020",
    topic: "limits",
    difficulty: 4,
    prompt: "\\lim_{x \\to 0}\\frac{\\arctan x-x}{x^3}",
    answerKind: "numeric",
    answer: "-1/3",
    timeLimit: 70,
    tabLimit: 1,
    solution: "arctan x = x-x^3/3+...。"
  },
  {
    id: "der-013",
    topic: "derivatives",
    difficulty: 4,
    prompt: "\\frac{d}{dx}\\left(x^{\\sin x}\\right)",
    answerKind: "expression",
    answer: "x^sin(x)*(cos(x)*log(x)+sin(x)/x)",
    variable: "x",
    timeLimit: 90,
    tabLimit: 1,
    solution: "對數微分：x^{sin x}=e^{sin x ln x}。"
  },
  {
    id: "der-014",
    topic: "derivatives",
    difficulty: 4,
    prompt: "\\frac{d}{dx}\\left(\\arctan\\frac{1+x}{1-x}\\right)",
    answerKind: "expression",
    answer: "1/(1+x^2)",
    variable: "x",
    timeLimit: 85,
    tabLimit: 1,
    solution: "令 u=(1+x)/(1-x)，套 arctan 鏈鎖律後會大幅化簡。"
  },
  {
    id: "der-015",
    topic: "derivatives",
    difficulty: 4,
    prompt: "\\frac{d}{dx}\\left(\\ln\\left(x+\\sqrt{1+x^2}\\right)\\right)",
    answerKind: "expression",
    answer: "1/sqrt(1+x^2)",
    variable: "x",
    timeLimit: 75,
    tabLimit: 1,
    solution: "這是 asinh x 的導數。"
  },
  {
    id: "der-016",
    topic: "derivatives",
    difficulty: 4,
    prompt: "\\frac{d}{dx}\\left(\\frac{\\sin x}{1+\\cos x}\\right)",
    answerKind: "expression",
    answer: "1/(1+cos(x))",
    variable: "x",
    timeLimit: 80,
    tabLimit: 1,
    solution: "商法則後分子化成 1+cos x。"
  },
  {
    id: "der-017",
    topic: "derivatives",
    difficulty: 4,
    prompt: "\\frac{d}{dx}\\left(e^{x^2}\\cos(3x)\\right)",
    answerKind: "expression",
    answer: "exp(x^2)*(2*x*cos(3*x)-3*sin(3*x))",
    variable: "x",
    timeLimit: 80,
    tabLimit: 1,
    solution: "乘法法則加兩個鏈鎖律。"
  },
  {
    id: "der-018",
    topic: "derivatives",
    difficulty: 4,
    prompt: "\\frac{d}{dx}\\left(\\ln\\left(x+\\sqrt{x^2-1}\\right)\\right)",
    answerKind: "expression",
    answer: "1/sqrt(x^2-1)",
    variable: "x",
    timeLimit: 80,
    tabLimit: 1,
    solution: "這是 arcosh x 的導數形式。"
  },
  {
    id: "der-019",
    topic: "derivatives",
    difficulty: 4,
    prompt: "\\frac{d}{dx}\\left((x^2+1)^5\\right)",
    answerKind: "expression",
    answer: "10*x*(x^2+1)^4",
    variable: "x",
    timeLimit: 55,
    tabLimit: 1,
    solution: "鏈鎖律。"
  },
  {
    id: "der-020",
    topic: "derivatives",
    difficulty: 4,
    prompt: "\\frac{d}{dx}\\left(\\arctan\\sqrt{x}\\right)",
    answerKind: "expression",
    answer: "1/(2*sqrt(x)*(1+x))",
    variable: "x",
    timeLimit: 75,
    tabLimit: 1,
    solution: "先對 arctan u 微分，再乘上 sqrt x 的導數。"
  },
  {
    id: "int-013",
    topic: "integrals",
    difficulty: 4,
    prompt: "\\int (\\ln x)^2\\,dx",
    answerKind: "antiderivative",
    answer: "x*(log(x)^2-2*log(x)+2)",
    variable: "x",
    timeLimit: 100,
    tabLimit: 1,
    solution: "分部積分兩次。"
  },
  {
    id: "int-014",
    topic: "integrals",
    difficulty: 4,
    prompt: "\\int \\frac{x^3}{x^2+1}\\,dx",
    answerKind: "antiderivative",
    answer: "x^2/2-log(x^2+1)/2",
    variable: "x",
    timeLimit: 85,
    tabLimit: 1,
    solution: "先做多項式除法：x^3/(x^2+1)=x-x/(x^2+1)。"
  },
  {
    id: "int-015",
    topic: "integrals",
    difficulty: 4,
    prompt: "\\int e^x\\sin x\\,dx",
    answerKind: "antiderivative",
    answer: "exp(x)*(sin(x)-cos(x))/2",
    variable: "x",
    timeLimit: 95,
    tabLimit: 1,
    solution: "分部積分兩次，或猜 e^x(a sin x+b cos x)。"
  },
  {
    id: "int-016",
    topic: "integrals",
    difficulty: 4,
    prompt: "\\int_0^1 \\ln(1+x)\\,dx",
    answerKind: "numeric",
    answer: "2*log(2)-1",
    timeLimit: 85,
    tabLimit: 1,
    solution: "原函數是 (1+x)ln(1+x)-(1+x)。"
  },
  {
    id: "int-017",
    topic: "integrals",
    difficulty: 4,
    prompt: "\\int_0^{\\pi/2}x\\sin x\\,dx",
    answerKind: "numeric",
    answer: "1",
    timeLimit: 80,
    tabLimit: 1,
    solution: "分部積分，邊界項留下 1。"
  },
  {
    id: "int-018",
    topic: "integrals",
    difficulty: 4,
    prompt: "\\int \\frac{\\sin x}{1+\\cos x}\\,dx",
    answerKind: "antiderivative",
    answer: "-log(1+cos(x))",
    variable: "x",
    timeLimit: 70,
    tabLimit: 1,
    solution: "令 u=1+cos x，du=-sin x dx。"
  },
  {
    id: "int-019",
    topic: "integrals",
    difficulty: 4,
    prompt: "\\int \\frac{1}{1+\\sqrt{x}}\\,dx",
    answerKind: "antiderivative",
    answer: "2*sqrt(x)-2*log(1+sqrt(x))",
    variable: "x",
    timeLimit: 100,
    tabLimit: 1,
    solution: "令 u=sqrt x，dx=2u du。"
  },
  {
    id: "int-020",
    topic: "integrals",
    difficulty: 4,
    prompt: "\\int_0^1\\frac{x^2}{1+x^3}\\,dx",
    answerKind: "numeric",
    answer: "log(2)/3",
    timeLimit: 70,
    tabLimit: 1,
    solution: "令 u=1+x^3。"
  },
  {
    id: "ser-013",
    topic: "series",
    difficulty: 4,
    prompt: "\\sum_{n=1}^{\\infty}(-1)^n\\frac{n}{n+1}",
    answerKind: "text",
    answers: ["diverges", "divergent", "發散"],
    canonical: "發散",
    timeLimit: 55,
    tabLimit: 1,
    solution: "通項不趨近 0，所以級數發散。"
  },
  {
    id: "ser-014",
    topic: "series",
    difficulty: 4,
    prompt: "\\sum_{n=1}^{\\infty}\\frac{n}{2^n}",
    answerKind: "numeric",
    answer: "2",
    timeLimit: 55,
    tabLimit: 1,
    solution: "公式 sum n r^n = r/(1-r)^2，取 r=1/2。"
  },
  {
    id: "ser-015",
    topic: "series",
    difficulty: 4,
    prompt: "\\sum_{n=1}^{\\infty}\\frac{n^2}{2^n}",
    answerKind: "numeric",
    answer: "6",
    timeLimit: 70,
    tabLimit: 1,
    solution: "公式 sum n^2 r^n = r(1+r)/(1-r)^3，取 r=1/2。"
  },
  {
    id: "ser-016",
    topic: "series",
    difficulty: 4,
    prompt: "\\sum_{n=1}^{\\infty}\\frac{(n!)^2}{(2n)!}",
    answerKind: "text",
    answers: ["converges", "convergent", "收斂"],
    canonical: "收斂",
    timeLimit: 70,
    tabLimit: 1,
    solution: "這是中央二項係數倒數量級，指數衰減所以收斂。"
  },
  {
    id: "ser-017",
    topic: "series",
    difficulty: 4,
    prompt: "\\text{Radius of convergence of }\\sum_{n=1}^{\\infty}\\frac{n^2x^n}{3^n}",
    answerKind: "numeric",
    answer: "3",
    timeLimit: 60,
    tabLimit: 1,
    solution: "n^2 不影響收斂半徑，核心比例是 |x|/3。"
  },
  {
    id: "ser-018",
    topic: "series",
    difficulty: 4,
    prompt: "\\sum_{n=1}^{\\infty}\\frac{(-1)^n}{n^2}",
    answerKind: "text",
    answers: ["absolutely converges", "absolute", "絕對收斂"],
    canonical: "絕對收斂",
    timeLimit: 45,
    tabLimit: 1,
    solution: "取絕對值後是 p-series，p=2>1。"
  },
  {
    id: "ser-019",
    topic: "series",
    difficulty: 4,
    prompt: "\\sum_{n=1}^{\\infty}\\frac{1}{n(n+2)}",
    answerKind: "numeric",
    answer: "3/4",
    timeLimit: 75,
    tabLimit: 1,
    solution: "裂項成 1/2(1/n-1/(n+2))。"
  },
  {
    id: "ser-020",
    topic: "series",
    difficulty: 4,
    prompt: "\\sum_{n=2}^{\\infty}\\frac{\\ln n}{n}",
    answerKind: "text",
    answers: ["diverges", "divergent", "發散"],
    canonical: "發散",
    timeLimit: 60,
    tabLimit: 1,
    solution: "用積分測試，int (ln x)/x dx 發散。"
  },
  {
    id: "td-lim-001",
    topic: "limits",
    difficulty: 4,
    source: "東大",
    prompt: "\\lim_{n\\to\\infty}\\prod_{k=1}^{n}\\left(1+\\frac{k}{n^2}\\right)",
    answerKind: "numeric",
    answer: "exp(1/2)",
    timeLimit: 90,
    tabLimit: 1,
    solution: "取 log 後，sum k/n^2 趨近 1/2，其餘高階項趨近 0。"
  },
  {
    id: "td-lim-002",
    topic: "limits",
    difficulty: 4,
    source: "東大",
    prompt: "\\lim_{n\\to\\infty}n\\left(\\prod_{k=1}^{n}\\left(1+\\frac{k}{n^2}\\right)-\\sqrt e\\right)",
    answerKind: "numeric",
    answer: "sqrt(e)/3",
    timeLimit: 120,
    tabLimit: 1,
    solution: "把 log 展開到 1/n 項：log P_n=1/2+1/(3n)+O(1/n^2)。"
  },
  {
    id: "td-lim-004",
    topic: "limits",
    difficulty: 4,
    source: "東大",
    prompt: "\\lim_{x\\to0}\\frac{(1+x)^x-1-x^2}{x^3}",
    answerKind: "numeric",
    answer: "-1/2",
    timeLimit: 80,
    tabLimit: 1,
    solution: "(1+x)^x=exp(x log(1+x))=1+x^2-x^3/2+...。"
  },
  {
    id: "td-der-001",
    topic: "derivatives",
    difficulty: 4,
    source: "東大",
    prompt: "\\frac{d^3}{dx^3}\\arctan\\frac1x",
    answerKind: "expression",
    answer: "2*(1-3*x^2)/(1+x^2)^3",
    variable: "x",
    timeLimit: 100,
    tabLimit: 1,
    solution: "先算 y'=-1/(1+x^2)，再連續微分兩次。"
  },
  {
    id: "td-der-002",
    topic: "derivatives",
    difficulty: 4,
    source: "東大",
    prompt: "\\frac{d}{dx}\\left[\\frac{1}{8}(35x^4-30x^2+3)\\right]",
    answerKind: "expression",
    answer: "(35*x^3-15*x)/2",
    variable: "x",
    timeLimit: 60,
    tabLimit: 1,
    solution: "這是 Legendre P_4 的導數，逐項微分即可。"
  },
  {
    id: "td-der-003",
    topic: "derivatives",
    difficulty: 4,
    source: "東大",
    prompt: "\\frac{d}{dx}\\left(x\\log(1+x)\\right)",
    answerKind: "expression",
    answer: "log(1+x)+x/(1+x)",
    variable: "x",
    timeLimit: 55,
    tabLimit: 1,
    solution: "乘法法則。這也是展開 (1+x)^x 時會出現的核心項。"
  },
  {
    id: "td-der-004",
    topic: "derivatives",
    difficulty: 4,
    source: "東大",
    prompt: "\\frac{d}{dx}\\left(\\log(5+3\\cos x)\\right)",
    answerKind: "expression",
    answer: "-3*sin(x)/(5+3*cos(x))",
    variable: "x",
    timeLimit: 50,
    tabLimit: 1,
    solution: "鏈鎖律，內層導數是 -3 sin x。"
  },
  {
    id: "td-int-001",
    topic: "integrals",
    difficulty: 4,
    source: "東大",
    prompt: "\\int_0^{\\infty}\\frac{\\cos(3x)}{1+x^2}\\,dx",
    answerKind: "numeric",
    answer: "pi*exp(-3)/2",
    timeLimit: 95,
    tabLimit: 1,
    solution: "使用 Fourier transform 型公式：int_0^infty cos(tx)/(1+x^2) dx = pi e^{-|t|}/2。"
  },
  {
    id: "td-int-002",
    topic: "integrals",
    difficulty: 4,
    source: "東大",
    prompt: "\\int_0^{\\pi}\\log(5+3\\cos x)\\,dx",
    answerKind: "numeric",
    answer: "pi*log(9/2)",
    timeLimit: 100,
    tabLimit: 1,
    solution: "套公式 int_0^pi log(a+b cos x) dx = pi log((a+sqrt(a^2-b^2))/2)。"
  },
  {
    id: "td-int-003",
    topic: "integrals",
    difficulty: 4,
    source: "東大",
    prompt: "\\int_0^{\\infty}\\frac{e^{-5x}-e^{-2x}}{x}\\,dx",
    answerKind: "numeric",
    answer: "log(2/5)",
    timeLimit: 85,
    tabLimit: 1,
    solution: "Frullani 公式：int_0^infty (e^{-alpha x}-e^{-beta x})/x dx = log(beta/alpha)。"
  },
  {
    id: "td-int-004",
    topic: "integrals",
    difficulty: 4,
    source: "東大",
    prompt: "\\int_0^{\\infty}\\frac{\\sin(2x)\\sin(5x)}{x}\\,dx",
    answerKind: "numeric",
    answer: "log(7/3)/2",
    timeLimit: 100,
    tabLimit: 1,
    solution: "用 2 sin A sin B = cos(A-B)-cos(A+B)，再套 Frullani 型結果。"
  },
  {
    id: "td-int-005",
    topic: "integrals",
    difficulty: 4,
    source: "東大",
    prompt: "\\text{Area of }3x^2+2xy+2y^2\\le1",
    answerKind: "numeric",
    answer: "pi/sqrt(5)",
    timeLimit: 80,
    tabLimit: 1,
    solution: "二次型矩陣 [[3,1],[1,2]] 的行列式為 5，面積是 pi/sqrt(det A)。"
  },
  {
    id: "td-int-006",
    topic: "integrals",
    difficulty: 4,
    source: "東大",
    prompt: "\\int_{-\\infty}^{\\infty}x^4e^{-3x^2}\\,dx",
    answerKind: "numeric",
    answer: "sqrt(pi)/(12*sqrt(3))",
    timeLimit: 90,
    tabLimit: 1,
    solution: "高斯積分偶次矩：int x^{2m}e^{-a x^2} dx=(2m-1)!! sqrt(pi)/(2^m a^{m+1/2})。"
  },
  {
    id: "td-ser-001",
    topic: "series",
    difficulty: 4,
    source: "東大",
    prompt: "\\text{Coefficient of }x^6\\text{ in }(1+x)^x",
    answerKind: "numeric",
    answer: "33/40",
    timeLimit: 100,
    tabLimit: 1,
    solution: "令 (1+x)^x=exp(x log(1+x))，展開到 x^6。"
  },
  {
    id: "td-ser-002",
    topic: "series",
    difficulty: 4,
    source: "東大",
    prompt: "\\text{Coefficient of }x^5\\text{ in }e^{2\\arcsin x}",
    answerKind: "numeric",
    answer: "13/12",
    timeLimit: 110,
    tabLimit: 1,
    solution: "arcsin x=x+x^3/6+3x^5/40+...，再取 exp。"
  },
  {
    id: "td-ser-003",
    topic: "series",
    difficulty: 4,
    source: "東大",
    prompt: "\\sum_{n=1}^{\\infty}\\frac{(2n-1)!!}{(2n)!!}\\cdot\\frac1n",
    answerKind: "numeric",
    answer: "2*log(2)",
    timeLimit: 105,
    tabLimit: 1,
    solution: "用 int_0^{pi/2} sin^{2n}x dx 表示雙階乘比，再交換求和。"
  },
];
