(function () {
  "use strict";

  const extraProblems = [
    {
      id: "lim-021",
      topic: "limits",
      difficulty: 2,
      source: "Buzz original",
      prompt: "\\lim_{x\\to0}\\frac{\\tan x-x}{x^3}",
      answerKind: "numeric",
      answer: "1/3",
      timeLimit: 55,
      tabLimit: 1,
      tags: ["taylor", "trig-limit"],
      hints: ["把 tan x 展開到 x^3。", "tan x = x + x^3/3 + O(x^5)。", "最低非零項決定極限。"],
      solution: "tan x = x + x^3/3 + O(x^5)，所以分子約為 x^3/3，極限為 1/3。"
    },
    {
      id: "lim-022",
      topic: "limits",
      difficulty: 2,
      source: "Buzz original",
      prompt: "\\lim_{x\\to\\infty}\\left(\\sqrt{x^2+3x}-x\\right)",
      answerKind: "numeric",
      answer: "3/2",
      timeLimit: 55,
      tabLimit: 1,
      tags: ["rationalize", "infinity"],
      hints: ["先有理化。", "分母會變成 sqrt(x^2+3x)+x。", "上下同除以 x。"],
      solution: "有理化後為 3x/(sqrt(x^2+3x)+x)，上下同除以 x 得 3/(sqrt(1+3/x)+1)，極限為 3/2。"
    },
    {
      id: "lim-023",
      topic: "limits",
      difficulty: 2,
      source: "Buzz original",
      prompt: "\\lim_{x\\to0}\\frac{e^{2x}-1-2x}{x^2}",
      answerKind: "numeric",
      answer: "2",
      timeLimit: 50,
      tabLimit: 1,
      tags: ["taylor", "exponential"],
      hints: ["展開 e^{2x} 到二次項。", "e^{2x}=1+2x+2x^2+O(x^3)。", "一次項會被扣掉。"],
      solution: "e^{2x}=1+2x+2x^2+O(x^3)，分子為 2x^2+O(x^3)，所以極限為 2。"
    },
    {
      id: "lim-024",
      topic: "limits",
      difficulty: 2,
      source: "Buzz original",
      prompt: "\\lim_{x\\to0}\\frac{\\log(1+x)-x}{x^2}",
      answerKind: "numeric",
      answer: "-1/2",
      timeLimit: 50,
      tabLimit: 1,
      tags: ["taylor", "log"],
      hints: ["使用 log(1+x) 的展開。", "log(1+x)=x-x^2/2+O(x^3)。", "扣掉 x 後看二次項。"],
      solution: "log(1+x)=x-x^2/2+O(x^3)，分子為 -x^2/2+O(x^3)，極限為 -1/2。"
    },
    {
      id: "lim-025",
      topic: "limits",
      difficulty: 2,
      source: "Buzz original",
      prompt: "\\lim_{(x,y)\\to(0,0)}\\frac{\\sin(xy)}{xy}",
      answerKind: "numeric",
      answer: "1",
      timeLimit: 55,
      tabLimit: 1,
      tags: ["multivariable", "standard-limit"],
      hints: ["把 xy 視為一個整體變數。", "令 u=xy，當 (x,y)->(0,0) 時 u->0。", "使用 sin u / u -> 1。"],
      solution: "令 u=xy，則 u->0，標準極限 sin u/u = 1。"
    },
    {
      id: "lim-026",
      topic: "limits",
      difficulty: 3,
      source: "Buzz original",
      prompt: "\\lim_{(x,y)\\to(0,0)}\\frac{x^2y}{x^2+y^2}",
      answerKind: "numeric",
      answer: "0",
      timeLimit: 70,
      tabLimit: 1,
      tags: ["multivariable", "squeeze"],
      hints: ["用極座標估計階數。", "分子是三次階，分母是二次階。", "整體大小被常數乘 r 控住。"],
      solution: "令 x=r cos theta, y=r sin theta，原式 = r cos^2 theta sin theta，當 r->0 時趨近 0。"
    },
    {
      id: "lim-027",
      topic: "limits",
      difficulty: 3,
      source: "Buzz original",
      prompt: "\\lim_{(x,y)\\to(0,0)}\\frac{xy}{x^2+y^2}",
      answerKind: "numeric",
      answer: "dne",
      timeLimit: 70,
      tabLimit: 1,
      tags: ["multivariable", "path-test", "dne"],
      hints: ["試兩條不同路徑。", "沿 y=x 與 y=-x 比較。", "如果結果不同，極限不存在。"],
      solution: "沿 y=x 得 1/2；沿 y=-x 得 -1/2。路徑極限不同，所以 DNE。"
    },
    {
      id: "lim-028",
      topic: "limits",
      difficulty: 3,
      source: "Buzz original",
      prompt: "\\lim_{(x,y)\\to(0,0)}\\frac{\\sqrt{1+x^2+y^2}-1}{x^2+y^2}",
      answerKind: "numeric",
      answer: "1/2",
      timeLimit: 75,
      tabLimit: 1,
      tags: ["multivariable", "rationalize"],
      hints: ["設 r^2=x^2+y^2。", "有理化分子。", "分母會出現 sqrt(1+r^2)+1。"],
      solution: "設 r^2=x^2+y^2。有理化後為 1/(sqrt(1+r^2)+1)，令 r->0 得 1/2。"
    },
    {
      id: "lim-029",
      topic: "limits",
      difficulty: 2,
      source: "Buzz original",
      prompt: "\\lim_{(x,y)\\to(0,0)}\\frac{x^4+y^4}{x^2+y^2}",
      answerKind: "numeric",
      answer: "0",
      timeLimit: 60,
      tabLimit: 1,
      tags: ["multivariable", "squeeze"],
      hints: ["分子是四次階，分母是二次階。", "用 x^4+y^4 <= (x^2+y^2)^2。", "因此原式被 x^2+y^2 控住。"],
      solution: "因 x^4+y^4 <= (x^2+y^2)^2，所以原式 <= x^2+y^2，極限為 0。"
    },
    {
      id: "lim-030",
      topic: "limits",
      difficulty: 2,
      source: "Buzz original",
      prompt: "\\lim_{x\\to0}\\frac{1-\\cos(3x)}{x^2}",
      answerKind: "numeric",
      answer: "9/2",
      timeLimit: 50,
      tabLimit: 1,
      tags: ["standard-limit", "trig-limit"],
      hints: ["使用 1-cos u ~ u^2/2。", "令 u=3x。", "注意係數平方。"],
      solution: "1-cos(3x) ~ (3x)^2/2，所以極限為 9/2。"
    },
    {
      id: "der-021",
      topic: "derivatives",
      difficulty: 2,
      source: "Buzz original",
      prompt: "\\frac{\\partial}{\\partial x}\\left(x^2y+\\sin(xy)\\right)",
      answerKind: "expression",
      answer: "2*x*y+y*cos(x*y)",
      variables: ["x", "y"],
      timeLimit: 65,
      tabLimit: 1,
      tags: ["multivariable", "partial-derivative", "chain-rule"],
      hints: ["對 x 微分時，把 y 當常數。", "sin(xy) 要用鏈鎖律。", "xy 對 x 的導數是 y。"],
      solution: "偏 x 微分得 2xy + cos(xy)*y。"
    },
    {
      id: "der-022",
      topic: "derivatives",
      difficulty: 2,
      source: "Buzz original",
      prompt: "\\frac{\\partial}{\\partial y}\\left(xe^{xy}+y^3\\right)",
      answerKind: "expression",
      answer: "x^2*exp(x*y)+3*y^2",
      variables: ["x", "y"],
      timeLimit: 65,
      tabLimit: 1,
      tags: ["multivariable", "partial-derivative", "chain-rule"],
      hints: ["對 y 微分時，把 x 當常數。", "e^{xy} 的內層 xy 對 y 導數為 x。", "外面的 x 也要保留。"],
      solution: "d/dy of x e^{xy} = x*e^{xy}*x = x^2 e^{xy}，再加 3y^2。"
    },
    {
      id: "der-023",
      topic: "derivatives",
      difficulty: 3,
      source: "Buzz original",
      prompt: "\\frac{\\partial^2}{\\partial x\\partial y}e^{xy}",
      answerKind: "expression",
      answer: "exp(x*y)*(1+x*y)",
      variables: ["x", "y"],
      timeLimit: 70,
      tabLimit: 1,
      tags: ["multivariable", "mixed-partial", "chain-rule"],
      hints: ["先對 y 微分，再對 x 微分。", "對 y 微分後得到 x e^{xy}。", "再對 x 用乘法律。"],
      solution: "先得 f_y=x e^{xy}，再對 x 微分為 e^{xy}+xy e^{xy}=e^{xy}(1+xy)。"
    },
    {
      id: "der-024",
      topic: "derivatives",
      difficulty: 3,
      source: "Buzz original",
      prompt: "\\text{Directional derivative of }f=x^2+y^2\\text{ at }(1,2)\\text{ in direction }(3,4)/5",
      answerKind: "numeric",
      answer: "22/5",
      timeLimit: 75,
      tabLimit: 1,
      tags: ["multivariable", "directional-derivative", "gradient"],
      hints: ["先求梯度。", "grad f(1,2)=(2,4)。", "方向導數是梯度與單位方向內積。"],
      solution: "grad f=(2x,2y)，在 (1,2) 為 (2,4)。與 (3/5,4/5) 內積得 22/5。"
    },
    {
      id: "der-025",
      topic: "derivatives",
      difficulty: 2,
      source: "Buzz original",
      prompt: "\\frac{\\partial}{\\partial x}\\log(x^2+y^2)",
      answerKind: "expression",
      answer: "2*x/(x^2+y^2)",
      variables: ["x", "y"],
      timeLimit: 60,
      tabLimit: 1,
      tags: ["multivariable", "partial-derivative", "log"],
      hints: ["log u 的導數是 u'/u。", "u=x^2+y^2。", "對 x 微分時 y^2 是常數。"],
      solution: "令 u=x^2+y^2，u_x=2x，所以 f_x=2x/(x^2+y^2)。"
    },
    {
      id: "der-026",
      topic: "derivatives",
      difficulty: 2,
      source: "Buzz original",
      prompt: "\\frac{d}{dx}\\left(x^2\\sin(3x)\\right)",
      answerKind: "expression",
      answer: "2*x*sin(3*x)+3*x^2*cos(3*x)",
      timeLimit: 55,
      tabLimit: 1,
      tags: ["product-rule", "chain-rule"],
      hints: ["同時用乘法律與鏈鎖律。", "x^2 微分是 2x。", "sin(3x) 微分是 3cos(3x)。"],
      solution: "乘法律給 2x sin(3x)+x^2*3cos(3x)。"
    },
    {
      id: "der-027",
      topic: "derivatives",
      difficulty: 2,
      source: "Buzz original",
      prompt: "\\frac{d}{dx}\\log\\sqrt{1+x^2}",
      answerKind: "expression",
      answer: "x/(1+x^2)",
      timeLimit: 55,
      tabLimit: 1,
      tags: ["log", "chain-rule"],
      hints: ["先把 log sqrt 改寫。", "log sqrt(1+x^2)=1/2 log(1+x^2)。", "再用鏈鎖律。"],
      solution: "原式為 (1/2)log(1+x^2)，微分得 x/(1+x^2)。"
    },
    {
      id: "der-028",
      topic: "derivatives",
      difficulty: 2,
      source: "Buzz original",
      prompt: "\\frac{d}{dx}\\arctan(e^x)",
      answerKind: "expression",
      answer: "exp(x)/(1+exp(2*x))",
      timeLimit: 60,
      tabLimit: 1,
      tags: ["inverse-trig", "chain-rule"],
      hints: ["arctan u 的導數是 u'/(1+u^2)。", "令 u=e^x。", "u'=e^x。"],
      solution: "由鏈鎖律得 e^x/(1+e^{2x})。"
    },
    {
      id: "der-029",
      topic: "derivatives",
      difficulty: 2,
      source: "Buzz original",
      prompt: "\\frac{d^2}{dx^2}\\left(xe^x\\right)",
      answerKind: "expression",
      answer: "exp(x)*(x+2)",
      timeLimit: 60,
      tabLimit: 1,
      tags: ["second-derivative", "product-rule"],
      hints: ["先微分一次。", "第一次微分是 e^x(x+1)。", "再用乘法律微分一次。"],
      solution: "f'=e^x(x+1)，f''=e^x(x+1)+e^x=e^x(x+2)。"
    },
    {
      id: "der-030",
      topic: "derivatives",
      difficulty: 3,
      source: "Buzz original",
      prompt: "\\text{Find }y'\\text{ from }x^2+xy+y^2=7",
      answerKind: "expression",
      answer: "-(2*x+y)/(x+2*y)",
      variables: ["x", "y"],
      timeLimit: 80,
      tabLimit: 1,
      tags: ["implicit-differentiation"],
      hints: ["把 y 視為 x 的函數。", "xy 微分是 y + x y'。", "把含 y' 的項移到同一邊。"],
      solution: "微分得 2x+y+xy'+2yy'=0，所以 y'=-(2x+y)/(x+2y)。"
    },
    {
      id: "int-021",
      topic: "integrals",
      difficulty: 2,
      source: "Buzz original",
      prompt: "\\int_0^1\\int_0^1(x+y)\\,dy\\,dx",
      answerKind: "numeric",
      answer: "1",
      timeLimit: 60,
      tabLimit: 1,
      tags: ["multivariable", "double-integral"],
      hints: ["先對 y 積分。", "內積分結果是 x+1/2。", "再對 x 從 0 到 1 積分。"],
      solution: "內積分為 x+1/2，外積分為 1/2+1/2=1。"
    },
    {
      id: "int-022",
      topic: "integrals",
      difficulty: 2,
      source: "Buzz original",
      prompt: "\\iint_D1\\,dA,\\quad D=\\{x\\ge0,y\\ge0,x+y\\le2\\}",
      answerKind: "numeric",
      answer: "2",
      timeLimit: 55,
      tabLimit: 1,
      tags: ["multivariable", "area", "double-integral"],
      hints: ["這是求三角形面積。", "截距都是 2。", "面積是 1/2*2*2。"],
      solution: "D 是直角三角形，兩股長皆為 2，面積為 2。"
    },
    {
      id: "int-023",
      topic: "integrals",
      difficulty: 2,
      source: "Buzz original",
      prompt: "\\int_0^1\\int_0^x xy\\,dy\\,dx",
      answerKind: "numeric",
      answer: "1/8",
      timeLimit: 65,
      tabLimit: 1,
      tags: ["multivariable", "double-integral"],
      hints: ["先對 y 積分。", "x 在內積分中是常數。", "得到 x^3/2 後再積分。"],
      solution: "內積分為 x*y^2/2|_0^x=x^3/2，外積分得 1/8。"
    },
    {
      id: "int-024",
      topic: "integrals",
      difficulty: 2,
      source: "Buzz original",
      prompt: "\\int_0^1\\int_0^{1-x}(x+y)\\,dy\\,dx",
      answerKind: "numeric",
      answer: "1/3",
      timeLimit: 70,
      tabLimit: 1,
      tags: ["multivariable", "double-integral", "triangle"],
      hints: ["積分區域是單位三角形。", "先對 y 積分。", "化簡後會得到 (1-x^2)/2。"],
      solution: "內積分為 x(1-x)+(1-x)^2/2=(1-x^2)/2，外積分得 1/3。"
    },
    {
      id: "int-025",
      topic: "integrals",
      difficulty: 3,
      source: "Buzz original",
      prompt: "\\iint_{x^2+y^2\\le1}(x^2+y^2)\\,dA",
      answerKind: "numeric",
      answer: "pi/2",
      timeLimit: 75,
      tabLimit: 1,
      tags: ["multivariable", "polar-coordinates", "double-integral"],
      hints: ["改用極座標。", "x^2+y^2=r^2，dA=r dr dtheta。", "積分 r^3。"],
      solution: "極座標下為 int_0^{2pi} int_0^1 r^3 dr dtheta = 2pi*(1/4)=pi/2。"
    },
    {
      id: "int-026",
      topic: "integrals",
      difficulty: 2,
      source: "Buzz original",
      prompt: "\\int_0^2\\int_0^3 xy\\,dy\\,dx",
      answerKind: "numeric",
      answer: "9",
      timeLimit: 55,
      tabLimit: 1,
      tags: ["multivariable", "double-integral", "separable"],
      hints: ["矩形區域上 xy 可分離。", "等於 int_0^2 x dx 乘 int_0^3 y dy。", "兩者分別是 2 與 9/2。"],
      solution: "分離為 (int_0^2 x dx)(int_0^3 y dy)=2*(9/2)=9。"
    },
    {
      id: "int-027",
      topic: "integrals",
      difficulty: 2,
      source: "Buzz original",
      prompt: "\\int \\frac{x}{1+x^2}\\,dx",
      answerKind: "antiderivative",
      answer: "log(1+x^2)/2",
      timeLimit: 55,
      tabLimit: 1,
      tags: ["substitution", "log"],
      hints: ["令 u=1+x^2。", "du=2x dx。", "差一個 1/2。"],
      solution: "u=1+x^2，積分為 (1/2)log(1+x^2)。"
    },
    {
      id: "int-028",
      topic: "integrals",
      difficulty: 2,
      source: "Buzz original",
      prompt: "\\int \\log x\\,dx",
      answerKind: "antiderivative",
      answer: "x*log(x)-x",
      timeLimit: 60,
      tabLimit: 1,
      tags: ["integration-by-parts", "log"],
      hints: ["用分部積分。", "取 u=log x，dv=dx。", "du=1/x dx，v=x。"],
      solution: "分部積分得 x log x - int 1 dx = x log x - x。"
    },
    {
      id: "int-029",
      topic: "integrals",
      difficulty: 2,
      source: "Buzz original",
      prompt: "\\int \\frac{1}{x^2+9}\\,dx",
      answerKind: "antiderivative",
      answer: "atan(x/3)/3",
      timeLimit: 55,
      tabLimit: 1,
      tags: ["inverse-trig", "standard-integral"],
      hints: ["辨認 arctan 型。", "公式 int dx/(x^2+a^2)=atan(x/a)/a。", "這裡 a=3。"],
      solution: "由標準公式得 (1/3)atan(x/3)。"
    },
    {
      id: "int-030",
      topic: "integrals",
      difficulty: 2,
      source: "Buzz original",
      prompt: "\\int_0^{\\pi/2}\\sin^3x\\cos x\\,dx",
      answerKind: "numeric",
      answer: "1/4",
      timeLimit: 55,
      tabLimit: 1,
      tags: ["substitution", "definite-integral"],
      hints: ["令 u=sin x。", "du=cos x dx。", "上下限從 0 到 1。"],
      solution: "令 u=sin x，積分變成 int_0^1 u^3 du = 1/4。"
    },
    {
      id: "ser-021",
      topic: "series",
      difficulty: 2,
      source: "Buzz original",
      prompt: "\\sum_{n=1}^{\\infty}\\frac{1}{n(n+1)}",
      answerKind: "numeric",
      answer: "1",
      timeLimit: 55,
      tabLimit: 1,
      tags: ["telescoping"],
      hints: ["做部分分式。", "1/(n(n+1))=1/n-1/(n+1)。", "級數會望遠鏡相消。"],
      solution: "部分分式後相消，部分和為 1-1/(N+1)，極限為 1。"
    },
    {
      id: "ser-022",
      topic: "series",
      difficulty: 2,
      source: "Buzz original",
      prompt: "\\sum_{n=1}^{\\infty}\\frac{n}{2^n}",
      answerKind: "numeric",
      answer: "2",
      timeLimit: 55,
      tabLimit: 1,
      tags: ["power-series", "geometric-derivative"],
      hints: ["使用公式 sum n r^n。", "公式為 r/(1-r)^2。", "代 r=1/2。"],
      solution: "sum n r^n = r/(1-r)^2，代 r=1/2 得 2。"
    },
    {
      id: "ser-023",
      topic: "series",
      difficulty: 2,
      source: "Buzz original",
      prompt: "\\sum_{n=1}^{\\infty}\\frac{(-1)^{n+1}}{n}",
      answerKind: "text",
      answers: ["conditionally converges", "conditional", "條件收斂"],
      canonical: "條件收斂",
      timeLimit: 55,
      tabLimit: 1,
      tags: ["alternating-series", "conditional-convergence"],
      hints: ["這是交錯調和級數。", "交錯級數判別可得收斂。", "絕對值後是調和級數，會發散。"],
      solution: "交錯調和級數收斂，但絕對值級數 sum 1/n 發散，因此條件收斂。"
    },
    {
      id: "ser-024",
      topic: "series",
      difficulty: 2,
      source: "Buzz original",
      prompt: "\\sum_{n=2}^{\\infty}\\frac{1}{n\\log n}",
      answerKind: "text",
      answers: ["diverges", "divergent", "發散"],
      canonical: "發散",
      timeLimit: 60,
      tabLimit: 1,
      tags: ["integral-test", "log"],
      hints: ["考慮積分判別。", "int dx/(x log x)=log log x。", "上限無窮大時會發散。"],
      solution: "由積分判別，int_2^infty dx/(x log x)=infty，所以級數發散。"
    },
    {
      id: "ser-025",
      topic: "series",
      difficulty: 3,
      source: "Buzz original",
      prompt: "\\sum_{n=1}^{\\infty}\\frac{n!}{n^n}",
      answerKind: "text",
      answers: ["converges", "convergent", "收斂"],
      canonical: "收斂",
      timeLimit: 70,
      tabLimit: 1,
      tags: ["ratio-test"],
      hints: ["使用比值判別。", "計算 a_{n+1}/a_n。", "(n/(n+1))^n 會趨近 e^{-1}。"],
      solution: "比值為 (n/(n+1))^n，極限為 e^{-1}<1，因此收斂。"
    },
    {
      id: "ser-026",
      topic: "series",
      difficulty: 2,
      source: "Buzz original",
      prompt: "\\text{Radius of convergence of }\\sum_{n=1}^{\\infty}\\frac{n^2x^n}{3^n}",
      answerKind: "numeric",
      answer: "3",
      timeLimit: 60,
      tabLimit: 1,
      tags: ["power-series", "radius"],
      hints: ["看係數大約像 n^2/3^n。", "n^2 不影響指數級半徑。", "可用根值判別。"],
      solution: "根值判別給 |x|/3<1，因此收斂半徑為 3。"
    },
    {
      id: "ser-027",
      topic: "series",
      difficulty: 2,
      source: "Buzz original",
      prompt: "\\text{Coefficient of }x^4\\text{ in }e^{2x}",
      answerKind: "numeric",
      answer: "2/3",
      timeLimit: 50,
      tabLimit: 1,
      tags: ["taylor", "coefficient"],
      hints: ["e^{2x}=sum (2x)^n/n!。", "x^4 項來自 n=4。", "係數是 2^4/4!。"],
      solution: "係數為 2^4/4! = 16/24 = 2/3。"
    },
    {
      id: "ser-028",
      topic: "series",
      difficulty: 1,
      source: "Buzz original",
      prompt: "\\sum_{n=1}^{\\infty}\\frac{1}{n^2}",
      answerKind: "text",
      answers: ["converges", "convergent", "收斂"],
      canonical: "收斂",
      timeLimit: 45,
      tabLimit: 1,
      tags: ["p-series"],
      hints: ["這是 p 級數。", "p=2。", "p>1 時收斂。"],
      solution: "p 級數 sum 1/n^p 在 p>1 時收斂，因此此級數收斂。"
    },
    {
      id: "ser-029",
      topic: "series",
      difficulty: 2,
      source: "Buzz original",
      prompt: "\\sum_{n=1}^{\\infty}\\frac{3^n}{n!}",
      answerKind: "numeric",
      answer: "exp(3)-1",
      timeLimit: 55,
      tabLimit: 1,
      tags: ["exponential-series"],
      hints: ["回想 e^x 的級數。", "e^3=sum_{n=0}^infty 3^n/n!。", "題目從 n=1 開始。"],
      solution: "e^3 的級數含 n=0 項 1，所以原級數為 e^3-1。"
    },
    {
      id: "ser-030",
      topic: "series",
      difficulty: 2,
      source: "Buzz original",
      prompt: "\\text{Radius of convergence of }\\sum_{n=1}^{\\infty}\\frac{(x-2)^n}{n5^n}",
      answerKind: "numeric",
      answer: "5",
      timeLimit: 55,
      tabLimit: 1,
      tags: ["power-series", "radius"],
      hints: ["中心平移不影響半徑。", "用比值或根值判別。", "條件是 |x-2|/5<1。"],
      solution: "根值判別得到 |x-2|/5<1，因此收斂半徑為 5。"
    }
  ];

  window.BUZZ_PROBLEMS = (window.BUZZ_PROBLEMS || []).concat(extraProblems);
})();
