(function () {
  "use strict";

  const extraProblems = [
    {
      id: "int-065",
      topic: "integrals",
      difficulty: 4,
      source: "Buzz advanced",
      prompt: "\\int_0^{\\infty}\\frac{e^{-3x}-e^{-7x}}{x}\\,dx",
      answerKind: "numeric",
      answer: "log(7/3)",
      timeLimit: 95,
      tabLimit: 1,
      tags: ["frullani", "improper-integral", "log"],
      hints: ["Use Frullani's formula.", "Compare e^{-ax} and e^{-bx}.", "The answer is log(b/a)."],
      solution: "Frullani gives int_0^infty (e^{-ax}-e^{-bx})/x dx = log(b/a). Here a=3,b=7."
    },
    {
      id: "int-066",
      topic: "integrals",
      difficulty: 4,
      source: "Buzz advanced",
      prompt: "\\int_0^{\\infty}\\frac{e^{-x}-e^{-4x}}{x}\\,dx",
      answerKind: "numeric",
      answer: "log(4)",
      timeLimit: 90,
      tabLimit: 1,
      tags: ["frullani", "improper-integral", "log"],
      hints: ["This is a direct Frullani integral.", "a=1 and b=4.", "Use log(b/a)."],
      solution: "The value is log(4/1)=log 4."
    },
    {
      id: "int-067",
      topic: "integrals",
      difficulty: 4,
      source: "Buzz advanced",
      prompt: "\\int_0^{\\infty}\\frac{e^{-2x}-e^{-8x}}{x}\\,dx",
      answerKind: "numeric",
      answer: "log(4)",
      timeLimit: 90,
      tabLimit: 1,
      tags: ["frullani", "improper-integral", "log"],
      hints: ["Again use log(b/a).", "Here b/a=8/2.", "Simplify the ratio."],
      solution: "Frullani gives log(8/2)=log 4."
    },
    {
      id: "int-068",
      topic: "integrals",
      difficulty: 4,
      source: "Buzz advanced",
      prompt: "\\int_0^{\\infty}\\frac{\\cos(2x)-\\cos(5x)}{x}\\,dx",
      answerKind: "numeric",
      answer: "log(5/2)",
      timeLimit: 100,
      tabLimit: 1,
      tags: ["frullani", "cosine-integral", "improper-integral"],
      hints: ["Use the cosine Frullani form.", "int_0^infty (cos ax - cos bx)/x dx = log(b/a).", "Take a=2,b=5."],
      solution: "The cosine Frullani identity gives log(5/2)."
    },
    {
      id: "int-069",
      topic: "integrals",
      difficulty: 4,
      source: "Buzz advanced",
      prompt: "\\int_0^{\\infty}\\frac{\\cos x-\\cos(4x)}{x}\\,dx",
      answerKind: "numeric",
      answer: "log(4)",
      timeLimit: 95,
      tabLimit: 1,
      tags: ["frullani", "cosine-integral", "improper-integral"],
      hints: ["Use the cosine version.", "The ratio is 4/1.", "The sign matches cos(ax)-cos(bx)."],
      solution: "int_0^infty (cos x - cos 4x)/x dx = log 4."
    },
    {
      id: "int-070",
      topic: "integrals",
      difficulty: 4,
      source: "Buzz advanced",
      prompt: "\\int_0^{\\infty}\\frac{\\cos(3x)-\\cos(9x)}{x}\\,dx",
      answerKind: "numeric",
      answer: "log(3)",
      timeLimit: 95,
      tabLimit: 1,
      tags: ["frullani", "cosine-integral", "improper-integral"],
      hints: ["Use log(b/a).", "Here b/a=9/3.", "So the value is log 3."],
      solution: "The integral equals log(9/3)=log 3."
    },
    {
      id: "int-071",
      topic: "integrals",
      difficulty: 4,
      source: "Buzz advanced",
      prompt: "\\int_0^{\\infty}\\frac{\\sin(3x)\\sin(8x)}{x}\\,dx",
      answerKind: "numeric",
      answer: "log(11/5)/2",
      timeLimit: 110,
      tabLimit: 1,
      tags: ["frullani", "trig", "improper-integral"],
      hints: ["Use 2sin A sin B = cos(A-B)-cos(A+B).", "Then apply the cosine Frullani identity.", "The ratio is (8+3)/(8-3)."],
      solution: "The integral is (1/2)int_0^infty (cos 5x - cos 11x)/x dx = (1/2)log(11/5)."
    },
    {
      id: "int-072",
      topic: "integrals",
      difficulty: 4,
      source: "Buzz advanced",
      prompt: "\\int_0^{\\infty}\\frac{\\sin(2x)\\sin(6x)}{x}\\,dx",
      answerKind: "numeric",
      answer: "log(2)/2",
      timeLimit: 105,
      tabLimit: 1,
      tags: ["frullani", "trig", "improper-integral"],
      hints: ["Use product-to-sum.", "The frequencies become 4 and 8.", "Then use the cosine Frullani identity."],
      solution: "The value is (1/2)log(8/4)=log(2)/2."
    },
    {
      id: "int-073",
      topic: "integrals",
      difficulty: 4,
      source: "Buzz advanced",
      prompt: "\\int_0^{\\infty}\\frac{\\sin x\\sin(4x)}{x}\\,dx",
      answerKind: "numeric",
      answer: "log(5/3)/2",
      timeLimit: 105,
      tabLimit: 1,
      tags: ["frullani", "trig", "improper-integral"],
      hints: ["Product-to-sum gives cosine frequencies 3 and 5.", "Apply Frullani to cos(3x)-cos(5x).", "Remember the factor 1/2."],
      solution: "The integral equals (1/2)log(5/3)."
    },
    {
      id: "int-074",
      topic: "integrals",
      difficulty: 4,
      source: "Buzz advanced",
      prompt: "\\int_0^{\\infty}\\frac{\\arctan(5x)-\\arctan(2x)}{x}\\,dx",
      answerKind: "numeric",
      answer: "pi*log(5/2)/2",
      timeLimit: 115,
      tabLimit: 1,
      tags: ["frullani", "inverse-trig", "improper-integral"],
      hints: ["Use Frullani with f(t)=arctan t.", "f(infinity)-f(0)=pi/2.", "The scale ratio is 5/2."],
      solution: "Frullani gives (pi/2)log(5/2)."
    },
    {
      id: "int-075",
      topic: "integrals",
      difficulty: 4,
      source: "Buzz advanced",
      prompt: "\\int_0^{\\infty}\\frac{1}{x}\\left(\\frac{1}{1+2x}-\\frac{1}{1+5x}\\right)dx",
      answerKind: "numeric",
      answer: "log(5/2)",
      timeLimit: 110,
      tabLimit: 1,
      tags: ["frullani", "rational", "improper-integral"],
      hints: ["Use f(t)=1/(1+t).", "f(0)=1 and f(infinity)=0.", "Scales are 2 and 5."],
      solution: "Frullani gives log(5/2)."
    },
    {
      id: "int-076",
      topic: "integrals",
      difficulty: 4,
      source: "Buzz advanced",
      prompt: "\\int_0^{\\infty}\\frac{1}{x}\\left(\\frac{1}{1+x}-\\frac{1}{1+6x}\\right)dx",
      answerKind: "numeric",
      answer: "log(6)",
      timeLimit: 105,
      tabLimit: 1,
      tags: ["frullani", "rational", "improper-integral"],
      hints: ["Use f(t)=1/(1+t).", "The scale ratio is 6/1.", "The integral equals log 6."],
      solution: "By Frullani, the value is log 6."
    },
    {
      id: "der-041",
      topic: "derivatives",
      difficulty: 3,
      source: "Buzz advanced",
      prompt: "\\text{Use total differential to estimate }\\Delta f\\text{ for }f=x^2y\\text{ at }(2,1),\\ dx=0.01,\\ dy=-0.02",
      answerKind: "numeric",
      answer: "-0.04",
      timeLimit: 80,
      tabLimit: 1,
      tags: ["total-differential", "linearization", "estimate"],
      hints: ["df=f_x dx+f_y dy.", "At (2,1), f_x=4 and f_y=4.", "Compute 4(0.01)+4(-0.02)."],
      solution: "df=4(0.01)+4(-0.02)=-0.04."
    },
    {
      id: "der-042",
      topic: "derivatives",
      difficulty: 3,
      source: "Buzz advanced",
      prompt: "\\text{Use total differential for }f=\\sqrt{x^2+y^2}\\text{ at }(3,4),\\ dx=0.06,\\ dy=-0.08",
      answerKind: "numeric",
      answer: "-0.028",
      timeLimit: 85,
      tabLimit: 1,
      tags: ["total-differential", "linearization", "estimate"],
      hints: ["f_x=x/r and f_y=y/r.", "At (3,4), r=5.", "df=(3/5)dx+(4/5)dy."],
      solution: "df=(3/5)(0.06)+(4/5)(-0.08)=0.036-0.064=-0.028."
    },
    {
      id: "der-043",
      topic: "derivatives",
      difficulty: 3,
      source: "Buzz advanced",
      prompt: "\\text{Estimate }\\Delta z\\text{ for }z=\\log(xy)\\text{ at }(1,2),\\ dx=0.02,\\ dy=-0.04",
      answerKind: "numeric",
      answer: "0",
      timeLimit: 75,
      tabLimit: 1,
      tags: ["total-differential", "linearization", "estimate", "log"],
      hints: ["dz=dx/x+dy/y.", "At (1,2), this is dx+dy/2.", "The two contributions cancel."],
      solution: "dz=0.02+(-0.04)/2=0."
    },
    {
      id: "der-044",
      topic: "derivatives",
      difficulty: 3,
      source: "Buzz advanced",
      prompt: "\\text{Linear part }df\\text{ of }f=e^{xy}",
      answerKind: "expression",
      answer: "y*exp(x*y)*dx+x*exp(x*y)*dy",
      variables: ["x", "y", "dx", "dy"],
      timeLimit: 90,
      tabLimit: 1,
      tags: ["total-differential", "linearization"],
      hints: ["df=f_x dx+f_y dy.", "f_x=y e^{xy}.", "f_y=x e^{xy}."],
      solution: "df=y e^{xy}dx+x e^{xy}dy."
    },
    {
      id: "der-045",
      topic: "derivatives",
      difficulty: 4,
      source: "Buzz advanced",
      prompt: "\\text{Linear part }df\\text{ of }f=\\arctan(y/x)",
      answerKind: "expression",
      answer: "-y*dx/(x^2+y^2)+x*dy/(x^2+y^2)",
      variables: ["x", "y", "dx", "dy"],
      timeLimit: 100,
      tabLimit: 1,
      tags: ["total-differential", "linearization", "inverse-trig"],
      hints: ["Use d arctan u = du/(1+u^2).", "u=y/x.", "Simplify the coefficients of dx and dy."],
      solution: "df=(-y/(x^2+y^2))dx+(x/(x^2+y^2))dy."
    },
    {
      id: "der-046",
      topic: "derivatives",
      difficulty: 3,
      source: "Buzz advanced",
      prompt: "\\text{Linear estimate of }x^2+y^2\\text{ at }(1.02,1.97)\\text{ using base }(1,2)",
      answerKind: "numeric",
      answer: "4.92",
      timeLimit: 85,
      tabLimit: 1,
      tags: ["total-differential", "linearization", "estimate"],
      hints: ["Base value is 5.", "dx=0.02 and dy=-0.03.", "df=2dx+4dy."],
      solution: "The estimate is 5+2(0.02)+4(-0.03)=4.92."
    },
    {
      id: "der-047",
      topic: "derivatives",
      difficulty: 4,
      source: "Buzz advanced",
      prompt: "\\min_{x,y}\\left(x^2+2xy+3y^2-4x-6y\\right)",
      answerKind: "numeric",
      answer: "-9/2",
      timeLimit: 100,
      tabLimit: 1,
      tags: ["total-differential-min", "optimization", "quadratic", "hessian"],
      hints: ["Set the total differential to zero.", "Equations: x+y=2 and x+3y=3.", "Evaluate the quadratic at the critical point."],
      solution: "The critical point is (3/2,1/2). The value is -9/2."
    },
    {
      id: "der-048",
      topic: "derivatives",
      difficulty: 4,
      source: "Buzz advanced",
      prompt: "\\min_{x,y}\\left(3x^2+2xy+2y^2-8x-6y\\right)",
      answerKind: "numeric",
      answer: "-9",
      timeLimit: 100,
      tabLimit: 1,
      tags: ["total-differential-min", "optimization", "quadratic", "hessian"],
      hints: ["Set partial derivatives equal to zero.", "The equations reduce to 3x+y=4 and x+2y=3.", "Evaluate at the solution."],
      solution: "The critical point is (1,1), and the minimum value is -9."
    },
    {
      id: "der-049",
      topic: "derivatives",
      difficulty: 3,
      source: "Buzz advanced",
      prompt: "\\text{x-coordinate of the minimum of }x^2+y^2+2x-4y+7",
      answerKind: "numeric",
      answer: "-1",
      timeLimit: 70,
      tabLimit: 1,
      tags: ["total-differential-min", "optimization", "quadratic"],
      hints: ["Set f_x=0.", "f_x=2x+2.", "Solve x=-1."],
      solution: "The minimum occurs at x=-1,y=2, so the x-coordinate is -1."
    },
    {
      id: "der-050",
      topic: "derivatives",
      difficulty: 4,
      source: "Buzz advanced",
      prompt: "\\min \\left(x^2+y^2\\right)\\quad\\text{subject to }x+2y=5",
      answerKind: "numeric",
      answer: "5",
      timeLimit: 95,
      tabLimit: 1,
      tags: ["total-differential-min", "optimization", "constraint"],
      hints: ["Use Lagrange multipliers or projection.", "The closest point to the origin on x+2y=5 is along (1,2).", "That point is (1,2)."],
      solution: "The closest point is (1,2), so the minimum of x^2+y^2 is 5."
    },
    {
      id: "der-051",
      topic: "derivatives",
      difficulty: 3,
      source: "Buzz advanced",
      prompt: "\\text{Hessian determinant of }f=x^2+xy+y^2",
      answerKind: "numeric",
      answer: "3",
      timeLimit: 75,
      tabLimit: 1,
      tags: ["hessian", "second-derivative"],
      hints: ["Build [[f_xx,f_xy],[f_yx,f_yy]].", "Here f_xx=2, f_yy=2, f_xy=1.", "Take determinant."],
      solution: "The Hessian is [[2,1],[1,2]], so det=3."
    },
    {
      id: "der-052",
      topic: "derivatives",
      difficulty: 3,
      source: "Buzz advanced",
      prompt: "\\text{Hessian determinant of }f=x^4+y^4\\text{ at }(1,1)",
      answerKind: "numeric",
      answer: "144",
      timeLimit: 75,
      tabLimit: 1,
      tags: ["hessian", "second-derivative"],
      hints: ["f_xx=12x^2 and f_yy=12y^2.", "The mixed derivative is 0.", "Evaluate at (1,1)."],
      solution: "The Hessian is diag(12,12), so the determinant is 144."
    },
    {
      id: "der-053",
      topic: "derivatives",
      difficulty: 4,
      source: "Buzz advanced",
      prompt: "\\text{Hessian determinant of }f=e^{xy}\\text{ at }(0,0)",
      answerKind: "numeric",
      answer: "-1",
      timeLimit: 95,
      tabLimit: 1,
      tags: ["hessian", "second-derivative", "exponential"],
      hints: ["f_xx=y^2e^{xy}.", "f_yy=x^2e^{xy}.", "f_xy=(1+xy)e^{xy}."],
      solution: "At (0,0), the Hessian is [[0,1],[1,0]], whose determinant is -1."
    },
    {
      id: "der-054",
      topic: "derivatives",
      difficulty: 4,
      source: "Buzz advanced",
      prompt: "\\text{Hessian determinant of }f=x^4+y^4-4xy\\text{ at }(1,1)",
      answerKind: "numeric",
      answer: "128",
      timeLimit: 90,
      tabLimit: 1,
      tags: ["hessian", "second-derivative"],
      hints: ["f_xx=12x^2, f_yy=12y^2, f_xy=-4.", "Evaluate at (1,1).", "Compute 12*12-16."],
      solution: "The Hessian is [[12,-4],[-4,12]], so det=144-16=128."
    },
    {
      id: "der-055",
      topic: "derivatives",
      difficulty: 3,
      source: "Buzz advanced",
      prompt: "\\text{Classify the critical point }(0,0)\\text{ of }f=x^2+y^2",
      answerKind: "text",
      answers: ["local minimum", "minimum", "min", "極小", "局部極小"],
      canonical: "local minimum",
      timeLimit: 70,
      tabLimit: 1,
      tags: ["hessian", "critical-point", "optimization"],
      hints: ["The Hessian is positive definite.", "Both eigenvalues are positive.", "So the critical point is a local minimum."],
      solution: "The Hessian is [[2,0],[0,2]], positive definite, so it is a local minimum."
    },
    {
      id: "der-056",
      topic: "derivatives",
      difficulty: 3,
      source: "Buzz advanced",
      prompt: "\\text{Classify the critical point }(0,0)\\text{ of }f=x^2-y^2",
      answerKind: "text",
      answers: ["saddle", "saddle point", "鞍點"],
      canonical: "saddle point",
      timeLimit: 70,
      tabLimit: 1,
      tags: ["hessian", "critical-point", "optimization"],
      hints: ["The Hessian has one positive and one negative direction.", "The determinant is negative.", "This means saddle."],
      solution: "The Hessian determinant is -4, so the critical point is a saddle point."
    },
    {
      id: "der-057",
      topic: "derivatives",
      difficulty: 4,
      source: "Buzz advanced",
      prompt: "\\text{Hessian determinant of }f=x^4+y^2\\text{ at }(0,0)",
      answerKind: "numeric",
      answer: "0",
      timeLimit: 70,
      tabLimit: 1,
      tags: ["hessian", "degenerate", "second-derivative"],
      hints: ["f_xx=12x^2.", "f_yy=2.", "At x=0, the determinant is 0."],
      solution: "At (0,0), the Hessian is [[0,0],[0,2]], so det=0."
    },
    {
      id: "der-058",
      topic: "derivatives",
      difficulty: 4,
      source: "Buzz advanced",
      prompt: "\\text{Hessian determinant of }f=\\log(x^2+y^2)\\text{ at }(1,0)",
      answerKind: "numeric",
      answer: "-4",
      timeLimit: 100,
      tabLimit: 1,
      tags: ["hessian", "log", "second-derivative"],
      hints: ["Compute second derivatives of log(r^2).", "At (1,0), f_xx=-2 and f_yy=2.", "The mixed derivative is 0."],
      solution: "The Hessian at (1,0) is [[-2,0],[0,2]], so the determinant is -4."
    },
    {
      id: "der-059",
      topic: "derivatives",
      difficulty: 3,
      source: "Buzz advanced",
      prompt: "\\text{Wronskian }W(\\sin x,\\cos x)",
      answerKind: "numeric",
      answer: "-1",
      timeLimit: 65,
      tabLimit: 1,
      tags: ["wronskian", "linear-independence"],
      hints: ["For two functions, W=f g'-f'g.", "g'=-sin x and f'=cos x.", "Use sin^2+cos^2=1."],
      solution: "W=sin x(-sin x)-cos x cos x=-1."
    },
    {
      id: "der-060",
      topic: "derivatives",
      difficulty: 3,
      source: "Buzz advanced",
      prompt: "\\text{Wronskian }W(\\cos x,\\sin x)",
      answerKind: "numeric",
      answer: "1",
      timeLimit: 65,
      tabLimit: 1,
      tags: ["wronskian", "linear-independence"],
      hints: ["Use W=f g'-f'g.", "Here f=cos x and g=sin x.", "Compute cos^2 x+sin^2 x."],
      solution: "W=cos x cos x-(-sin x)sin x=1."
    },
    {
      id: "der-061",
      topic: "derivatives",
      difficulty: 3,
      source: "Buzz advanced",
      prompt: "\\text{Wronskian }W(e^x,e^{2x})",
      answerKind: "expression",
      answer: "exp(3*x)",
      variables: ["x"],
      timeLimit: 70,
      tabLimit: 1,
      tags: ["wronskian", "linear-independence", "exponential"],
      hints: ["Use the 2 by 2 determinant.", "Derivative of e^{2x} is 2e^{2x}.", "Subtract e^x e^{2x}."],
      solution: "W=e^x(2e^{2x})-e^x e^{2x}=e^{3x}."
    },
    {
      id: "der-062",
      topic: "derivatives",
      difficulty: 3,
      source: "Buzz advanced",
      prompt: "\\text{Wronskian }W(x,x^2)",
      answerKind: "expression",
      answer: "x^2",
      variables: ["x"],
      timeLimit: 60,
      tabLimit: 1,
      tags: ["wronskian", "polynomial"],
      hints: ["Use W=f g'-f'g.", "g'=2x and f'=1.", "Simplify x*2x-x^2."],
      solution: "W=x(2x)-1*x^2=x^2."
    },
    {
      id: "der-063",
      topic: "derivatives",
      difficulty: 4,
      source: "Buzz advanced",
      prompt: "\\text{Wronskian }W(1,x,x^2)",
      answerKind: "numeric",
      answer: "2",
      timeLimit: 85,
      tabLimit: 1,
      tags: ["wronskian", "polynomial"],
      hints: ["Build the 3 by 3 Wronskian matrix.", "Rows are functions, first derivatives, second derivatives.", "The matrix is triangular after the first column."],
      solution: "The determinant of [[1,x,x^2],[0,1,2x],[0,0,2]] is 2."
    },
    {
      id: "der-064",
      topic: "derivatives",
      difficulty: 4,
      source: "Buzz advanced",
      prompt: "\\text{Wronskian }W(e^x,xe^x)",
      answerKind: "expression",
      answer: "exp(2*x)",
      variables: ["x"],
      timeLimit: 75,
      tabLimit: 1,
      tags: ["wronskian", "exponential"],
      hints: ["Derivative of xe^x is e^x+xe^x.", "Use the 2 by 2 determinant.", "The xe^{2x} terms cancel."],
      solution: "W=e^x(e^x+xe^x)-e^x(xe^x)=e^{2x}."
    },
    {
      id: "der-065",
      topic: "derivatives",
      difficulty: 3,
      source: "Buzz advanced",
      prompt: "\\text{Wronskian }W(1,\\log x)",
      answerKind: "expression",
      answer: "1/x",
      variables: ["x"],
      timeLimit: 65,
      tabLimit: 1,
      tags: ["wronskian", "log"],
      hints: ["Use W=f g'-f'g.", "The derivative of 1 is 0.", "The derivative of log x is 1/x."],
      solution: "W=1*(1/x)-0*log x=1/x."
    },
    {
      id: "der-066",
      topic: "derivatives",
      difficulty: 3,
      source: "Buzz advanced",
      prompt: "\\text{Wronskian }W(x^2,x^3)",
      answerKind: "expression",
      answer: "x^4",
      variables: ["x"],
      timeLimit: 65,
      tabLimit: 1,
      tags: ["wronskian", "polynomial"],
      hints: ["Use W=f g'-f'g.", "g'=3x^2 and f'=2x.", "Simplify 3x^4-2x^4."],
      solution: "W=x^2(3x^2)-(2x)(x^3)=x^4."
    },
    {
      id: "der-067",
      topic: "derivatives",
      difficulty: 3,
      source: "Buzz advanced",
      prompt: "\\text{If }u=x+y,\\ v=x-y,\\ F=u^2+v^2,\\text{ find }dF/dx",
      answerKind: "expression",
      answer: "4*x",
      variables: ["x", "y"],
      timeLimit: 80,
      tabLimit: 1,
      tags: ["jacobian-chain", "chain-rule", "multivariable"],
      hints: ["Substitute or use the chain rule.", "F=(x+y)^2+(x-y)^2=2x^2+2y^2.", "Differentiate with respect to x."],
      solution: "After substitution, F=2x^2+2y^2, so dF/dx=4x."
    },
    {
      id: "der-068",
      topic: "derivatives",
      difficulty: 4,
      source: "Buzz advanced",
      prompt: "\\text{If }u=x^2,\\ v=\\sin x,\\ F=ue^v,\\text{ find }dF/dx",
      answerKind: "expression",
      answer: "exp(sin(x))*(2*x+x^2*cos(x))",
      variables: ["x"],
      timeLimit: 95,
      tabLimit: 1,
      tags: ["jacobian-chain", "chain-rule"],
      hints: ["Substitute F=x^2e^{sin x}.", "Differentiate by product and chain rule.", "Keep both product terms."],
      solution: "d/dx[x^2e^{sin x}]=e^{sin x}(2x+x^2cos x)."
    },
    {
      id: "der-069",
      topic: "derivatives",
      difficulty: 3,
      source: "Buzz advanced",
      prompt: "\\text{Jacobian determinant of }u=x^2-y^2,\\ v=2xy",
      answerKind: "expression",
      answer: "4*(x^2+y^2)",
      variables: ["x", "y"],
      timeLimit: 80,
      tabLimit: 1,
      tags: ["jacobian-chain", "jacobian", "complex"],
      hints: ["Build the 2 by 2 derivative matrix.", "Rows: (2x,-2y) and (2y,2x).", "Compute determinant."],
      solution: "The determinant is 4x^2+4y^2=4(x^2+y^2)."
    },
    {
      id: "der-070",
      topic: "derivatives",
      difficulty: 4,
      source: "Buzz advanced",
      prompt: "\\text{Let }r=u+v,\\ s=uv,\\ u=x+y,\\ v=x-y.\\text{ Find }\\frac{\\partial(r,s)}{\\partial(x,y)}",
      answerKind: "expression",
      answer: "-4*y",
      variables: ["x", "y"],
      timeLimit: 100,
      tabLimit: 1,
      tags: ["jacobian-chain", "jacobian", "multivariable"],
      hints: ["Use determinant chain rule.", "det d(r,s)/d(u,v)=u-v.", "det d(u,v)/d(x,y)=-2."],
      solution: "The product is (u-v)(-2). Since u-v=2y, the determinant is -4y."
    },
    {
      id: "der-071",
      topic: "derivatives",
      difficulty: 3,
      source: "Buzz advanced",
      prompt: "\\text{Jacobian }\\frac{\\partial(x,y)}{\\partial(r,t)}\\text{ for }x=r\\cos t,\\ y=r\\sin t",
      answerKind: "expression",
      answer: "r",
      variables: ["r", "t"],
      timeLimit: 75,
      tabLimit: 1,
      tags: ["jacobian-chain", "jacobian", "polar-coordinates"],
      hints: ["Build [[x_r,x_t],[y_r,y_t]].", "The determinant is rcos^2 t + rsin^2 t.", "Use sin^2+cos^2=1."],
      solution: "The Jacobian is r."
    },
    {
      id: "der-072",
      topic: "derivatives",
      difficulty: 4,
      source: "Buzz advanced",
      prompt: "\\text{Jacobian }\\frac{\\partial(u,v)}{\\partial(x,y)}\\text{ for }u=xy,\\ v=x/y",
      answerKind: "expression",
      answer: "-2*x/y",
      variables: ["x", "y"],
      timeLimit: 90,
      tabLimit: 1,
      tags: ["jacobian-chain", "jacobian", "multivariable"],
      hints: ["u_x=y and u_y=x.", "v_x=1/y and v_y=-x/y^2.", "Compute the 2 by 2 determinant."],
      solution: "The determinant is y(-x/y^2)-x(1/y)=-2x/y."
    },
    {
      id: "der-073",
      topic: "derivatives",
      difficulty: 4,
      source: "Buzz advanced",
      prompt: "\\text{Let }u=2x+y,\\ v=x+3y,\\ p=u^2-v^2,\\ q=2uv.\\text{ Find }\\frac{\\partial(p,q)}{\\partial(x,y)}",
      answerKind: "expression",
      answer: "20*((2*x+y)^2+(x+3*y)^2)",
      variables: ["x", "y"],
      timeLimit: 115,
      tabLimit: 1,
      tags: ["jacobian-chain", "jacobian", "complex"],
      hints: ["The map (u,v)->(p,q) is complex squaring.", "Its Jacobian is 4(u^2+v^2).", "The linear map (x,y)->(u,v) has determinant 5."],
      solution: "By the chain rule, the determinant is 4(u^2+v^2)*5=20((2x+y)^2+(x+3y)^2)."
    },
    {
      id: "der-074",
      topic: "derivatives",
      difficulty: 4,
      source: "Buzz advanced",
      prompt: "\\text{If }f(x,y)=(x,xy),\\ g(u,v)=(u+v,u-v),\\text{ find }\\det D(g\\circ f)\\text{ at }(2,3)",
      answerKind: "numeric",
      answer: "-4",
      timeLimit: 95,
      tabLimit: 1,
      tags: ["jacobian-chain", "jacobian", "todai-inspired"],
      hints: ["Use det D(g o f)=det Dg * det Df.", "det Dg=-2.", "det Df=x, so at x=2 it is 2."],
      solution: "The determinant is (-2)*2=-4."
    },
    {
      id: "der-075",
      topic: "derivatives",
      difficulty: 3,
      source: "Buzz advanced",
      prompt: "\\text{Real part of }(x+iy)^3",
      answerKind: "expression",
      answer: "x^3-3*x*y^2",
      variables: ["x", "y"],
      timeLimit: 75,
      tabLimit: 1,
      tags: ["complex", "real-part", "polynomial"],
      hints: ["Expand (x+iy)^3.", "Use i^2=-1 and i^3=-i.", "Collect the real terms."],
      solution: "(x+iy)^3=x^3+3ix^2y-3xy^2-iy^3, so the real part is x^3-3xy^2."
    },
    {
      id: "der-076",
      topic: "derivatives",
      difficulty: 3,
      source: "Buzz advanced",
      prompt: "\\text{Imaginary part of }(x+iy)^3",
      answerKind: "expression",
      answer: "3*x^2*y-y^3",
      variables: ["x", "y"],
      timeLimit: 75,
      tabLimit: 1,
      tags: ["complex", "imaginary-part", "polynomial"],
      hints: ["Expand the cube.", "Terms with a single factor i contribute to the imaginary part.", "Terms with i^3 also contribute."],
      solution: "The imaginary part is 3x^2y-y^3."
    },
    {
      id: "der-077",
      topic: "derivatives",
      difficulty: 2,
      source: "Buzz advanced",
      prompt: "|1+i|",
      answerKind: "numeric",
      answer: "sqrt(2)",
      timeLimit: 45,
      tabLimit: 1,
      tags: ["complex", "modulus"],
      hints: ["Use |a+bi|=sqrt(a^2+b^2).", "Here a=b=1.", "So the modulus is sqrt 2."],
      solution: "|1+i|=sqrt(1^2+1^2)=sqrt 2."
    },
    {
      id: "der-078",
      topic: "derivatives",
      difficulty: 3,
      source: "Buzz advanced",
      prompt: "\\text{Real part of }(1+i)^4",
      answerKind: "numeric",
      answer: "-4",
      timeLimit: 55,
      tabLimit: 1,
      tags: ["complex", "power"],
      hints: ["First square 1+i.", "(1+i)^2=2i.", "Then square again."],
      solution: "(1+i)^4=(2i)^2=-4, so the real part is -4."
    },
    {
      id: "der-079",
      topic: "derivatives",
      difficulty: 3,
      source: "Buzz advanced",
      prompt: "\\text{Is }u=x^2-y^2,\\ v=2xy\\text{ holomorphic by Cauchy-Riemann?}",
      answerKind: "text",
      answers: ["yes", "holomorphic", "analytic", "是", "全純", "解析"],
      canonical: "holomorphic",
      timeLimit: 70,
      tabLimit: 1,
      tags: ["complex", "cauchy-riemann"],
      hints: ["Check u_x=v_y.", "Check u_y=-v_x.", "Both identities hold."],
      solution: "u_x=2x=v_y and u_y=-2y=-v_x, so the function is holomorphic."
    },
    {
      id: "der-080",
      topic: "derivatives",
      difficulty: 3,
      source: "Buzz advanced",
      prompt: "\\text{Is }u=x^2+y^2,\\ v=0\\text{ holomorphic on an open set?}",
      answerKind: "text",
      answers: ["no", "not holomorphic", "not analytic", "否", "不是"],
      canonical: "not holomorphic",
      timeLimit: 70,
      tabLimit: 1,
      tags: ["complex", "cauchy-riemann"],
      hints: ["Cauchy-Riemann requires u_x=v_y and u_y=-v_x.", "Here v_x=v_y=0.", "u_x=2x and u_y=2y do not vanish on an open set."],
      solution: "The CR equations fail except at a point, so it is not holomorphic on any open set."
    },
    {
      id: "der-081",
      topic: "derivatives",
      difficulty: 4,
      source: "Buzz advanced",
      prompt: "\\left|\\operatorname{Res}_{z=i}\\frac{1}{z^2+1}\\right|",
      answerKind: "numeric",
      answer: "1/2",
      timeLimit: 80,
      tabLimit: 1,
      tags: ["complex", "residue"],
      hints: ["Factor z^2+1=(z-i)(z+i).", "The residue at i is 1/(2i).", "Its modulus is 1/2."],
      solution: "The residue is 1/(i+i)=1/(2i), whose modulus is 1/2."
    },
    {
      id: "der-082",
      topic: "derivatives",
      difficulty: 3,
      source: "Buzz advanced",
      prompt: "\\operatorname{Res}_{z=2}\\frac{1}{(z-2)^3}",
      answerKind: "numeric",
      answer: "0",
      timeLimit: 60,
      tabLimit: 1,
      tags: ["complex", "residue", "laurent"],
      hints: ["Residue means coefficient of (z-2)^{-1}.", "This Laurent series has only (z-2)^{-3}.", "So the residue is 0."],
      solution: "There is no (z-2)^{-1} term, hence the residue is 0."
    },
    {
      id: "der-083",
      topic: "derivatives",
      difficulty: 4,
      source: "Buzz advanced",
      prompt: "\\text{Coefficient of }z^{-1}\\text{ in }e^z/z^3",
      answerKind: "numeric",
      answer: "1/2",
      timeLimit: 75,
      tabLimit: 1,
      tags: ["complex", "laurent", "residue"],
      hints: ["Use e^z=sum z^n/n!.", "After dividing by z^3, z^{-1} occurs when n=2.", "The coefficient is 1/2!."],
      solution: "e^z/z^3=sum z^{n-3}/n!, so z^{-1} comes from n=2 and has coefficient 1/2."
    },
    {
      id: "der-084",
      topic: "derivatives",
      difficulty: 3,
      source: "Buzz advanced",
      prompt: "\\frac{1}{2\\pi i}\\int_{|z|=2}\\frac{1}{z-1}\\,dz",
      answerKind: "numeric",
      answer: "1",
      timeLimit: 70,
      tabLimit: 1,
      tags: ["complex", "contour-integral", "residue"],
      hints: ["The pole z=1 is inside |z|=2.", "The residue is 1.", "The normalized contour integral equals the residue."],
      solution: "By the residue theorem, the normalized integral is 1."
    },
    {
      id: "der-085",
      topic: "derivatives",
      difficulty: 4,
      source: "Buzz advanced",
      prompt: "\\text{Real part of }f'(1+i)\\text{ for }f(z)=z^4",
      answerKind: "numeric",
      answer: "-8",
      timeLimit: 75,
      tabLimit: 1,
      tags: ["complex", "complex-derivative"],
      hints: ["f'(z)=4z^3.", "(1+i)^2=2i.", "(1+i)^3=-2+2i."],
      solution: "f'(1+i)=4(-2+2i)=-8+8i, so the real part is -8."
    },
    {
      id: "der-086",
      topic: "derivatives",
      difficulty: 3,
      source: "Buzz advanced",
      prompt: "\\text{Jacobian determinant of the complex map }z\\mapsto z^2\\text{ at }z=x+iy",
      answerKind: "expression",
      answer: "4*(x^2+y^2)",
      variables: ["x", "y"],
      timeLimit: 80,
      tabLimit: 1,
      tags: ["complex", "jacobian", "cauchy-riemann"],
      hints: ["z^2 has real part x^2-y^2 and imaginary part 2xy.", "Build the real Jacobian.", "The determinant is |2z|^2."],
      solution: "The real Jacobian determinant is 4(x^2+y^2)."
    },
    {
      id: "der-087",
      topic: "derivatives",
      difficulty: 3,
      source: "Buzz advanced",
      prompt: "\\Delta\\,\\operatorname{Re}(z^3)\\quad (z=x+iy)",
      answerKind: "numeric",
      answer: "0",
      timeLimit: 70,
      tabLimit: 1,
      tags: ["complex", "harmonic", "laplacian"],
      hints: ["Real parts of holomorphic functions are harmonic.", "You can also compute u_xx+u_yy.", "For u=x^3-3xy^2, the sum is 0."],
      solution: "u=x^3-3xy^2 has u_xx=6x and u_yy=-6x, so the Laplacian is 0."
    },
    {
      id: "der-088",
      topic: "derivatives",
      difficulty: 3,
      source: "Buzz advanced",
      prompt: "\\text{Is }u=x^3-3xy^2\\text{ harmonic?}",
      answerKind: "text",
      answers: ["yes", "harmonic", "是", "調和"],
      canonical: "harmonic",
      timeLimit: 65,
      tabLimit: 1,
      tags: ["complex", "harmonic", "laplacian"],
      hints: ["Compute u_xx+u_yy.", "u_xx=6x.", "u_yy=-6x."],
      solution: "The Laplacian is 6x-6x=0, so u is harmonic."
    }
  ];

  window.BUZZ_PROBLEMS = (window.BUZZ_PROBLEMS || []).concat(extraProblems);
})();
