(function () {
  "use strict";

  const extraProblems = [
    {
      id: "int-041",
      topic: "integrals",
      difficulty: 3,
      source: "Buzz hard integrals",
      prompt: "\\int \\frac{x^3}{1+x^4}\\,dx",
      answerKind: "antiderivative",
      answer: "log(1+x^4)/4",
      timeLimit: 70,
      tabLimit: 1,
      tags: ["substitution", "u-sub", "log"],
      hints: ["Let u=1+x^4.", "du=4x^3 dx.", "Only a constant factor remains."],
      solution: "With u=1+x^4, the antiderivative is (1/4)log(1+x^4)."
    },
    {
      id: "int-042",
      topic: "integrals",
      difficulty: 3,
      source: "Buzz hard integrals",
      prompt: "\\int x^2\\sqrt{1+x^3}\\,dx",
      answerKind: "antiderivative",
      answer: "(2/9)*(1+x^3)^(3/2)",
      timeLimit: 75,
      tabLimit: 1,
      tags: ["substitution", "u-sub", "radical"],
      hints: ["Let u=1+x^3.", "du=3x^2 dx.", "Integrate u^{1/2}."],
      solution: "u=1+x^3 gives (1/3)int u^{1/2}du = (2/9)(1+x^3)^{3/2}."
    },
    {
      id: "int-043",
      topic: "integrals",
      difficulty: 4,
      source: "Buzz hard integrals",
      prompt: "\\int \\frac{x}{\\sqrt{1+x^2}\\left(1+\\sqrt{1+x^2}\\right)}\\,dx",
      answerKind: "antiderivative",
      answer: "log(1+sqrt(1+x^2))",
      timeLimit: 95,
      tabLimit: 1,
      tags: ["substitution", "u-sub", "radical", "log"],
      hints: ["Let u=sqrt(1+x^2).", "Then du=x/sqrt(1+x^2) dx.", "The integral becomes int du/(1+u)."],
      solution: "With u=sqrt(1+x^2), the integrand becomes du/(1+u), so the answer is log(1+sqrt(1+x^2))."
    },
    {
      id: "int-044",
      topic: "integrals",
      difficulty: 3,
      source: "Buzz hard integrals",
      prompt: "\\int \\frac{x e^{x^2}}{1+e^{x^2}}\\,dx",
      answerKind: "antiderivative",
      answer: "log(1+exp(x^2))/2",
      timeLimit: 85,
      tabLimit: 1,
      tags: ["substitution", "u-sub", "exponential", "log"],
      hints: ["Let u=1+e^{x^2}.", "du=2x e^{x^2} dx.", "The result is logarithmic."],
      solution: "u=1+e^{x^2} gives (1/2)int du/u = (1/2)log(1+e^{x^2})."
    },
    {
      id: "int-045",
      topic: "integrals",
      difficulty: 3,
      source: "Buzz hard integrals",
      prompt: "\\int \\frac{(\\log x)^2}{x}\\,dx",
      answerKind: "antiderivative",
      answer: "log(x)^3/3",
      timeLimit: 70,
      tabLimit: 1,
      tags: ["substitution", "u-sub", "log"],
      hints: ["Let u=log x.", "du=dx/x.", "Integrate u^2."],
      solution: "u=log x changes the integral to int u^2 du = u^3/3."
    },
    {
      id: "int-046",
      topic: "integrals",
      difficulty: 4,
      source: "Buzz hard integrals",
      prompt: "\\int_0^1 \\frac{2x}{(1+x^2)^3}\\,dx",
      answerKind: "numeric",
      answer: "3/8",
      timeLimit: 80,
      tabLimit: 1,
      tags: ["substitution", "u-sub", "definite-integral"],
      hints: ["Let u=1+x^2.", "The bounds become 1 to 2.", "Integrate u^{-3}."],
      solution: "The integral is int_1^2 u^{-3}du = [-1/(2u^2)]_1^2 = 3/8."
    },
    {
      id: "int-047",
      topic: "integrals",
      difficulty: 4,
      source: "Buzz hard integrals",
      prompt: "\\int_0^2 \\sqrt{4-x^2}\\,dx",
      answerKind: "numeric",
      answer: "pi",
      timeLimit: 75,
      tabLimit: 1,
      tags: ["trig-substitution", "definite-integral", "area"],
      hints: ["Use x=2sin theta, or read it as a quarter circle.", "The radius is 2.", "Quarter area of a radius 2 circle is pi."],
      solution: "The graph is the upper quarter of x^2+y^2=4, so the area is pi."
    },
    {
      id: "int-048",
      topic: "integrals",
      difficulty: 4,
      source: "Buzz hard integrals",
      prompt: "\\int_0^1 \\frac{x^2}{\\sqrt{1-x^2}}\\,dx",
      answerKind: "numeric",
      answer: "pi/4",
      timeLimit: 90,
      tabLimit: 1,
      tags: ["trig-substitution", "definite-integral"],
      hints: ["Let x=sin theta.", "dx=cos theta dtheta and sqrt(1-x^2)=cos theta.", "The integral becomes int_0^{pi/2} sin^2 theta dtheta."],
      solution: "After x=sin theta, the integral is int_0^{pi/2} sin^2 theta dtheta = pi/4."
    },
    {
      id: "int-049",
      topic: "integrals",
      difficulty: 4,
      source: "Buzz hard integrals",
      prompt: "\\int_0^2 \\frac{x^2}{\\sqrt{4-x^2}}\\,dx",
      answerKind: "numeric",
      answer: "pi",
      timeLimit: 95,
      tabLimit: 1,
      tags: ["trig-substitution", "definite-integral"],
      hints: ["Let x=2sin theta.", "The integral becomes 4int_0^{pi/2} sin^2 theta dtheta.", "Use int_0^{pi/2} sin^2 theta dtheta=pi/4."],
      solution: "With x=2sin theta, the integral becomes 4*(pi/4)=pi."
    },
    {
      id: "int-050",
      topic: "integrals",
      difficulty: 4,
      source: "Buzz hard integrals",
      prompt: "\\int_1^2 \\frac{1}{x\\sqrt{x^2-1}}\\,dx",
      answerKind: "numeric",
      answer: "pi/3",
      timeLimit: 95,
      tabLimit: 1,
      tags: ["trig-substitution", "inverse-trig", "definite-integral"],
      hints: ["Use x=sec theta.", "Then sqrt(x^2-1)=tan theta.", "Bounds are theta=0 to theta=pi/3."],
      solution: "With x=sec theta, the integrand becomes dtheta. The bounds give pi/3."
    },
    {
      id: "int-051",
      topic: "integrals",
      difficulty: 4,
      source: "Buzz hard integrals",
      prompt: "\\int \\frac{1}{(x^2+4)^{3/2}}\\,dx",
      answerKind: "antiderivative",
      answer: "x/(4*sqrt(x^2+4))",
      timeLimit: 95,
      tabLimit: 1,
      tags: ["trig-substitution", "radical"],
      hints: ["This is the derivative of x/sqrt(x^2+a^2) up to a factor.", "Here a^2=4.", "Differentiate x/(4sqrt(x^2+4)) to check."],
      solution: "The standard result is int dx/(x^2+a^2)^{3/2}=x/(a^2 sqrt(x^2+a^2)); here a^2=4."
    },
    {
      id: "int-052",
      topic: "integrals",
      difficulty: 3,
      source: "Buzz hard integrals",
      prompt: "\\int x^2e^x\\,dx",
      answerKind: "antiderivative",
      answer: "exp(x)*(x^2-2*x+2)",
      timeLimit: 90,
      tabLimit: 1,
      tags: ["integration-by-parts", "ibp", "exponential"],
      hints: ["Use integration by parts twice.", "Each step lowers the power of x.", "The final pattern is e^x times a quadratic."],
      solution: "Two rounds of IBP give e^x(x^2-2x+2)."
    },
    {
      id: "int-053",
      topic: "integrals",
      difficulty: 4,
      source: "Buzz hard integrals",
      prompt: "\\int x^2\\sin x\\,dx",
      answerKind: "antiderivative",
      answer: "-x^2*cos(x)+2*x*sin(x)+2*cos(x)",
      timeLimit: 100,
      tabLimit: 1,
      tags: ["integration-by-parts", "ibp", "trig"],
      hints: ["Use IBP with u=x^2.", "A second IBP handles int x cos x dx.", "Track signs carefully."],
      solution: "IBP gives -x^2 cos x + 2int x cos x dx = -x^2 cos x + 2x sin x + 2cos x."
    },
    {
      id: "int-055",
      topic: "integrals",
      difficulty: 4,
      source: "Buzz hard integrals",
      prompt: "\\int (\\log x)^2\\,dx",
      answerKind: "antiderivative",
      answer: "x*(log(x)^2-2*log(x)+2)",
      timeLimit: 100,
      tabLimit: 1,
      tags: ["integration-by-parts", "ibp", "log"],
      hints: ["Take u=(log x)^2 and dv=dx.", "Then du=2log(x)/x dx.", "A second known integral int log x dx appears."],
      solution: "IBP gives x(log x)^2-2int log x dx = x(log x)^2-2(xlog x-x)."
    },
    {
      id: "int-056",
      topic: "integrals",
      difficulty: 4,
      source: "Buzz hard integrals",
      prompt: "\\int_0^1 x\\arctan x\\,dx",
      answerKind: "numeric",
      answer: "pi/4-1/2",
      timeLimit: 100,
      tabLimit: 1,
      tags: ["integration-by-parts", "ibp", "inverse-trig", "definite-integral"],
      hints: ["Use u=arctan x and dv=x dx.", "Then x^2/(1+x^2)=1-1/(1+x^2).", "Evaluate from 0 to 1."],
      solution: "IBP gives pi/8 - (1/2)int_0^1 x^2/(1+x^2)dx = pi/8 - 1/2 + pi/8 = pi/4-1/2."
    },
    {
      id: "int-057",
      topic: "integrals",
      difficulty: 4,
      source: "Buzz hard integrals",
      prompt: "\\text{Find }F(x)=\\int_0^x e^{x-t}\\sin t\\,dt",
      answerKind: "expression",
      answer: "(exp(x)-sin(x)-cos(x))/2",
      timeLimit: 110,
      tabLimit: 1,
      tags: ["ode-style", "convolution", "parameter-integral"],
      hints: ["Treat x as the outside variable.", "This convolution satisfies F'-F=sin x with F(0)=0.", "Solve or integrate e^x int_0^x e^{-t}sin t dt."],
      solution: "F=e^x int_0^x e^{-t}sin t dt = (e^x-sin x-cos x)/2."
    },
    {
      id: "int-058",
      topic: "integrals",
      difficulty: 4,
      source: "Buzz hard integrals",
      prompt: "\\text{Find }F(x)=\\int_0^x e^{2(x-t)}t\\,dt",
      answerKind: "expression",
      answer: "(exp(2*x)-2*x-1)/4",
      timeLimit: 105,
      tabLimit: 1,
      tags: ["ode-style", "convolution", "parameter-integral"],
      hints: ["This satisfies F'-2F=x and F(0)=0.", "A direct route is e^{2x}int_0^x t e^{-2t}dt.", "Simplify after evaluating the definite integral."],
      solution: "e^{2x}int_0^x t e^{-2t}dt = e^{2x}/4-x/2-1/4."
    },
    {
      id: "int-059",
      topic: "integrals",
      difficulty: 4,
      source: "Buzz hard integrals",
      prompt: "\\text{Find }F(x)=\\int_0^x e^{-(x-t)}t^2\\,dt",
      answerKind: "expression",
      answer: "x^2-2*x+2-2*exp(-x)",
      timeLimit: 110,
      tabLimit: 1,
      tags: ["ode-style", "convolution", "parameter-integral"],
      hints: ["This satisfies F'+F=x^2 and F(0)=0.", "Try a quadratic particular solution.", "Use the initial condition for the exponential term."],
      solution: "Solving F'+F=x^2 with F(0)=0 gives F=x^2-2x+2-2e^{-x}."
    },
    {
      id: "int-060",
      topic: "integrals",
      difficulty: 4,
      source: "Buzz hard integrals",
      prompt: "\\text{Find }F(x)=\\int_0^x \\sin(x-t)\\cos t\\,dt",
      answerKind: "expression",
      answer: "x*sin(x)/2",
      timeLimit: 110,
      tabLimit: 1,
      tags: ["ode-style", "convolution", "trig"],
      hints: ["Use convolution thinking or trig identities.", "sin(x-t)cos t = sin x cos^2 t - cos x sin t cos t.", "The non-x terms cancel."],
      solution: "Expanding and integrating gives x sin x/2."
    },
    {
      id: "int-061",
      topic: "integrals",
      difficulty: 4,
      source: "Buzz hard integrals",
      prompt: "\\int_0^{\\pi/2}\\frac{\\sin^3x}{\\sin^3x+\\cos^3x}\\,dx",
      answerKind: "numeric",
      answer: "pi/4",
      timeLimit: 85,
      tabLimit: 1,
      tags: ["kings-property", "symmetry", "definite-integral"],
      hints: ["Use x -> pi/2-x.", "The transformed numerator becomes cos^3 x.", "Adding the two integrals gives pi/2."],
      solution: "Let I be the integral. The transformed integral has cos^3 numerator. Adding gives 2I=int_0^{pi/2}1 dx=pi/2."
    },
    {
      id: "int-062",
      topic: "integrals",
      difficulty: 4,
      source: "Buzz hard integrals",
      prompt: "\\int_0^1\\frac{e^x}{e^x+e^{1-x}}\\,dx",
      answerKind: "numeric",
      answer: "1/2",
      timeLimit: 80,
      tabLimit: 1,
      tags: ["kings-property", "symmetry", "definite-integral"],
      hints: ["Use x -> 1-x.", "The transformed numerator is e^{1-x}.", "The two integrands add to 1."],
      solution: "I plus its transformed version equals int_0^1 1 dx=1, so I=1/2."
    },
    {
      id: "int-063",
      topic: "integrals",
      difficulty: 4,
      source: "Buzz hard integrals",
      prompt: "\\int_0^{\\pi/2}\\frac{1+\\sin x}{2+\\sin x+\\cos x}\\,dx",
      answerKind: "numeric",
      answer: "pi/4",
      timeLimit: 90,
      tabLimit: 1,
      tags: ["kings-property", "symmetry", "definite-integral"],
      hints: ["Use x -> pi/2-x.", "The transformed numerator is 1+cos x.", "The two integrands add to 1."],
      solution: "Adding the integral to its transformed copy gives int_0^{pi/2}1 dx=pi/2, hence I=pi/4."
    },
    {
      id: "int-064",
      topic: "integrals",
      difficulty: 4,
      source: "Buzz hard integrals",
      prompt: "\\int_0^\\pi \\frac{x\\sin x}{1+\\cos^2x}\\,dx",
      answerKind: "numeric",
      answer: "pi^2/4",
      timeLimit: 110,
      tabLimit: 1,
      tags: ["kings-property", "symmetry", "definite-integral"],
      hints: ["Use x -> pi-x.", "The non-x factor is symmetric.", "Then I=(pi/2)int_0^pi sin x/(1+cos^2 x) dx."],
      solution: "The symmetric factor gives I=(pi/2)int_0^pi sin x/(1+cos^2x)dx. With u=cos x, the remaining integral is pi/2, so I=pi^2/4."
    }
  ];

  window.BUZZ_PROBLEMS = (window.BUZZ_PROBLEMS || []).concat(extraProblems);
})();
